// ============================================

const LANGUAGES = {
    "it": {
        "name": "Italiano",
        "flag": "🇮🇹"
    },
    "es": {
        "name": "Español",
        "flag": "🇪🇸"
    },
    "fr": {
        "name": "Français",
        "flag": "🇫🇷"
    },
    "de": {
        "name": "Deutsch",
        "flag": "🇩🇪"
    },
    "tr": {
        "name": "Türkçe",
        "flag": "🇹🇷"
    },
    "ru": {
        "name": "Русский",
        "flag": "🇷🇺"
    },
    "ja": {
        "name": "日本語",
        "flag": "🇯🇵"
    },
    "pl": {
        "name": "Polski",
        "flag": "🇵🇱"
    },
    "hu": {
        "name": "Magyar",
        "flag": "🇭🇺"
    },
    "pt": {
        "name": "Português",
        "flag": "🇵🇹"
    },
    "hi": {
        "name": "हिन्दी",
        "flag": "🇮🇳"
    },
    "ko": {
        "name": "한국어",
        "flag": "🇰🇷"
    },
    "zh": {
        "name": "中文",
        "flag": "🇨🇳"
    },
    "haw": {
        "name": "Ōlelo Hawaiʻi",
        "flag": "🌺"
    }
};

let CURRENT_LANG = localStorage.getItem('waitress_game_lang') || 'it';

const AUTO_TRANSLATIONS = {
    "it": {
        "GIOCA": "▶ GIOCA",
        "IMPOSTAZIONI": "⚙ IMPOSTAZIONI",
        "CREDITI": "ℹ CREDITI",
        "TORNA": "↩ TORNA AL MENU",
        "VAI A CASA": "🏠 VAI A CASA",
        "GIORNO": "⭐ Giorno",
        "INCASSO": "💰 Incasso:",
        "SERVITI": "👥 Serviti:",
        "VASSOIO": "📋 Vassoio:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 LAVELLO",
        "PRONTO": "Pronto! 👨‍🍳",
        "OCCUPATO": "Postazione occupata!",
        "LOADING": "Caricamento...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATORE DI CAMERIERA & VITA DA CASALINGA",
        "NOTEPAD_TITLE": "📝 COMANDA",
        "NOTEPAD_EMPTY": "Taccuino Vuoto",
        "NOTEPAD_READY": "Pronto per ordini",
        "NOTEPAD_TABLE": "Tavolo:",
        "DAY_COMPLETE": "⭐ GIORNATA COMPLETATA! ⭐",
        "DAY_FAILED": "💀 GIORNATA FALLITA 💀",
        "DAY_FAILED_DESC": "Hai perso tutte le vite a causa dei clienti arrabbiati!",
        "SAVINGS_LEFT": "💰 Risparmi rimasti:",
        "DAYS_WORKED": "📅 Giorni lavorati:",
        "FURNITURE_BOUGHT": "🛋️ Mobili acquistati:",
        "AUDIO_SETTINGS": "🔊 Audio di gioco",
        "ACTIVE": "ATTIVO",
        "DISABLED": "DISATTIVATO",
        "DIFFICULTY_LEVEL": "📊 Livello di Difficoltà",
        "EASY": "FACILE",
        "NORMAL": "NORMALE",
        "HARD": "DIFFICILE",
        "CONTROL_SYSTEM": "🎮 Sistema di Controlli",
        "KEYBOARD": "TASTIERA:",
        "LANGUAGE_SELECT": "🌐 Lingua / Language",
        "CREDITS_TITLE": "ℹ CREDITI DI SVILUPPO",
        "CREDITS_IDEATION": "🎮 IDEAZIONE & CODICE ORIGINALE",
        "CREDITS_SUPPORT": "🏠 CON IL SUPPORTO DI",
        "CREDITS_GRAPHICS": "🎨 GRAFICA & ANIMAZIONI",
        "CREDITS_TECH": "🛠️ TECNOLOGIE INTEGRATE",
        "CREDITS_LICENSE": "📝 LICENZA",
        "ERR_CLOSE_TABLE": "🚫 Avvicinati al tavolo!",
        "ERR_ALREADY_ORDER": "❌ Hai già una comanda!",
        "ERR_SINK_FULL": "🚨 Lavello sovraccarico! Lava i piatti!",
        "ERR_CLOSE_COUNTER": "🚫 Avvicinati al bancone!",
        "ERR_NO_FOOD_SERVED": "❌ Non serviamo questo cibo!",
        "ERR_TRAY_FULL": "❌ Vassoio stracolmo!",
        "ERR_NO_READY_FOOD": "📦 Nessun cibo pronto!",
        "ERR_CLOSE_SINK": "🚫 Avvicinati al lavello!",
        "MSG_ORDER_TAKEN": "📝 Comanda Scritta!",
        "MSG_ORDER_REC": "📝 Ordine preso!",
        "MSG_SERVED": "🍽️ Servito!",
        "MSG_TABLE_CLEARED": "🧹 Tavolo Sbarazzato!",
        "MSG_TABLE_FREE": "🪑 Tavolo libero",
        "FOOD_READY": "pronto!",
        "FOOD_TAKEN": "prelevato!",
        "TRICK_CLICKS": "🔑 Trucco:",
        "CLICKS_LEFT": "clic...",
        "WASHING": "🧼 Lavando...",
        "WASH_CLEAN": "✨ Piatti puliti!",
        "WASH_NONE": "🧼 Nessun piatto",
        "LEAVING_ANGRY": "😡 Se ne va!",
        "TABLE_SHORT": "Tav."
    },
    "es": {
        "GIOCA": "▶ JUGAR",
        "IMPOSTAZIONI": "⚙ AJUSTES",
        "CREDITI": "ℹ CRÉDITOS",
        "TORNA": "↩ VOLVER AL MENÚ",
        "VAI A CASA": "🏠 IR A CASA",
        "GIORNO": "⭐ Día",
        "INCASSO": "💰 Ganancias:",
        "SERVITI": "👥 Atendidos:",
        "VASSOIO": "📋 Bandeja:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 FREGADERO",
        "PRONTO": "¡Listo! 👨‍🍳",
        "OCCUPATO": "¡Estación ocupada!",
        "LOADING": "Cargando...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULADOR DE CAMARERA Y VIDA EN CASA",
        "NOTEPAD_TITLE": "📝 PEDIDO",
        "NOTEPAD_EMPTY": "Bloc vacío",
        "NOTEPAD_READY": "Listo para pedidos",
        "NOTEPAD_TABLE": "Mesa:",
        "DAY_COMPLETE": "⭐ ¡DÍA COMPLETADO! ⭐",
        "DAY_FAILED": "💀 DÍA FALLIDO 💀",
        "DAY_FAILED_DESC": "¡Has perdido todas las vidas por clientes enfadados!",
        "SAVINGS_LEFT": "💰 Ahorros restantes:",
        "DAYS_WORKED": "📅 Días trabajados:",
        "FURNITURE_BOUGHT": "🛋️ Muebles comprados:",
        "AUDIO_SETTINGS": "🔊 Audio del juego",
        "ACTIVE": "ACTIVADO",
        "DISABLED": "DESACTIVADO",
        "DIFFICULTY_LEVEL": "📊 Dificultad",
        "EASY": "FÁCIL",
        "NORMAL": "NORMAL",
        "HARD": "DIFÍCIL",
        "CONTROL_SYSTEM": "🎮 Controles",
        "KEYBOARD": "TECLADO:",
        "LANGUAGE_SELECT": "🌐 Idioma / Language",
        "CREDITS_TITLE": "ℹ CRÉDITOS DE DESARROLLO",
        "CREDITS_IDEATION": "🎮 IDEACIÓN Y CÓDIGO ORIGINAL",
        "CREDITS_SUPPORT": "🏠 CON EL APOYO DE",
        "CREDITS_GRAPHICS": "🎨 GRÁFICOS Y ANIMACIONES",
        "CREDITS_TECH": "🛠️ TECNOLOGÍAS INTEGRADAS",
        "CREDITS_LICENSE": "📝 LICENCIA",
        "ERR_CLOSE_TABLE": "🚫 ¡Acércate a la mesa!",
        "ERR_ALREADY_ORDER": "❌ ¡Ya tienes una comanda!",
        "ERR_SINK_FULL": "🚨 ¡Fregadero lleno! ¡Lava los platos!",
        "ERR_CLOSE_COUNTER": "🚫 ¡Acércate a la barra!",
        "ERR_NO_FOOD_SERVED": "❌ ¡No servimos esta comida!",
        "ERR_TRAY_FULL": "❌ ¡Bandeja llena!",
        "ERR_NO_READY_FOOD": "📦 ¡No hay comida lista!",
        "ERR_CLOSE_SINK": "🚫 ¡Acércate al fregadero!",
        "MSG_ORDER_TAKEN": "📝 ¡Pedido Tomado!",
        "MSG_ORDER_REC": "📝 ¡Orden recibida!",
        "MSG_SERVED": "🍽️ ¡Servido!",
        "MSG_TABLE_CLEARED": "🧹 ¡Mesa Limpia!",
        "MSG_TABLE_FREE": "🪑 Mesa libre",
        "FOOD_READY": "¡listo!",
        "FOOD_TAKEN": "¡recogido!",
        "TRICK_CLICKS": "🔑 Truco:",
        "CLICKS_LEFT": "clics...",
        "WASHING": "🧼 Lavando...",
        "WASH_CLEAN": "✨ ¡Platos limpios!",
        "WASH_NONE": "🧼 No hay platos",
        "LEAVING_ANGRY": "😡 ¡Se va!",
        "TABLE_SHORT": "Mesa"
    },
    "fr": {
        "GIOCA": "▶ JOUER",
        "IMPOSTAZIONI": "⚙ PARAMÈTRES",
        "CREDITI": "ℹ CRÉDITS",
        "TORNA": "↩ RETOUR AU MENU",
        "VAI A CASA": "🏠 RENTRER",
        "GIORNO": "⭐ Jour",
        "INCASSO": "💰 Gains:",
        "SERVITI": "👥 Servis:",
        "VASSOIO": "📋 Plateau:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 ÉVIER",
        "PRONTO": "Prêt! 👨‍🍳",
        "OCCUPATO": "Poste occupé!",
        "LOADING": "Chargement...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATEUR DE SERVEUSE & VIE À LA MAISON",
        "NOTEPAD_TITLE": "📝 COMMANDE",
        "NOTEPAD_EMPTY": "Carnet Vide",
        "NOTEPAD_READY": "Prêt pour les commandes",
        "NOTEPAD_TABLE": "Table:",
        "DAY_COMPLETE": "⭐ JOURNÉE RÉUSSIE! ⭐",
        "DAY_FAILED": "💀 ÉCHEC DE LA JOURNÉE 💀",
        "DAY_FAILED_DESC": "Vous avez perdu toutes vos vies à cause de clients mécontents!",
        "SAVINGS_LEFT": "💰 Économies restantes:",
        "DAYS_WORKED": "📅 Jours travaillés:",
        "FURNITURE_BOUGHT": "🛋️ Meubles achetés:",
        "AUDIO_SETTINGS": "🔊 Audio du jeu",
        "ACTIVE": "ACTIVÉ",
        "DISABLED": "DÉSACTIVÉ",
        "DIFFICULTY_LEVEL": "📊 Niveau de Difficulté",
        "EASY": "FACILE",
        "NORMAL": "NORMAL",
        "HARD": "DIFFICILE",
        "CONTROL_SYSTEM": "🎮 Système de Contrôle",
        "KEYBOARD": "CLAVIER:",
        "LANGUAGE_SELECT": "🌐 Langue / Language",
        "CREDITS_TITLE": "ℹ CRÉDITS",
        "CREDITS_IDEATION": "🎮 IDÉE & CODE ORIGINAL",
        "CREDITS_SUPPORT": "🏠 AVEC LE SOUTIEN DE",
        "CREDITS_GRAPHICS": "🎨 GRAPHISMES & ANIMATIONS",
        "CREDITS_TECH": "🛠️ TECHNOLOGIES INTÉGRÉES",
        "CREDITS_LICENSE": "📝 LICENCE",
        "ERR_CLOSE_TABLE": "🚫 Approchez-vous de la table!",
        "ERR_ALREADY_ORDER": "❌ Vous avez déjà une commande!",
        "ERR_SINK_FULL": "🚨 Évier débordé! Lavez les assiettes!",
        "ERR_CLOSE_COUNTER": "🚫 Approchez-vous du comptoir!",
        "ERR_NO_FOOD_SERVED": "❌ Nous ne servons pas ceci!",
        "ERR_TRAY_FULL": "❌ Plateau plein!",
        "ERR_NO_READY_FOOD": "📦 Pas de plat prêt!",
        "ERR_CLOSE_SINK": "🚫 Approchez-vous de l'évier!",
        "MSG_ORDER_TAKEN": "📝 Commande prise!",
        "MSG_ORDER_REC": "📝 Ordre reçu!",
        "MSG_SERVED": "🍽️ Servi!",
        "MSG_TABLE_CLEARED": "🧹 Table débarrassée!",
        "MSG_TABLE_FREE": "🪑 Table libre",
        "FOOD_READY": "prêt!",
        "FOOD_TAKEN": "récupéré!",
        "TRICK_CLICKS": "🔑 Astuce:",
        "CLICKS_LEFT": "clics...",
        "WASHING": "🧼 Lavage...",
        "WASH_CLEAN": "✨ Assiettes propres!",
        "WASH_NONE": "🧼 Pas d'assiette",
        "LEAVING_ANGRY": "😡 Il part!",
        "TABLE_SHORT": "Tab."
    },
    "de": {
        "GIOCA": "▶ SPIELEN",
        "IMPOSTAZIONI": "⚙ EINSTELLUNGEN",
        "CREDITI": "ℹ CREDITS",
        "TORNA": "↩ ZURÜCK ZUM MENÜ",
        "VAI A CASA": "🏠 NACH HAUSE",
        "GIORNO": "⭐ Tag",
        "INCASSO": "💰 Einnahmen:",
        "SERVITI": "👥 Bedient:",
        "VASSOIO": "📋 Tablett:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 SPÜLE",
        "PRONTO": "Fertig! 👨‍🍳",
        "OCCUPATO": "Station besetzt!",
        "LOADING": "Laden...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "KELLNERIN & HAUSHALT SIMULATOR",
        "NOTEPAD_TITLE": "📝 BESTELLUNG",
        "NOTEPAD_EMPTY": "Notizblock leer",
        "NOTEPAD_READY": "Bereit für Bestellungen",
        "NOTEPAD_TABLE": "Tisch:",
        "DAY_COMPLETE": "⭐ TAG ERFOLGREICH! ⭐",
        "DAY_FAILED": "💀 TAG FEHLGESCHLAGEN 💀",
        "DAY_FAILED_DESC": "Du hast alle Leben durch verärgerte Kunden verloren!",
        "SAVINGS_LEFT": "💰 Verbleibende Ersparnisse:",
        "DAYS_WORKED": "📅 Gearbeitete Tage:",
        "FURNITURE_BOUGHT": "🛋️ Gekaufte Möbel:",
        "AUDIO_SETTINGS": "🔊 Spiel-Audio",
        "ACTIVE": "AKTIV",
        "DISABLED": "DEAKTIVIERT",
        "DIFFICULTY_LEVEL": "📊 Schwierigkeitsgrad",
        "EASY": "EINFACH",
        "NORMAL": "NORMAL",
        "HARD": "SCHWER",
        "CONTROL_SYSTEM": "🎮 Steuerung",
        "KEYBOARD": "TASTATUR:",
        "LANGUAGE_SELECT": "🌐 Sprache / Language",
        "CREDITS_TITLE": "ℹ ENTWICKLER-CREDITS",
        "CREDITS_IDEATION": "🎮 IDEE & CODE",
        "CREDITS_SUPPORT": "🏠 UNTERSTÜTZT VON",
        "CREDITS_GRAPHICS": "🎨 GRAFIK & ANIMATIONEN",
        "CREDITS_TECH": "🛠️ INTEGRATIONEN",
        "CREDITS_LICENSE": "📝 LIZENZ",
        "ERR_CLOSE_TABLE": "🚫 Geh näher zum Tisch!",
        "ERR_ALREADY_ORDER": "❌ Du hast bereits eine Bestellung!",
        "ERR_SINK_FULL": "🚨 Spüle voll! Wasche das Geschirr!",
        "ERR_CLOSE_COUNTER": "🚫 Geh näher zum Tresen!",
        "ERR_NO_FOOD_SERVED": "❌ Das servieren wir nicht!",
        "ERR_TRAY_FULL": "❌ Tablett voll!",
        "ERR_NO_READY_FOOD": "📦 Kein Essen bereit!",
        "ERR_CLOSE_SINK": "🚫 Geh näher zur Spüle!",
        "MSG_ORDER_TAKEN": "📝 Bestellung aufgenommen!",
        "MSG_ORDER_REC": "📝 Bestellung erhalten!",
        "MSG_SERVED": "🍽️ Serviert!",
        "MSG_TABLE_CLEARED": "🧹 Tisch abgeräumt!",
        "MSG_TABLE_FREE": "🪑 Tisch frei",
        "FOOD_READY": "fertig!",
        "FOOD_TAKEN": "abgeholt!",
        "TRICK_CLICKS": "🔑 Trick:",
        "CLICKS_LEFT": "Klicks...",
        "WASHING": "🧼 Spülen...",
        "WASH_CLEAN": "✨ Geschirr sauber!",
        "WASH_NONE": "🧼 Kein Geschirr",
        "LEAVING_ANGRY": "😡 Geht verärgert!",
        "TABLE_SHORT": "Tisch"
    },
    "tr": {
        "GIOCA": "▶ OYNA",
        "IMPOSTAZIONI": "⚙ AYARLAR",
        "CREDITI": "ℹ EMEĞİ GEÇENLER",
        "TORNA": "↩ MENÜYE DÖN",
        "VAI A CASA": "🏠 EVE GİT",
        "GIORNO": "⭐ Gün",
        "INCASSO": "💰 Kazanç:",
        "SERVITI": "👥 Hizmet Edilen:",
        "VASSOIO": "📋 Tepsi:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 EVIYE",
        "PRONTO": "Hazır! 👨‍🍳",
        "OCCUPATO": "İstasyon dolu!",
        "LOADING": "Yükleniyor...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "GARSON & EV YAŞAMI SİMÜLATÖRÜ",
        "NOTEPAD_TITLE": "📝 SİPARİŞ",
        "NOTEPAD_EMPTY": "Not Defteri Boş",
        "NOTEPAD_READY": "Siparişler için hazır",
        "NOTEPAD_TABLE": "Masa:",
        "DAY_COMPLETE": "⭐ GÜN TAMAMLANDI! ⭐",
        "DAY_FAILED": "💀 GÜN BAŞARISIZ 💀",
        "DAY_FAILED_DESC": "Kızgın müşteriler yüzünden tüm canlarını kaybettin!",
        "SAVINGS_LEFT": "💰 Kalan Birikim:",
        "DAYS_WORKED": "📅 Çalışılan Gün:",
        "FURNITURE_BOUGHT": "🛋️ Alınan Mobilya:",
        "AUDIO_SETTINGS": "🔊 Oyun Sesi",
        "ACTIVE": "AÇIK",
        "DISABLED": "KAPALI",
        "DIFFICULTY_LEVEL": "📊 Zorluk Seviyesi",
        "EASY": "KOLAY",
        "NORMAL": "NORMAL",
        "HARD": "ZOR",
        "CONTROL_SYSTEM": "🎮 Kontrol Sistemi",
        "KEYBOARD": "KLAVYE:",
        "LANGUAGE_SELECT": "🌐 Dil / Language",
        "CREDITS_TITLE": "ℹ EMEĞİ GEÇENLER",
        "CREDITS_IDEATION": "🎮 FİKİR & KODLAMA",
        "CREDITS_SUPPORT": "🏠 DESTEKLEYENLER",
        "CREDITS_GRAPHICS": "🎨 GRAFİK & ANİMASYON",
        "CREDITS_TECH": "🛠️ TEKNOLOJİLER",
        "CREDITS_LICENSE": "📝 LİSANS",
        "ERR_CLOSE_TABLE": "🚫 Masaya yaklaşın!",
        "ERR_ALREADY_ORDER": "❌ Zaten bir sipariş var!",
        "ERR_SINK_FULL": "🚨 Eviye dolu! Bulaşıkları yıka!",
        "ERR_CLOSE_COUNTER": "🚫 Tezgaha yaklaşın!",
        "ERR_NO_FOOD_SERVED": "❌ Bu yemeği servis etmiyoruz!",
        "ERR_TRAY_FULL": "❌ Tepsi dolu!",
        "ERR_NO_READY_FOOD": "📦 Hazır yemek yok!",
        "ERR_CLOSE_SINK": "🚫 Eviyeye yaklaşın!",
        "MSG_ORDER_TAKEN": "📝 Sipariş Alındı!",
        "MSG_ORDER_REC": "📝 Sipariş alındı!",
        "MSG_SERVED": "🍽️ Servis Edildi!",
        "MSG_TABLE_CLEARED": "🧹 Masa Temizlendi!",
        "MSG_TABLE_FREE": "🪑 Masa boş",
        "FOOD_READY": "hazır!",
        "FOOD_TAKEN": "alındı!",
        "TRICK_CLICKS": "🔑 Hile:",
        "CLICKS_LEFT": "tık...",
        "WASHING": "🧼 Yıkanıyor...",
        "WASH_CLEAN": "✨ Bulaşıklar temiz!",
        "WASH_NONE": "🧼 Bulaşık yok",
        "LEAVING_ANGRY": "😡 Ayrılıyor!",
        "TABLE_SHORT": "Masa"
    },
    "ru": {
        "GIOCA": "▶ ИГРАТЬ",
        "IMPOSTAZIONI": "⚙ НАСТРОЙКИ",
        "CREDITI": "ℹ АВТОРЫ",
        "TORNA": "↩ В МЕНЮ",
        "VAI A CASA": "🏠 ДОМОЙ",
        "GIORNO": "⭐ День",
        "INCASSO": "💰 Выручка:",
        "SERVITI": "👥 Обслужено:",
        "VASSOIO": "📋 Поднос:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 РАКОВИНА",
        "PRONTO": "Готово! 👨‍🍳",
        "OCCUPATO": "Занято!",
        "LOADING": "Загрузка...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "СИМУЛЯТОР ОФИЦИАНТКИ И ДОМАШНЕЙ ЖИЗНИ",
        "NOTEPAD_TITLE": "📝 ЗАКАЗ",
        "NOTEPAD_EMPTY": "Блокнот пуст",
        "NOTEPAD_READY": "Готов к заказам",
        "NOTEPAD_TABLE": "Стол:",
        "DAY_COMPLETE": "⭐ ДЕНЬ ЗАВЕРШЕН! ⭐",
        "DAY_FAILED": "💀 ДЕНЬ ПРОВАЛЕН 💀",
        "DAY_FAILED_DESC": "Вы потеряли все жизни из-за злых клиентов!",
        "SAVINGS_LEFT": "💰 Остаток накоплений:",
        "DAYS_WORKED": "📅 Отработано дней:",
        "FURNITURE_BOUGHT": "🛋️ Куплено мебели:",
        "AUDIO_SETTINGS": "🔊 Звук игры",
        "ACTIVE": "ВКЛ",
        "DISABLED": "ВЫКЛ",
        "DIFFICULTY_LEVEL": "📊 Сложность",
        "EASY": "ЛЕГКО",
        "NORMAL": "НОРМАЛЬНО",
        "HARD": "СЛОЖНО",
        "CONTROL_SYSTEM": "🎮 Управление",
        "KEYBOARD": "КЛАВИАТУРА:",
        "LANGUAGE_SELECT": "🌐 Язык / Language",
        "CREDITS_TITLE": "ℹ РАЗРАБОТЧИКИ",
        "CREDITS_IDEATION": "🎮 ИДЕЯ И КОД",
        "CREDITS_SUPPORT": "🏠 ПРИ ПОДДЕРЖКЕ",
        "CREDITS_GRAPHICS": "🎨 ГРАФИКА И АНИМАЦИЯ",
        "CREDITS_TECH": "🛠️ ТЕХНОЛОГИИ",
        "CREDITS_LICENSE": "📝 ЛИЦЕНЗИЯ",
        "ERR_CLOSE_TABLE": "🚫 Подойдите к столу!",
        "ERR_ALREADY_ORDER": "❌ У вас уже есть заказ!",
        "ERR_SINK_FULL": "🚨 Раковина полна! Помойте посуду!",
        "ERR_CLOSE_COUNTER": "🚫 Подойдите к стойке!",
        "ERR_NO_FOOD_SERVED": "❌ Мы это не подаем!",
        "ERR_TRAY_FULL": "❌ Поднос полон!",
        "ERR_NO_READY_FOOD": "📦 Нет готовой еды!",
        "ERR_CLOSE_SINK": "🚫 Подойдите к раковине!",
        "MSG_ORDER_TAKEN": "📝 Заказ записан!",
        "MSG_ORDER_REC": "📝 Заказ принят!",
        "MSG_SERVED": "🍽️ Подано!",
        "MSG_TABLE_CLEARED": "🧹 Стол убран!",
        "MSG_TABLE_FREE": "🪑 Стол свободен",
        "FOOD_READY": "готово!",
        "FOOD_TAKEN": "забрано!",
        "TRICK_CLICKS": "🔑 Трюк:",
        "CLICKS_LEFT": "кликов...",
        "WASHING": "🧼 Моем...",
        "WASH_CLEAN": "✨ Посуда чистая!",
        "WASH_NONE": "🧼 Нет посуды",
        "LEAVING_ANGRY": "😡 Уходит!",
        "TABLE_SHORT": "Стол"
    },
    "ja": {
        "GIOCA": "▶ プレイ",
        "IMPOSTAZIONI": "⚙ 設定",
        "CREDITI": "ℹ クレジット",
        "TORNA": "↩ メニューへ戻る",
        "VAI A CASA": "🏠 帰宅する",
        "GIORNO": "⭐ 日目",
        "INCASSO": "💰 売上:",
        "SERVITI": "👥 接客数:",
        "VASSOIO": "📋 トレイ:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 シンク",
        "PRONTO": "完成！ 👨‍🍳",
        "OCCUPATO": "使用中！",
        "LOADING": "読み込み中...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "ウェイトレス＆ライフシミュレーター",
        "NOTEPAD_TITLE": "📝 注文メモ",
        "NOTEPAD_EMPTY": "メモは空です",
        "NOTEPAD_READY": "注文準備完了",
        "NOTEPAD_TABLE": "テーブル:",
        "DAY_COMPLETE": "⭐ 1日クリア！ ⭐",
        "DAY_FAILED": "💀 営業失敗 💀",
        "DAY_FAILED_DESC": "怒ったお客様のせいでライフが無くなりました！",
        "SAVINGS_LEFT": "💰 貯金残高:",
        "DAYS_WORKED": "📅 労働日数:",
        "FURNITURE_BOUGHT": "🛋️ 購入した家具:",
        "AUDIO_SETTINGS": "🔊 ゲーム音量",
        "ACTIVE": "有効",
        "DISABLED": "無効",
        "DIFFICULTY_LEVEL": "📊 難易度",
        "EASY": "かんたん",
        "NORMAL": "ふつう",
        "HARD": "むずかしい",
        "CONTROL_SYSTEM": "🎮 操作方法",
        "KEYBOARD": "キーボード:",
        "LANGUAGE_SELECT": "🌐 言語 / Language",
        "CREDITS_TITLE": "ℹ 開発クレジット",
        "CREDITS_IDEATION": "🎮 企画・開発",
        "CREDITS_SUPPORT": "🏠 協力",
        "CREDITS_GRAPHICS": "🎨 グラフィック・アニメ",
        "CREDITS_TECH": "🛠️ 使用技術",
        "CREDITS_LICENSE": "📝 ライセンス",
        "ERR_CLOSE_TABLE": "🚫 テーブルに近づいてください！",
        "ERR_ALREADY_ORDER": "❌ 既に注文を受けています！",
        "ERR_SINK_FULL": "🚨 シンクがいっぱいです！皿を洗ってください！",
        "ERR_CLOSE_COUNTER": "🚫 カウンターに近づいてください！",
        "ERR_NO_FOOD_SERVED": "❌ その料理は提供していません！",
        "ERR_TRAY_FULL": "❌ トレイがいっぱいです！",
        "ERR_NO_READY_FOOD": "📦 出来上がり料理がありません！",
        "ERR_CLOSE_SINK": "🚫 シンクに近づいてください！",
        "MSG_ORDER_TAKEN": "📝 注文を受けました！",
        "MSG_ORDER_REC": "📝 注文完了！",
        "MSG_SERVED": "🍽️ 配膳完了！",
        "MSG_TABLE_CLEARED": "🧹 片付け完了！",
        "MSG_TABLE_FREE": "🪑 空席",
        "FOOD_READY": "完成！",
        "FOOD_TAKEN": "受け取り！",
        "TRICK_CLICKS": "🔑 裏技:",
        "CLICKS_LEFT": "クリック...",
        "WASHING": "🧼 洗浄中...",
        "WASH_CLEAN": "✨ ピカピカ！",
        "WASH_NONE": "🧼 皿がありません",
        "LEAVING_ANGRY": "😡 帰ってしまった！",
        "TABLE_SHORT": "卓"
    },
    "pl": {
        "GIOCA": "▶ GRAJ",
        "IMPOSTAZIONI": "⚙ USTAWIENIA",
        "CREDITI": "ℹ TWÓRCY",
        "TORNA": "↩ POWRÓT DO MENU",
        "VAI A CASA": "🏠 IDŹ DO DOMU",
        "GIORNO": "⭐ Dzień",
        "INCASSO": "💰 Zarobek:",
        "SERVITI": "👥 Obsłużeni:",
        "VASSOIO": "📋 Taca:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 ZLEW",
        "PRONTO": "Gotowe! 👨‍🍳",
        "OCCUPATO": "Stowisko zajęte!",
        "LOADING": "Ładowanie...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SYMULATOR KELNERKI I ŻYCIA W DOMU",
        "NOTEPAD_TITLE": "📝 ZAMÓWIENIE",
        "NOTEPAD_EMPTY": "Notatnik Pusty",
        "NOTEPAD_READY": "Gotowy na zamówienia",
        "NOTEPAD_TABLE": "Stolik:",
        "DAY_COMPLETE": "⭐ DZIEŃ ZAKOŃCZONY! ⭐",
        "DAY_FAILED": "💀 DZIEŃ NIEUDANY 💀",
        "DAY_FAILED_DESC": "Straciłeś wszystkie życia przez złość klientów!",
        "SAVINGS_LEFT": "💰 Pozostałe oszczędności:",
        "DAYS_WORKED": "📅 Przepracowane dni:",
        "FURNITURE_BOUGHT": "🛋️ Kupione meble:",
        "AUDIO_SETTINGS": "🔊 Dźwięk w grze",
        "ACTIVE": "WŁĄCZONE",
        "DISABLED": "WYŁĄCZONE",
        "DIFFICULTY_LEVEL": "📊 Poziom Trudności",
        "EASY": "ŁATWY",
        "NORMAL": "NORMALNY",
        "HARD": "TRUDNY",
        "CONTROL_SYSTEM": "🎮 Sterowanie",
        "KEYBOARD": "KLAWIATURA:",
        "LANGUAGE_SELECT": "🌐 Język / Language",
        "CREDITS_TITLE": "ℹ AUTORZY",
        "CREDITS_IDEATION": "🎮 POMYSŁ I KOD",
        "CREDITS_SUPPORT": "🏠 WSPARCIE",
        "CREDITS_GRAPHICS": "🎨 GRAFIKA I ANIMACJE",
        "CREDITS_TECH": "🛠️ TECHNOLOGIE",
        "CREDITS_LICENSE": "📝 LICENCJA",
        "ERR_CLOSE_TABLE": "🚫 Podejdź do stolika!",
        "ERR_ALREADY_ORDER": "❌ Masz już zamówienie!",
        "ERR_SINK_FULL": "🚨 Zlew przepełniony! Umyj naczynia!",
        "ERR_CLOSE_COUNTER": "🚫 Podejdź do lady!",
        "ERR_NO_FOOD_SERVED": "❌ Nie serwujemy tego!",
        "ERR_TRAY_FULL": "❌ Taca pełna!",
        "ERR_NO_READY_FOOD": "📦 Brak gotowych dań!",
        "ERR_CLOSE_SINK": "🚫 Podejdź do zlewu!",
        "MSG_ORDER_TAKEN": "📝 Zamówienie Przyjęte!",
        "MSG_ORDER_REC": "📝 Zrealizowano zamówienie!",
        "MSG_SERVED": "🍽️ Podano!",
        "MSG_TABLE_CLEARED": "🧹 Stolik Posprzątany!",
        "MSG_TABLE_FREE": "🪑 Stolik wolny",
        "FOOD_READY": "gotowe!",
        "FOOD_TAKEN": "pobrane!",
        "TRICK_CLICKS": "🔑 Kod:",
        "CLICKS_LEFT": "kliknięć...",
        "WASHING": "🧼 Mycie...",
        "WASH_CLEAN": "✨ Czyste naczynia!",
        "WASH_NONE": "🧼 Brak naczyń",
        "LEAVING_ANGRY": "😡 Wychodzi!",
        "TABLE_SHORT": "Stół"
    },
    "hu": {
        "GIOCA": "▶ JÁTÉK",
        "IMPOSTAZIONI": "⚙ BEÁLLÍTÁSOK",
        "CREDITI": "ℹ ALKOTÓK",
        "TORNA": "↩ VISSZA A MENÜBE",
        "VAI A CASA": "🏠 HAZAMENETEL",
        "GIORNO": "⭐ Nap",
        "INCASSO": "💰 Bevétel:",
        "SERVITI": "👥 Kiszolgálva:",
        "VASSOIO": "📋 Tálca:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 MOSOGATÓ",
        "PRONTO": "Kész! 👨‍🍳",
        "OCCUPATO": "Foglalt hely!",
        "LOADING": "Betöltés...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "PINCÉRNŐ ÉS OTTHONI ÉLET SZIMULÁTOR",
        "NOTEPAD_TITLE": "📝 RENDELÉS",
        "NOTEPAD_EMPTY": "Üres jegyzetfüzet",
        "NOTEPAD_READY": "Készen áll a rendelésre",
        "NOTEPAD_TABLE": "Asztal:",
        "DAY_COMPLETE": "⭐ NAP TELJESÍTVE! ⭐",
        "DAY_FAILED": "💀 NAP SIKERTELEN 💀",
        "DAY_FAILED_DESC": "Minden életet elveszítettél a mérges vendégek miatt!",
        "SAVINGS_LEFT": "💰 Megmaradt megtakarítás:",
        "DAYS_WORKED": "📅 Ledolgozott napok:",
        "FURNITURE_BOUGHT": "🛋️ Vásárolt bútorok:",
        "AUDIO_SETTINGS": "🔊 Játék hangja",
        "ACTIVE": "BEKAPCSOLVA",
        "DISABLED": "KIKAPCSOLVA",
        "DIFFICULTY_LEVEL": "📊 Nehézség",
        "EASY": "KÖNNYŰ",
        "NORMAL": "NORMÁL",
        "HARD": "NEHÉZ",
        "CONTROL_SYSTEM": "🎮 Irányítás",
        "KEYBOARD": "BILLENTYŰZET:",
        "LANGUAGE_SELECT": "🌐 Nyelv / Language",
        "CREDITS_TITLE": "ℹ ALKOTÓK",
        "CREDITS_IDEATION": "🎮 ÖTLET ÉS KÓD",
        "CREDITS_SUPPORT": "🏠 TÁMOGATÓK",
        "CREDITS_GRAPHICS": "🎨 GRAFIKA ÉS ANIMÁCIÓ",
        "CREDITS_TECH": "🛠️ TECHNOLÓGIÁK",
        "CREDITS_LICENSE": "📝 LICENC",
        "ERR_CLOSE_TABLE": "🚫 Menj közelebb az asztalhoz!",
        "ERR_ALREADY_ORDER": "❌ Már van egy rendelésed!",
        "ERR_SINK_FULL": "🚨 Tele a mosogató! Mosogass el!",
        "ERR_CLOSE_COUNTER": "🚫 Menj közelebb a pulthoz!",
        "ERR_NO_FOOD_SERVED": "❌ Ezt nem szolgáljuk fel!",
        "ERR_TRAY_FULL": "❌ Tele a tálca!",
        "ERR_NO_READY_FOOD": "📦 Nincs kész étel!",
        "ERR_CLOSE_SINK": "🚫 Menj közelebb a mosogatóhoz!",
        "MSG_ORDER_TAKEN": "📝 Rendelés felvéve!",
        "MSG_ORDER_REC": "📝 Rendelés megérkezett!",
        "MSG_SERVED": "🍽️ Felszolgálva!",
        "MSG_TABLE_CLEARED": "🧹 Asztal letakarítva!",
        "MSG_TABLE_FREE": "🪑 Szabad asztal",
        "FOOD_READY": "kész!",
        "FOOD_TAKEN": "elvégre!",
        "TRICK_CLICKS": "🔑 Csalás:",
        "CLICKS_LEFT": "Kattintás...",
        "WASHING": "🧼 Mosogatás...",
        "WASH_CLEAN": "✨ Tiszta edények!",
        "WASH_NONE": "🧼 Nincs edény",
        "LEAVING_ANGRY": "😡 Elmegy!",
        "TABLE_SHORT": "Aszt."
    },
    "pt": {
        "GIOCA": "▶ JOGAR",
        "IMPOSTAZIONI": "⚙ CONFIGURAÇÕES",
        "CREDITI": "ℹ CRÉDITOS",
        "TORNA": "↩ VOLTAR AO MENU",
        "VAI A CASA": "🏠 IR PARA CASA",
        "GIORNO": "⭐ Dia",
        "INCASSO": "💰 Lucro:",
        "SERVITI": "👥 Atendidos:",
        "VASSOIO": "📋 Bandeja:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 PIA",
        "PRONTO": "Pronto! 👨‍🍳",
        "OCCUPATO": "Posto ocupado!",
        "LOADING": "Carregando...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULADOR DE GARÇONETE E VIDA EM CASA",
        "NOTEPAD_TITLE": "📝 PEDIDO",
        "NOTEPAD_EMPTY": "Bloco Vazio",
        "NOTEPAD_READY": "Pronto para pedidos",
        "NOTEPAD_TABLE": "Mesa:",
        "DAY_COMPLETE": "⭐ DIA CONCLUÍDO! ⭐",
        "DAY_FAILED": "💀 DIA FRACASSADO 💀",
        "DAY_FAILED_DESC": "Você perdeu todas as vidas devido a clientes zangados!",
        "SAVINGS_LEFT": "💰 Economias restantes:",
        "DAYS_WORKED": "📅 Dias trabalhados:",
        "FURNITURE_BOUGHT": "🛋️ Móveis comprados:",
        "AUDIO_SETTINGS": "🔊 Áudio do jogo",
        "ACTIVE": "ATIVADO",
        "DISABLED": "DESATIVADO",
        "DIFFICULTY_LEVEL": "📊 Dificuldade",
        "EASY": "FÁCIL",
        "NORMAL": "NORMAL",
        "HARD": "DIFÍCIL",
        "CONTROL_SYSTEM": "🎮 Controles",
        "KEYBOARD": "TECLADO:",
        "LANGUAGE_SELECT": "🌐 Idioma / Language",
        "CREDITS_TITLE": "ℹ CRÉDITOS",
        "CREDITS_IDEATION": "🎮 IDEIA E CÓDIGO ORIGINAL",
        "CREDITS_SUPPORT": "🏠 COM O APOIO DE",
        "CREDITS_GRAPHICS": "🎨 GRÁFICOS E ANIMAÇÕES",
        "CREDITS_TECH": "🛠️ TECNOLOGIAS INTEGRADAS",
        "CREDITS_LICENSE": "📝 LICENÇA",
        "ERR_CLOSE_TABLE": "🚫 Aproxime-se da mesa!",
        "ERR_ALREADY_ORDER": "❌ Você já tem um pedido!",
        "ERR_SINK_FULL": "🚨 Pia cheia! Lave a louça!",
        "ERR_CLOSE_COUNTER": "🚫 Aproxime-se do balcão!",
        "ERR_NO_FOOD_SERVED": "❌ Não servimos essa comida!",
        "ERR_TRAY_FULL": "❌ Bandeja cheia!",
        "ERR_NO_READY_FOOD": "📦 Nenhuma comida pronta!",
        "ERR_CLOSE_SINK": "🚫 Aproxime-se da pia!",
        "MSG_ORDER_TAKEN": "📝 Pedido Anotado!",
        "MSG_ORDER_REC": "📝 Pedido recebido!",
        "MSG_SERVED": "🍽️ Servido!",
        "MSG_TABLE_CLEARED": "🧹 Mesa Limpa!",
        "MSG_TABLE_FREE": "🪑 Mesa livre",
        "FOOD_READY": "pronto!",
        "FOOD_TAKEN": "retirado!",
        "TRICK_CLICKS": "🔑 Truque:",
        "CLICKS_LEFT": "cliques...",
        "WASHING": "🧼 Lavando...",
        "WASH_CLEAN": "✨ Louça limpa!",
        "WASH_NONE": "🧼 Sem louça",
        "LEAVING_ANGRY": "😡 Vai embora!",
        "TABLE_SHORT": "Mesa"
    },
    "hi": {
        "GIOCA": "▶ खेलें",
        "IMPOSTAZIONI": "⚙ सेटिंग्स",
        "CREDITI": "ℹ क्रेडिट्स",
        "TORNA": "↩ मेनू पर वापस जाएँ",
        "VAI A CASA": "🏠 घर जाएँ",
        "GIORNO": "⭐ दिन",
        "INCASSO": "💰 कमाई:",
        "SERVITI": "👥 सेवा की:",
        "VASSOIO": "📋 ट्रे:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 सिंक",
        "PRONTO": "तैयार! 👨‍🍳",
        "OCCUPATO": "जगह व्यस्त है!",
        "LOADING": "लोड हो रहा है...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "वेट्रेस और गृहस्थ जीवन सिम्युलेटर",
        "NOTEPAD_TITLE": "📝 ऑर्डर",
        "NOTEPAD_EMPTY": "नोटपैड खाली है",
        "NOTEPAD_READY": "ऑर्डर के लिए तैयार",
        "NOTEPAD_TABLE": "टेबल:",
        "DAY_COMPLETE": "⭐ दिन पूरा हुआ! ⭐",
        "DAY_FAILED": "💀 दिन असफल 💀",
        "DAY_FAILED_DESC": "गुस्साए ग्राहकों के कारण आपने सभी जानें गंवा दीं!",
        "SAVINGS_LEFT": "💰 बची हुई बचत:",
        "DAYS_WORKED": "📅 काम किए गए दिन:",
        "FURNITURE_BOUGHT": "🛋️ खरीदे गए फर्नीचर:",
        "AUDIO_SETTINGS": "🔊 गेम ऑडियो",
        "ACTIVE": "सक्रिय",
        "DISABLED": "निष्क्रिय",
        "DIFFICULTY_LEVEL": "📊 कठिनाई का स्तर",
        "EASY": "आसान",
        "NORMAL": "सामान्य",
        "HARD": "कठिन",
        "CONTROL_SYSTEM": "🎮 नियंत्रण प्रणाली",
        "KEYBOARD": "कीबोर्ड:",
        "LANGUAGE_SELECT": "🌐 भाषा / Language",
        "CREDITS_TITLE": "ℹ विकास श्रेय",
        "CREDITS_IDEATION": "🎮 विचार और मूल कोड",
        "CREDITS_SUPPORT": "🏠 के सहयोग से",
        "CREDITS_GRAPHICS": "🎨 ग्राफिक्स और एनिमेशन",
        "CREDITS_TECH": "🛠️ एकीकृत प्रौद्योगिकियां",
        "CREDITS_LICENSE": "📝 लाइसेंस",
        "ERR_CLOSE_TABLE": "🚫 टेबल के पास जाएँ!",
        "ERR_ALREADY_ORDER": "❌ आपके पास पहले से एक ऑर्डर है!",
        "ERR_SINK_FULL": "🚨 सिंक भरा हुआ है! बर्तन धोएं!",
        "ERR_CLOSE_COUNTER": "🚫 काउंटर के पास जाएँ!",
        "ERR_NO_FOOD_SERVED": "❌ हम यह भोजन परोसते नहीं हैं!",
        "ERR_TRAY_FULL": "❌ ट्रे पूरी भरी है!",
        "ERR_NO_READY_FOOD": "📦 कोई भोजन तैयार नहीं है!",
        "ERR_CLOSE_SINK": "🚫 सिंक के पास जाएँ!",
        "MSG_ORDER_TAKEN": "📝 ऑर्डर लिया गया!",
        "MSG_ORDER_REC": "📝 ऑर्डर प्राप्त हुआ!",
        "MSG_SERVED": "🍽️ परोसा गया!",
        "MSG_TABLE_CLEARED": "🧹 टेबल साफ हो गई!",
        "MSG_TABLE_FREE": "🪑 टेबल खाली है",
        "FOOD_READY": "तैयार!",
        "FOOD_TAKEN": "ले लिया!",
        "TRICK_CLICKS": "🔑 ट्रिक:",
        "CLICKS_LEFT": "क्लिक...",
        "WASHING": "🧼 धुलाई जारी...",
        "WASH_CLEAN": "✨ बर्तन साफ!",
        "WASH_NONE": "🧼 कोई बर्तन नहीं",
        "LEAVING_ANGRY": "😡 जा रहा है!",
        "TABLE_SHORT": "टेबल"
    },
    "ko": {
        "GIOCA": "▶ 게임 시작",
        "IMPOSTAZIONI": "⚙ 설정",
        "CREDITI": "ℹ 크레딧",
        "TORNA": "↩ 메뉴로 돌아가기",
        "VAI A CASA": "🏠 집으로 가기",
        "GIORNO": "⭐ 일차",
        "INCASSO": "💰 수입:",
        "SERVITI": "👥 손님 수:",
        "VASSOIO": "📋 쟁반:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 싱크대",
        "PRONTO": "완성! 👨‍🍳",
        "OCCUPATO": "사용 중!",
        "LOADING": "로딩 중...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "웨이트리스 & 일상 시뮬레이터",
        "NOTEPAD_TITLE": "📝 주문서",
        "NOTEPAD_EMPTY": "메모장이 비어있음",
        "NOTEPAD_READY": "주문 받기 준비 완료",
        "NOTEPAD_TABLE": "테이블:",
        "DAY_COMPLETE": "⭐ 하루 완료! ⭐",
        "DAY_FAILED": "💀 영업 실패 💀",
        "DAY_FAILED_DESC": "화난 손님들 때문에 모든 생명을 잃었습니다!",
        "SAVINGS_LEFT": "💰 남은 저축액:",
        "DAYS_WORKED": "📅 일한 날짜:",
        "FURNITURE_BOUGHT": "🛋️ 구매한 가구:",
        "AUDIO_SETTINGS": "🔊 게임 사운드",
        "ACTIVE": "켜짐",
        "DISABLED": "꺼짐",
        "DIFFICULTY_LEVEL": "📊 난이도",
        "EASY": "쉬움",
        "NORMAL": "보통",
        "HARD": "어려움",
        "CONTROL_SYSTEM": "🎮 조작 방식",
        "KEYBOARD": "키보드:",
        "LANGUAGE_SELECT": "🌐 언어 / Language",
        "CREDITS_TITLE": "ℹ 개발진 크레딧",
        "CREDITS_IDEATION": "🎮 기획 & 개발",
        "CREDITS_SUPPORT": "🏠 지원",
        "CREDITS_GRAPHICS": "🎨 그래픽 & 애니메이션",
        "CREDITS_TECH": "🛠️ 사용 기술",
        "CREDITS_LICENSE": "📝 라이선스",
        "ERR_CLOSE_TABLE": "🚫 테이블에 더 가까이 가세요!",
        "ERR_ALREADY_ORDER": "❌ 이미 받아둔 주문이 있습니다!",
        "ERR_SINK_FULL": "🚨 싱크대가 가득 찼습니다! 설거지를 하세요!",
        "ERR_CLOSE_COUNTER": "🚫 카운터에 더 가까이 가세요!",
        "ERR_NO_FOOD_SERVED": "❌ 이 음식은 서빙할 수 없습니다!",
        "ERR_TRAY_FULL": "❌ 쟁반이 가득 찼습니다!",
        "ERR_NO_READY_FOOD": "📦 준비된 음식이 없습니다!",
        "ERR_CLOSE_SINK": "🚫 싱크대에 더 가까이 가세요!",
        "MSG_ORDER_TAKEN": "📝 주문 접수!",
        "MSG_ORDER_REC": "📝 주문 완료!",
        "MSG_SERVED": "🍽️ 서빙 완료!",
        "MSG_TABLE_CLEARED": "🧹 테이블 정리 완료!",
        "MSG_TABLE_FREE": "🪑 빈 테이블",
        "FOOD_READY": "완성!",
        "FOOD_TAKEN": "픽업!",
        "TRICK_CLICKS": "🔑 치트:",
        "CLICKS_LEFT": "회 클릭...",
        "WASHING": "🧼 설거지 중...",
        "WASH_CLEAN": "✨ 접시가 깨끗해졌습니다!",
        "WASH_NONE": "🧼 설거지할 접시가 없습니다",
        "LEAVING_ANGRY": "😡 손님이 떠납니다!",
        "TABLE_SHORT": "테이블"
    },
    "zh": {
        "GIOCA": "▶ 开始游戏",
        "IMPOSTAZIONI": "⚙ 设置",
        "CREDITI": "ℹ 制作人员",
        "TORNA": "↩ 返回菜单",
        "VAI A CASA": "🏠 回家",
        "GIORNO": "⭐ 天",
        "INCASSO": "💰 收入:",
        "SERVITI": "👥 服务人数:",
        "VASSOIO": "📋 托盘:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 水槽",
        "PRONTO": "好了！ 👨‍🍳",
        "OCCUPATO": "位置已被占用！",
        "LOADING": "加载中...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "服务员与家庭生活模拟器",
        "NOTEPAD_TITLE": "📝 菜单",
        "NOTEPAD_EMPTY": "便签本为空",
        "NOTEPAD_READY": "准备点餐",
        "NOTEPAD_TABLE": "餐桌:",
        "DAY_COMPLETE": "⭐ 完成今日营业！ ⭐",
        "DAY_FAILED": "💀 营业失败 💀",
        "DAY_FAILED_DESC": "由于顾客生气，你失去了所有生命！",
        "SAVINGS_LEFT": "💰 剩余存款:",
        "DAYS_WORKED": "📅 工作天数:",
        "FURNITURE_BOUGHT": "🛋️ 已购家具:",
        "AUDIO_SETTINGS": "🔊 游戏音效",
        "ACTIVE": "开启",
        "DISABLED": "关闭",
        "DIFFICULTY_LEVEL": "📊 难度",
        "EASY": "简单",
        "NORMAL": "普通",
        "HARD": "困难",
        "CONTROL_SYSTEM": "🎮 控制方式",
        "KEYBOARD": "键盘:",
        "LANGUAGE_SELECT": "🌐 语言 / Language",
        "CREDITS_TITLE": "ℹ 开发者名单",
        "CREDITS_IDEATION": "🎮 策划与代码",
        "CREDITS_SUPPORT": "🏠 支持团队",
        "CREDITS_GRAPHICS": "🎨 美术与动画",
        "CREDITS_TECH": "🛠️ 技术支持",
        "CREDITS_LICENSE": "📝 许可证",
        "ERR_CLOSE_TABLE": "🚫 请靠近餐桌！",
        "ERR_ALREADY_ORDER": "❌ 你已经拿到了点菜单！",
        "ERR_SINK_FULL": "🚨 水槽满了！快去洗碗！",
        "ERR_CLOSE_COUNTER": "🚫 请靠近柜台！",
        "ERR_NO_FOOD_SERVED": "❌ 我们不上这道菜！",
        "ERR_TRAY_FULL": "❌ 托盘装满了！",
        "ERR_NO_READY_FOOD": "📦 没有准备好的食物！",
        "ERR_CLOSE_SINK": "🚫 请靠近水槽！",
        "MSG_ORDER_TAKEN": "📝 已记下点单！",
        "MSG_ORDER_REC": "📝 收到订单！",
        "MSG_SERVED": "🍽️ 上菜成功！",
        "MSG_TABLE_CLEARED": "🧹 餐桌已打扫！",
        "MSG_TABLE_FREE": "🪑 空桌",
        "FOOD_READY": "好了！",
        "FOOD_TAKEN": "已取走！",
        "TRICK_CLICKS": "🔑 秘籍:",
        "CLICKS_LEFT": "次点击...",
        "WASHING": "🧼 洗碗中...",
        "WASH_CLEAN": "✨ 碗碟已洗净！",
        "WASH_NONE": "🧼 没有脏碗",
        "LEAVING_ANGRY": "😡 顾客生性离开了！",
        "TABLE_SHORT": "桌"
    },
    "haw": {
        "GIOCA": "▶ PĀʻANI",
        "IMPOSTAZIONI": "⚙ HŌʻIKE",
        "CREDITI": "ℹ GOʻI",
        "TORNA": "↩ HOʻOPIʻI I KA PAPA KOE",
        "VAI A CASA": "🏠 HOʻI I KA HALE",
        "GIORNO": "⭐ Lā",
        "INCASSO": "💰 Kālā:",
        "SERVITI": "👥 Mākaukau:",
        "VASSOIO": "📋 Pā pālahalaha:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 KINI",
        "PRONTO": "Mākaukau! 👨‍🍳",
        "OCCUPATO": "Ua paʻa ka wahi!",
        "LOADING": "Hoʻouka nei...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATOR O KA WAHINE HĀNAI ME KA HALE",
        "NOTEPAD_TITLE": "📝 PALAPALA KAUOHA",
        "NOTEPAD_EMPTY": "Puke hāmama",
        "NOTEPAD_READY": "Mākaukau no nā kauoha",
        "NOTEPAD_TABLE": "Pākaukau:",
        "DAY_COMPLETE": "⭐ LĀ UA PAʻA! ⭐",
        "DAY_FAILED": "💀 HOʻOPAI LĀ 💀",
        "DAY_FAILED_DESC": "Ua pau nā ola i nā keiki huhū!",
        "SAVINGS_LEFT": "💰 Kālā i toe:",
        "DAYS_WORKED": "📅 Nā lā hana:",
        "FURNITURE_BOUGHT": "🛋️ Nā pūnana hou:",
        "AUDIO_SETTINGS": "🔊 Leo pāʻani",
        "ACTIVE": "HANA",
        "DISABLED": "AʻOLE HANA",
        "DIFFICULTY_LEVEL": "📊 Pae Hiki",
        "EASY": "WALE",
        "NORMAL": "MAʻAMAU",
        "HARD": "NUI",
        "CONTROL_SYSTEM": "🎮 Nā Mana",
        "KEYBOARD": "PĀPAʻI PĀKAUKAU:",
        "LANGUAGE_SELECT": "🌐 ʻŌlelo / Language",
        "CREDITS_TITLE": "ℹ NĀ KANAKA HAKU",
        "CREDITS_IDEATION": "🎮 MANAʻO A ME KA HAKU",
        "CREDITS_SUPPORT": "🏠 KŌKUA",
        "CREDITS_GRAPHICS": "🎨 KII A ME ANIMA",
        "CREDITS_TECH": "🛠️ ʻENEKINI",
        "CREDITS_LICENSE": "📝 PALAAPALA",
        "ERR_CLOSE_TABLE": "🚫 E hoʻokokoke i ka pākaukau!",
        "ERR_ALREADY_ORDER": "❌ He kauoha kāu!",
        "ERR_SINK_FULL": "🚨 Ua piha ka kini! Umi i nā pā!",
        "ERR_CLOSE_COUNTER": "🚫 E hoʻokokoke i ka papa!",
        "ERR_NO_FOOD_SERVED": "❌ ʻAʻole mākou e hāʻawi i kēia!",
        "ERR_TRAY_FULL": "❌ Ua piha ka pā!",
        "ERR_NO_READY_FOOD": "📦 ʻAʻole meʻai mākaukau!",
        "ERR_CLOSE_SINK": "🚫 E hoʻokokoke i ka kini!",
        "MSG_ORDER_TAKEN": "📝 Ua skū i ka kauoha!",
        "MSG_ORDER_REC": "📝 Ua loaʻa ka kauoha!",
        "MSG_SERVED": "🍽️ Ua hāʻawi ʻia!",
        "MSG_TABLE_CLEARED": "🧹 Ua hāʻalele i ka pākaukau!",
        "MSG_TABLE_FREE": "🪑 Pākaukau hāmama",
        "FOOD_READY": "mākaukau!",
        "FOOD_TAKEN": "ua lawe ʻia!",
        "TRICK_CLICKS": "🔑 Kī secret:",
        "CLICKS_LEFT": "kaomi...",
        "WASHING": "🧼 Umi nei...",
        "WASH_CLEAN": "✨ Maʻemaʻe nā pā!",
        "WASH_NONE": "🧼 ʻAʻole pā",
        "LEAVING_ANGRY": "😡 Ua hele huhū!",
        "TABLE_SHORT": "Pā."
    }
};

function t(key) {
    const lang = window.CURRENT_LANG || CURRENT_LANG || localStorage.getItem('waitress_game_lang') || 'it';
    if (AUTO_TRANSLATIONS[lang] && AUTO_TRANSLATIONS[lang][key]) {
        return AUTO_TRANSLATIONS[lang][key];
    }
    if (AUTO_TRANSLATIONS['it'] && AUTO_TRANSLATIONS['it'][key]) {
        return AUTO_TRANSLATIONS['it'][key];
    }
    return key;
}

function setLanguage(langCode) {
    if (!LANGUAGES[langCode]) return;
    CURRENT_LANG = langCode;
    window.CURRENT_LANG = langCode;
    localStorage.setItem('waitress_game_lang', langCode);
    
    if (window.game && window.game.scene) {
        window.game.scene.getScenes(true).forEach(scene => {
            if (scene && scene.scene) {
                scene.scene.restart();
            }
        });
    }
}

// ESPORTAZIONE GLOBALE
window.LANGUAGES = LANGUAGES;
window.CURRENT_LANG = CURRENT_LANG;
window.AUTO_TRANSLATIONS = AUTO_TRANSLATIONS;
window.t = t;
window.setLanguage = setLanguage;