const LOCAL_LANGUAGES = {
    'it': { name: 'Italiano', flag: '🇮🇹' },
    'es': { name: 'Español', flag: '🇪🇸' },
    'fr': { name: 'Français', flag: '🇫🇷' },
    'de': { name: 'Deutsch', flag: '🇩🇪' },
    'tr': { name: 'Türkçe', flag: '🇹🇷' },
    'ru': { name: 'Русский', flag: '🇷🇺' },
    'ja': { name: '日本語', flag: '🇯🇵' },
    'pl': { name: 'Polski', flag: '🇵🇱' },
    'hu': { name: 'Magyar', flag: '🇭🇺' },
    'pt': { name: 'Português', flag: '🇵🇹' },
    'pt-BR': { name: 'Português (Brasil)', flag: '🇧🇷' },
    'hi': { name: 'हिन्दी', flag: '🇮🇳' },
    'ko': { name: '한국어', flag: '🇰🇷' },
    'zh': { name: '中文', flag: '🇨🇳' },
    'ar': { name: 'العربية', flag: '🇸🇦' },
    'haw': { name: 'Ōlelo Hawaiʻi', flag: '🌺' },
    'me': { name: 'Crnogorski', flag: '🇲🇪' },
    'ku': { name: 'Kurdî (Kurmancî)', flag: '🌞' }
};

const LOCAL_AUTO_TRANSLATIONS = {
    "it": {
        // MENU
        "GIOCA": "▶ GIOCA",
        "IMPOSTAZIONI": "⚙ IMPOSTAZIONI",
        "CREDITI": "ℹ CREDITI",
        "TORNA": "↩ TORNA AL MENU",
        "VAI A CASA": "🏠 VAI A CASA",
        "GIORNO": "⭐ Giorno",
        "INCASSO": "💰 Incasso:",
        "SERVITI": "👥 Serviti:",
        "VASSOIO": "📋 Vassoio:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 LAVELLO",
        "PRONTO": "Pronto! 👨‍🍳",
        "OCCUPATO": "Postazione occupata!",
        "LOADING": "Caricamento...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATORE DI CAMERIERA & VITA DA CASALINGA",
        "NOTEPAD_TITLE": "📝 COMANDA",
        "NOTEPAD_EMPTY": "Taccuino Vuoto",
        "NOTEPAD_READY": "Pronto per ordini",
        "NOTEPAD_TABLE": "Tavolo:",
        "DAY_COMPLETE": "⭐ GIORNATA COMPLETATA! ⭐",
        "DAY_FAILED": "💀 GIORNATA FALLITA 💀",
        "DAY_FAILED_DESC": "Hai perso tutte le vite a causa dei clienti arrabbiati!",
        "SAVINGS_LEFT": "💰 Risparmi rimasti:",
        "DAYS_WORKED": "📅 Giorni lavorati:",
        "FURNITURE_BOUGHT": "🛋️ Mobili acquistati:",
        "AUDIO_SETTINGS": "🔊 Audio di gioco",
        "ACTIVE": "ATTIVO",
        "DISABLED": "DISATTIVATO",
        "DIFFICULTY_LEVEL": "📊 Livello di Difficoltà",
        "EASY": "FACILE",
        "NORMAL": "NORMALE",
        "HARD": "DIFFICILE",
        "CONTROL_SYSTEM": "🎮 Sistema di Controlli",
        "KEYBOARD": "TASTIERA:",
        "LANGUAGE_SELECT": "🌐 Lingua / Language",
        "CREDITS_TITLE": "ℹ CREDITI DI SVILUPPO",
        "CREDITS_IDEATION": "🎮 IDEAZIONE & CODICE ORIGINALE",
        "CREDITS_SUPPORT": "🏠 CON IL SUPPORTO DI",
        "CREDITS_GRAPHICS": "🎨 GRAFICA & ANIMAZIONI",
        "CREDITS_TECH": "🛠️ TECNOLOGIE INTEGRATE",
        "CREDITS_LICENSE": "📝 LICENZA",
        "INTELLIGENZA ARTIFICIALE": "🧠 INTELLIGENZA ARTIFICIALE",
        
        // ERRORI
        "ERR_CLOSE_TABLE": "🚫 Avvicinati al tavolo!",
        "ERR_ALREADY_ORDER": "❌ Hai già una comanda!",
        "ERR_SINK_FULL": "🚨 Lavello sovraccarico! Lava i piatti!",
        "ERR_CLOSE_COUNTER": "🚫 Avvicinati al bancone!",
        "ERR_NO_FOOD_SERVED": "❌ Non serviamo questo cibo!",
        "ERR_TRAY_FULL": "❌ Vassoio stracolmo!",
        "ERR_NO_READY_FOOD": "📦 Nessun cibo pronto!",
        "ERR_CLOSE_SINK": "🚫 Avvicinati al lavello!",
        "TRAY_FULL": "Vassoio pieno!",
        "SINK_FULL": "Lavello pieno!",
        "NO_FOOD_READY": "Nessun cibo pronto",
        "COUNTER_OCCUPIED": "Postazione occupata!",
        "MOVE_CLOSER_WASD": "Avvicinati con WASD!",
        "MOVE_CLOSER_ARROWS": "Avvicinati con le Frecce!",
        
        // MESSAGGI DI GIOCO
        "MSG_ORDER_TAKEN": "📝 Comanda Scritta!",
        "MSG_ORDER_REC": "📝 Ordine preso!",
        "MSG_SERVED": "🍽️ Servito!",
        "MSG_TABLE_CLEARED": "🧹 Tavolo Sbarazzato!",
        "MSG_TABLE_FREE": "🪑 Tavolo libero",
        "FOOD_READY": "pronto!",
        "FOOD_TAKEN": "prelevato!",
        "TRICK_CLICKS": "🔑 Trucco:",
        "CLICKS_LEFT": "clic...",
        "WASHING": "🧼 Lavando...",
        "WASH_CLEAN": "✨ Piatti puliti!",
        "WASH_NONE": "🧼 Nessun piatto",
        "LEAVING_ANGRY": "😡 Se ne va!",
        "TABLE_SHORT": "Tav.",
        "PLATE_DEPOSITED": "🧹 Piatto depositato!",
        "DAY_STARTED": "🎉 GIORNO {level} INIZIATO!",
        "TABLE_OCCUPIED": "Tavolo occupato",
        "ORDER_TAKEN": "Ordine preso!",
        "WASHING_PLATE": "🧹 Piatto depositato!",
        
        // TUTORIAL
        "TUTORIAL_TITLE": "🎯 TUTORIAL - GIORNO 0",
        "TUTORIAL_STEP_1": "👋 Benvenuta, Cameriera!\nUsa WASD per muoverti.\nVai al tavolo del cliente per prendere l'ordine.",
        "TUTORIAL_STEP_2": "📝 Ottimo! Hai preso l'ordine.\nOra vai al bancone in cucina\nper consegnarlo allo Chef.",
        "TUTORIAL_STEP_3": "👨‍🍳 Lo Chef ha cucinato!\nTorna al bancone per prendere il cibo\ne servirlo al cliente.",
        "TUTORIAL_STEP_4": "🍽️ Cliente servito!\nOra riprendi il piatto sporco\ne portalo al lavello.",
        "TUTORIAL_STEP_5": "🧼 Ben fatto!\nLava i piatti cliccando sul lavello.\nIl tutorial è finito!",
        "TUTORIAL_STEP_6": "🎉 Tutorial completato!\nInizia il Giorno 1 con 3 vite.",
        "TUTORIAL_TABLE": "🪑 Tavolo del Cliente",
        "TUTORIAL_COUNTER": "🧑‍🍳 Bancone della Cucina",
        "TUTORIAL_SINK": "🚿 Lavello",
        "TUTORIAL_MSG": "📖 Segui le istruzioni",
        "TUTORIAL_WAIT": "⏳ Aspetta che lo Chef cucini...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Segui le frecce del tutorial!",
        
        // SISTEMI
        "AI_CHAT_TITLE": "💬 Chat con {name}",
        "AI_CHAT_GREETING": "Ciao! Come posso aiutarti?",
        "AI_CHAT_CLOSE": "Chiudi chat",
        "AI_CHAT_SEND": "Invia",
        "AI_CHAT_PLACEHOLDER": "Scrivi un messaggio...",
        "AI_CHAT_LOADING": "🤔 Sto pensando...",
        "AI_CHAT_ERROR": "⚠️ Errore: riprova più tardi",
        "AI_CHAT_FALLBACK": "📝 Sono in modalità offline!",
        
        // RADIO
        "RADIO_TITLE": "📻 Radio",
        "RADIO_PLAY": "▶ Play",
        "RADIO_STOP": "⏹ Stop",
        "RADIO_NEXT": "⏭ Prossima",
        "RADIO_ON": "📻 Radio Accesa",
        "RADIO_OFF": "📻 Radio Spenta",
        "RADIO_STATION_1": "🎵 Canzone 1",
        "RADIO_STATION_2": "🎵 Canzone 2",
        "RADIO_STATION_3": "🎵 Canzone 3",
        
        // TELEFONO
        "PHONE_RINGING": "📞 Il telefono sta squillando!",
        "PHONE_ANSWER": "📞 Rispondi?",
        "PHONE_CALL": "📞 In chiamata...",
        "PHONE_MESSAGE": "📱 Nuovo messaggio!",
        "PHONE_DELIVERY": "📦 Consegna speciale arriva in 3 clienti!",
        
        // CIBI
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Patatine",
        "FOOD_PANINO": "🍔 Panino",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Caponata",
        "FOOD_CAFFE": "☕ Caffè",
        "FOOD_COLA": "🥤 Cola",
        "FOOD_ACQUA": "💧 Acqua",
        "FOOD_BIRRA": "🍺 Birra",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
        
    },
    "es": {
        "GIOCA": "▶ JUGAR",
        "IMPOSTAZIONI": "⚙ AJUSTES",
        "CREDITI": "ℹ CRÉDITOS",
        "TORNA": "↩ VOLVER AL MENÚ",
        "VAI A CASA": "🏠 IR A CASA",
        "GIORNO": "⭐ Día",
        "INCASSO": "💰 Ganancias:",
        "SERVITI": "👥 Atendidos:",
        "VASSOIO": "📋 Bandeja:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 FREGADERO",
        "PRONTO": "¡Listo! 👨‍🍳",
        "OCCUPATO": "¡Estación ocupada!",
        "LOADING": "Cargando...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULADOR DE CAMARERA Y VIDA EN CASA",
        "NOTEPAD_TITLE": "📝 PEDIDO",
        "NOTEPAD_EMPTY": "Bloc vacío",
        "NOTEPAD_READY": "Listo para pedidos",
        "NOTEPAD_TABLE": "Mesa:",
        "DAY_COMPLETE": "⭐ ¡DÍA COMPLETADO! ⭐",
        "DAY_FAILED": "💀 DÍA FALLIDO 💀",
        "DAY_FAILED_DESC": "¡Has perdido todas las vidas por clientes enfadados!",
        "SAVINGS_LEFT": "💰 Ahorros restantes:",
        "DAYS_WORKED": "📅 Días trabajados:",
        "FURNITURE_BOUGHT": "🛋️ Muebles comprados:",
        "AUDIO_SETTINGS": "🔊 Audio del juego",
        "ACTIVE": "ACTIVADO",
        "DISABLED": "DESACTIVADO",
        "DIFFICULTY_LEVEL": "📊 Dificultad",
        "EASY": "FÁCIL",
        "NORMAL": "NORMAL",
        "HARD": "DIFÍCIL",
        "CONTROL_SYSTEM": "🎮 Controles",
        "KEYBOARD": "TECLADO:",
        "LANGUAGE_SELECT": "🌐 Idioma / Language",
        "CREDITS_TITLE": "ℹ CRÉDITOS DE DESARROLLO",
        "CREDITS_IDEATION": "🎮 IDEACIÓN Y CÓDIGO ORIGINAL",
        "CREDITS_SUPPORT": "🏠 CON EL APOYO DE",
        "CREDITS_GRAPHICS": "🎨 GRÁFICOS Y ANIMACIONES",
        "CREDITS_TECH": "🛠️ TECNOLOGÍAS INTEGRADAS",
        "CREDITS_LICENSE": "📝 LICENCIA",
        "INTELLIGENZA ARTIFICIALE": "🧠 INTELIGENCIA ARTIFICIAL",
        
        "ERR_CLOSE_TABLE": "🚫 ¡Acércate a la mesa!",
        "ERR_ALREADY_ORDER": "❌ ¡Ya tienes una comanda!",
        "ERR_SINK_FULL": "🚨 ¡Fregadero lleno! ¡Lava los platos!",
        "ERR_CLOSE_COUNTER": "🚫 ¡Acércate a la barra!",
        "ERR_NO_FOOD_SERVED": "❌ ¡No servimos esta comida!",
        "ERR_TRAY_FULL": "❌ ¡Bandeja llena!",
        "ERR_NO_READY_FOOD": "📦 ¡No hay comida lista!",
        "ERR_CLOSE_SINK": "🚫 ¡Acércate al fregadero!",
        "TRAY_FULL": "¡Bandeja llena!",
        "SINK_FULL": "¡Fregadero lleno!",
        "NO_FOOD_READY": "No hay comida lista",
        "COUNTER_OCCUPIED": "¡Estación ocupada!",
        "MOVE_CLOSER_WASD": "¡Acércate con WASD!",
        "MOVE_CLOSER_ARROWS": "¡Acércate con las Flechas!",
        
        "MSG_ORDER_TAKEN": "📝 ¡Pedido Tomado!",
        "MSG_ORDER_REC": "📝 ¡Orden recibida!",
        "MSG_SERVED": "🍽️ ¡Servido!",
        "MSG_TABLE_CLEARED": "🧹 ¡Mesa Limpia!",
        "MSG_TABLE_FREE": "🪑 Mesa libre",
        "FOOD_READY": "¡listo!",
        "FOOD_TAKEN": "¡recogido!",
        "TRICK_CLICKS": "🔑 Truco:",
        "CLICKS_LEFT": "clics...",
        "WASHING": "🧼 Lavando...",
        "WASH_CLEAN": "✨ ¡Platos limpios!",
        "WASH_NONE": "🧼 No hay platos",
        "LEAVING_ANGRY": "😡 ¡Se va!",
        "TABLE_SHORT": "Mesa",
        "PLATE_DEPOSITED": "🧹 ¡Plato depositado!",
        "DAY_STARTED": "🎉 ¡DÍA {level} INICIADO!",
        "TABLE_OCCUPIED": "Mesa ocupada",
        "ORDER_TAKEN": "¡Pedido tomado!",
        "WASHING_PLATE": "🧹 ¡Plato depositado!",
        
        "TUTORIAL_TITLE": "🎯 TUTORIAL - DÍA 0",
        "TUTORIAL_STEP_1": "👋 ¡Bienvenida, Camarera!\nUsa WASD para moverte.\nVe a la mesa del cliente para tomar el pedido.",
        "TUTORIAL_STEP_2": "📝 ¡Bien! Has tomado el pedido.\nAhora ve al mostrador de la cocina\npara entregarlo al Chef.",
        "TUTORIAL_STEP_3": "👨‍🍳 ¡El Chef ha cocinado!\nVuelve al mostrador para recoger la comida\ny servirla al cliente.",
        "TUTORIAL_STEP_4": "🍽️ ¡Cliente servido!\nAhora recoge el plato sucio\nylévatelo al fregadero.",
        "TUTORIAL_STEP_5": "🧼 ¡Bien hecho!\nLava los platos haciendo clic en el fregadero.\n¡El tutorial ha terminado!",
        "TUTORIAL_STEP_6": "🎉 ¡Tutorial completado!\nComienza el Día 1 con 3 vidas.",
        "TUTORIAL_TABLE": "🪑 Mesa del Cliente",
        "TUTORIAL_COUNTER": "🧑‍🍳 Mostrador de Cocina",
        "TUTORIAL_SINK": "🚿 Fregadero",
        "TUTORIAL_MSG": "📖 Sigue las instrucciones",
        "TUTORIAL_WAIT": "⏳ Espera a que el Chef cocine...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ ¡Sigue las flechas del tutorial!",
        
        "AI_CHAT_TITLE": "💬 Chat con {name}",
        "AI_CHAT_GREETING": "¡Hola! ¿Cómo puedo ayudarte?",
        "AI_CHAT_CLOSE": "Cerrar chat",
        "AI_CHAT_SEND": "Enviar",
        "AI_CHAT_PLACEHOLDER": "Escribe un mensaje...",
        "AI_CHAT_LOADING": "🤔 Estoy pensando...",
        "AI_CHAT_ERROR": "⚠️ Error: intenta de nuevo más tarde",
        "AI_CHAT_FALLBACK": "📝 ¡Estoy en modo sin conexión!",
        
        "RADIO_TITLE": "📻 Radio",
        "RADIO_PLAY": "▶ Reproducir",
        "RADIO_STOP": "⏹ Detener",
        "RADIO_NEXT": "⏭ Siguiente",
        "RADIO_ON": "📻 Radio Encendida",
        "RADIO_OFF": "📻 Radio Apagada",
        "RADIO_STATION_1": "🎵 Canción 1",
        "RADIO_STATION_2": "🎵 Canción 2",
        "RADIO_STATION_3": "🎵 Canción 3",
        
        "PHONE_RINGING": "📞 ¡El teléfono está sonando!",
        "PHONE_ANSWER": "📞 ¿Responder?",
        "PHONE_CALL": "📞 En llamada...",
        "PHONE_MESSAGE": "📱 ¡Nuevo mensaje!",
        "PHONE_DELIVERY": "📦 ¡Entrega especial en 3 clientes!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Patatas Fritas",
        "FOOD_PANINO": "🍔 Hamburguesa",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Caponata",
        "FOOD_CAFFE": "☕ Café",
        "FOOD_COLA": "🥤 Cola",
        "FOOD_ACQUA": "💧 Agua",
        "FOOD_BIRRA": "🍺 Cerveza",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "fr": {
        "GIOCA": "▶ JOUER",
        "IMPOSTAZIONI": "⚙ PARAMÈTRES",
        "CREDITI": "ℹ CRÉDITS",
        "TORNA": "↩ RETOUR AU MENU",
        "VAI A CASA": "🏠 RENTRER",
        "GIORNO": "⭐ Jour",
        "INCASSO": "💰 Gains:",
        "SERVITI": "👥 Servis:",
        "VASSOIO": "📋 Plateau:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 ÉVIER",
        "PRONTO": "Prêt! 👨‍🍳",
        "OCCUPATO": "Poste occupé!",
        "LOADING": "Chargement...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATEUR DE SERVEUSE & VIE À LA MAISON",
        "NOTEPAD_TITLE": "📝 COMMANDE",
        "NOTEPAD_EMPTY": "Carnet Vide",
        "NOTEPAD_READY": "Prêt pour les commandes",
        "NOTEPAD_TABLE": "Table:",
        "DAY_COMPLETE": "⭐ JOURNÉE RÉUSSIE! ⭐",
        "DAY_FAILED": "💀 ÉCHEC DE LA JOURNÉE 💀",
        "DAY_FAILED_DESC": "Vous avez perdu toutes vos vies à cause de clients mécontents!",
        "SAVINGS_LEFT": "💰 Économies restantes:",
        "DAYS_WORKED": "📅 Jours travaillés:",
        "FURNITURE_BOUGHT": "🛋️ Meubles achetés:",
        "AUDIO_SETTINGS": "🔊 Audio du jeu",
        "ACTIVE": "ACTIVÉ",
        "DISABLED": "DÉSACTIVÉ",
        "DIFFICULTY_LEVEL": "📊 Niveau de Difficulté",
        "EASY": "FACILE",
        "NORMAL": "NORMAL",
        "HARD": "DIFFICILE",
        "CONTROL_SYSTEM": "🎮 Système de Contrôle",
        "KEYBOARD": "CLAVIER:",
        "LANGUAGE_SELECT": "🌐 Langue / Language",
        "CREDITS_TITLE": "ℹ CRÉDITS",
        "CREDITS_IDEATION": "🎮 IDÉE & CODE ORIGINAL",
        "CREDITS_SUPPORT": "🏠 AVEC LE SOUTIEN DE",
        "CREDITS_GRAPHICS": "🎨 GRAPHISMES & ANIMATIONS",
        "CREDITS_TECH": "🛠️ TECHNOLOGIES INTÉGRÉES",
        "CREDITS_LICENSE": "📝 LICENCE",
        "INTELLIGENZA ARTIFICIALE": "🧠 INTELLIGENCE ARTIFICIELLE",
        
        "ERR_CLOSE_TABLE": "🚫 Approchez-vous de la table!",
        "ERR_ALREADY_ORDER": "❌ Vous avez déjà une commande!",
        "ERR_SINK_FULL": "🚨 Évier débordé! Lavez les assiettes!",
        "ERR_CLOSE_COUNTER": "🚫 Approchez-vous du comptoir!",
        "ERR_NO_FOOD_SERVED": "❌ Nous ne servons pas ceci!",
        "ERR_TRAY_FULL": "❌ Plateau plein!",
        "ERR_NO_READY_FOOD": "📦 Pas de plat prêt!",
        "ERR_CLOSE_SINK": "🚫 Approchez-vous de l'évier!",
        "TRAY_FULL": "Plateau plein!",
        "SINK_FULL": "Évier plein!",
        "NO_FOOD_READY": "Pas de nourriture prête",
        "COUNTER_OCCUPIED": "Poste occupé!",
        "MOVE_CLOSER_WASD": "Approchez-vous avec WASD!",
        "MOVE_CLOSER_ARROWS": "Approchez-vous avec les Flèches!",
        
        "MSG_ORDER_TAKEN": "📝 Commande prise!",
        "MSG_ORDER_REC": "📝 Ordre reçu!",
        "MSG_SERVED": "🍽️ Servi!",
        "MSG_TABLE_CLEARED": "🧹 Table débarrassée!",
        "MSG_TABLE_FREE": "🪑 Table libre",
        "FOOD_READY": "prêt!",
        "FOOD_TAKEN": "récupéré!",
        "TRICK_CLICKS": "🔑 Astuce:",
        "CLICKS_LEFT": "clics...",
        "WASHING": "🧼 Lavage...",
        "WASH_CLEAN": "✨ Assiettes propres!",
        "WASH_NONE": "🧼 Pas d'assiette",
        "LEAVING_ANGRY": "😡 Il part!",
        "TABLE_SHORT": "Tab.",
        "PLATE_DEPOSITED": "🧹 Assiette déposée!",
        "DAY_STARTED": "🎉 JOUR {level} COMMENCÉ!",
        "TABLE_OCCUPIED": "Table occupée",
        "ORDER_TAKEN": "Commande prise!",
        "WASHING_PLATE": "🧹 Assiette déposée!",
        
        "TUTORIAL_TITLE": "🎯 TUTORIEL - JOUR 0",
        "TUTORIAL_STEP_1": "👋 Bienvenue, Serveuse!\nUtilise WASD pour te déplacer.\nVa à la table du client pour prendre la commande.",
        "TUTORIAL_STEP_2": "📝 Parfait! Tu as pris la commande.\nVa au comptoir de la cuisine\npour la donner au Chef.",
        "TUTORIAL_STEP_3": "👨‍🍳 Le Chef a cuisiné!\nRetourne au comptoir pour prendre la nourriture\net la servir au client.",
        "TUTORIAL_STEP_4": "🍽️ Client servi!\nMaintenant, prends l'assiette sale\net porte-la à l'évier.",
        "TUTORIAL_STEP_5": "🧼 Bien joué!\nLave les assiettes en cliquant sur l'évier.\nLe tutoriel est terminé!",
        "TUTORIAL_STEP_6": "🎉 Tutoriel terminé!\nCommence le Jour 1 avec 3 vies.",
        "TUTORIAL_TABLE": "🪑 Table du Client",
        "TUTORIAL_COUNTER": "🧑‍🍳 Comptoir de Cuisine",
        "TUTORIAL_SINK": "🚿 Évier",
        "TUTORIAL_MSG": "📖 Suis les instructions",
        "TUTORIAL_WAIT": "⏳ Attends que le Chef cuisine...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Suis les flèches du tutoriel!",
        
        "AI_CHAT_TITLE": "💬 Chat avec {name}",
        "AI_CHAT_GREETING": "Bonjour! Comment puis-je vous aider?",
        "AI_CHAT_CLOSE": "Fermer le chat",
        "AI_CHAT_SEND": "Envoyer",
        "AI_CHAT_PLACEHOLDER": "Écris un message...",
        "AI_CHAT_LOADING": "🤔 Je réfléchis...",
        "AI_CHAT_ERROR": "⚠️ Erreur: réessaye plus tard",
        "AI_CHAT_FALLBACK": "📝 Je suis en mode hors ligne!",
        
        "RADIO_TITLE": "📻 Radio",
        "RADIO_PLAY": "▶ Lecture",
        "RADIO_STOP": "⏹ Arrêter",
        "RADIO_NEXT": "⏭ Suivant",
        "RADIO_ON": "📻 Radio Allumée",
        "RADIO_OFF": "📻 Radio Éteinte",
        "RADIO_STATION_1": "🎵 Chanson 1",
        "RADIO_STATION_2": "🎵 Chanson 2",
        "RADIO_STATION_3": "🎵 Chanson 3",
        
        "PHONE_RINGING": "📞 Le téléphone sonne!",
        "PHONE_ANSWER": "📞 Répondre?",
        "PHONE_CALL": "📞 En appel...",
        "PHONE_MESSAGE": "📱 Nouveau message!",
        "PHONE_DELIVERY": "📦 Livraison spéciale dans 3 clients!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Frites",
        "FOOD_PANINO": "🍔 Burger",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Caponata",
        "FOOD_CAFFE": "☕ Café",
        "FOOD_COLA": "🥤 Cola",
        "FOOD_ACQUA": "💧 Eau",
        "FOOD_BIRRA": "🍺 Bière",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "de": {
        "GIOCA": "▶ SPIELEN",
        "IMPOSTAZIONI": "⚙ EINSTELLUNGEN",
        "CREDITI": "ℹ CREDITS",
        "TORNA": "↩ ZURÜCK ZUM MENÜ",
        "VAI A CASA": "🏠 NACH HAUSE",
        "GIORNO": "⭐ Tag",
        "INCASSO": "💰 Einnahmen:",
        "SERVITI": "👥 Bedient:",
        "VASSOIO": "📋 Tablett:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 SPÜLE",
        "PRONTO": "Fertig! 👨‍🍳",
        "OCCUPATO": "Station besetzt!",
        "LOADING": "Laden...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "KELLNERIN & HAUSHALT SIMULATOR",
        "NOTEPAD_TITLE": "📝 BESTELLUNG",
        "NOTEPAD_EMPTY": "Notizblock leer",
        "NOTEPAD_READY": "Bereit für Bestellungen",
        "NOTEPAD_TABLE": "Tisch:",
        "DAY_COMPLETE": "⭐ TAG ERFOLGREICH! ⭐",
        "DAY_FAILED": "💀 TAG FEHLGESCHLAGEN 💀",
        "DAY_FAILED_DESC": "Du hast alle Leben durch verärgerte Kunden verloren!",
        "SAVINGS_LEFT": "💰 Verbleibende Ersparnisse:",
        "DAYS_WORKED": "📅 Gearbeitete Tage:",
        "FURNITURE_BOUGHT": "🛋️ Gekaufte Möbel:",
        "AUDIO_SETTINGS": "🔊 Spiel-Audio",
        "ACTIVE": "AKTIV",
        "DISABLED": "DEAKTIVIERT",
        "DIFFICULTY_LEVEL": "📊 Schwierigkeitsgrad",
        "EASY": "EINFACH",
        "NORMAL": "NORMAL",
        "HARD": "SCHWER",
        "CONTROL_SYSTEM": "🎮 Steuerung",
        "KEYBOARD": "TASTATUR:",
        "LANGUAGE_SELECT": "🌐 Sprache / Language",
        "CREDITS_TITLE": "ℹ ENTWICKLER-CREDITS",
        "CREDITS_IDEATION": "🎮 IDEE & CODE",
        "CREDITS_SUPPORT": "🏠 UNTERSTÜTZT VON",
        "CREDITS_GRAPHICS": "🎨 GRAFIK & ANIMATIONEN",
        "CREDITS_TECH": "🛠️ INTEGRATIONEN",
        "CREDITS_LICENSE": "📝 LIZENZ",
        "INTELLIGENZA ARTIFICIALE": "🧠 KÜNSTLICHE INTELLIGENZ",
        
        "ERR_CLOSE_TABLE": "🚫 Geh näher zum Tisch!",
        "ERR_ALREADY_ORDER": "❌ Du hast bereits eine Bestellung!",
        "ERR_SINK_FULL": "🚨 Spüle voll! Wasche das Geschirr!",
        "ERR_CLOSE_COUNTER": "🚫 Geh näher zum Tresen!",
        "ERR_NO_FOOD_SERVED": "❌ Das servieren wir nicht!",
        "ERR_TRAY_FULL": "❌ Tablett voll!",
        "ERR_NO_READY_FOOD": "📦 Kein Essen bereit!",
        "ERR_CLOSE_SINK": "🚫 Geh näher zur Spüle!",
        "TRAY_FULL": "Tablett voll!",
        "SINK_FULL": "Spüle voll!",
        "NO_FOOD_READY": "Kein Essen bereit",
        "COUNTER_OCCUPIED": "Station besetzt!",
        "MOVE_CLOSER_WASD": "Geh näher mit WASD!",
        "MOVE_CLOSER_ARROWS": "Geh näher mit Pfeiltasten!",
        
        "MSG_ORDER_TAKEN": "📝 Bestellung aufgenommen!",
        "MSG_ORDER_REC": "📝 Bestellung erhalten!",
        "MSG_SERVED": "🍽️ Serviert!",
        "MSG_TABLE_CLEARED": "🧹 Tisch abgeräumt!",
        "MSG_TABLE_FREE": "🪑 Tisch frei",
        "FOOD_READY": "fertig!",
        "FOOD_TAKEN": "abgeholt!",
        "TRICK_CLICKS": "🔑 Trick:",
        "CLICKS_LEFT": "Klicks...",
        "WASHING": "🧼 Spülen...",
        "WASH_CLEAN": "✨ Geschirr sauber!",
        "WASH_NONE": "🧼 Kein Geschirr",
        "LEAVING_ANGRY": "😡 Geht verärgert!",
        "TABLE_SHORT": "Tisch",
        "PLATE_DEPOSITED": "🧹 Teller abgegeben!",
        "DAY_STARTED": "🎉 TAG {level} BEGONNEN!",
        "TABLE_OCCUPIED": "Tisch besetzt",
        "ORDER_TAKEN": "Bestellung aufgenommen!",
        "WASHING_PLATE": "🧹 Teller abgegeben!",
        
        "TUTORIAL_TITLE": "🎯 TUTORIAL - TAG 0",
        "TUTORIAL_STEP_1": "👋 Willkommen, Kellnerin!\nNutze WASD um dich zu bewegen.\nGeh zum Tisch des Kunden, um die Bestellung aufzunehmen.",
        "TUTORIAL_STEP_2": "📝 Gut gemacht! Du hast die Bestellung.\nGeh jetzt zur Theke in der Küche,\num sie dem Koch zu geben.",
        "TUTORIAL_STEP_3": "👨‍🍳 Der Koch hat gekocht!\nGeh zurück zur Theke, um das Essen zu holen\nund es dem Kunden zu servieren.",
        "TUTORIAL_STEP_4": "🍽️ Kunde bedient!\nJetzt nimm den schmutzigen Teller\nund bring ihn zur Spüle.",
        "TUTORIAL_STEP_5": "🧼 Gut gemacht!\nWasche die Teller, indem du auf die Spüle klickst.\nDas Tutorial ist beendet!",
        "TUTORIAL_STEP_6": "🎉 Tutorial abgeschlossen!\nStarte Tag 1 mit 3 Leben.",
        "TUTORIAL_TABLE": "🪑 Kundentisch",
        "TUTORIAL_COUNTER": "🧑‍🍳 Küchentheke",
        "TUTORIAL_SINK": "🚿 Spüle",
        "TUTORIAL_MSG": "📖 Folge den Anweisungen",
        "TUTORIAL_WAIT": "⏳ Warte, bis der Koch kocht...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Folge den Tutorial-Pfeilen!",
        
        "AI_CHAT_TITLE": "💬 Chat mit {name}",
        "AI_CHAT_GREETING": "Hallo! Wie kann ich helfen?",
        "AI_CHAT_CLOSE": "Chat schließen",
        "AI_CHAT_SEND": "Senden",
        "AI_CHAT_PLACEHOLDER": "Nachricht schreiben...",
        "AI_CHAT_LOADING": "🤔 Ich denke nach...",
        "AI_CHAT_ERROR": "⚠️ Fehler: versuche es später erneut",
        "AI_CHAT_FALLBACK": "📝 Ich bin im Offline-Modus!",
        
        "RADIO_TITLE": "📻 Radio",
        "RADIO_PLAY": "▶ Abspielen",
        "RADIO_STOP": "⏹ Stopp",
        "RADIO_NEXT": "⏭ Nächster",
        "RADIO_ON": "📻 Radio An",
        "RADIO_OFF": "📻 Radio Aus",
        "RADIO_STATION_1": "🎵 Lied 1",
        "RADIO_STATION_2": "🎵 Lied 2",
        "RADIO_STATION_3": "🎵 Lied 3",
        
        "PHONE_RINGING": "📞 Das Telefon klingelt!",
        "PHONE_ANSWER": "📞 Antworten?",
        "PHONE_CALL": "📞 Im Gespräch...",
        "PHONE_MESSAGE": "📱 Neue Nachricht!",
        "PHONE_DELIVERY": "📦 Sonderlieferung in 3 Kunden!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Pommes",
        "FOOD_PANINO": "🍔 Burger",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Caponata",
        "FOOD_CAFFE": "☕ Kaffee",
        "FOOD_COLA": "🥤 Cola",
        "FOOD_ACQUA": "💧 Wasser",
        "FOOD_BIRRA": "🍺 Bier",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "tr": {
        "GIOCA": "▶ OYNA",
        "IMPOSTAZIONI": "⚙ AYARLAR",
        "CREDITI": "ℹ EMEĞİ GEÇENLER",
        "TORNA": "↩ MENÜYE DÖN",
        "VAI A CASA": "🏠 EVE GİT",
        "GIORNO": "⭐ Gün",
        "INCASSO": "💰 Kazanç:",
        "SERVITI": "👥 Hizmet Edilen:",
        "VASSOIO": "📋 Tepsi:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 EVIYE",
        "PRONTO": "Hazır! 👨‍🍳",
        "OCCUPATO": "İstasyon dolu!",
        "LOADING": "Yükleniyor...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "GARSON & EV YAŞAMI SİMÜLATÖRÜ",
        "NOTEPAD_TITLE": "📝 SİPARİŞ",
        "NOTEPAD_EMPTY": "Not Defteri Boş",
        "NOTEPAD_READY": "Siparişler için hazır",
        "NOTEPAD_TABLE": "Masa:",
        "DAY_COMPLETE": "⭐ GÜN TAMAMLANDI! ⭐",
        "DAY_FAILED": "💀 GÜN BAŞARISIZ 💀",
        "DAY_FAILED_DESC": "Kızgın müşteriler yüzünden tüm canlarını kaybettin!",
        "SAVINGS_LEFT": "💰 Kalan Birikim:",
        "DAYS_WORKED": "📅 Çalışılan Gün:",
        "FURNITURE_BOUGHT": "🛋️ Alınan Mobilya:",
        "AUDIO_SETTINGS": "🔊 Oyun Sesi",
        "ACTIVE": "AÇIK",
        "DISABLED": "KAPALI",
        "DIFFICULTY_LEVEL": "📊 Zorluk Seviyesi",
        "EASY": "KOLAY",
        "NORMAL": "NORMAL",
        "HARD": "ZOR",
        "CONTROL_SYSTEM": "🎮 Kontrol Sistemi",
        "KEYBOARD": "KLAVYE:",
        "LANGUAGE_SELECT": "🌐 Dil / Language",
        "CREDITS_TITLE": "ℹ EMEĞİ GEÇENLER",
        "CREDITS_IDEATION": "🎮 FİKİR & KODLAMA",
        "CREDITS_SUPPORT": "🏠 DESTEKLEYENLER",
        "CREDITS_GRAPHICS": "🎨 GRAFİK & ANİMASYON",
        "CREDITS_TECH": "🛠️ TEKNOLOJİLER",
        "CREDITS_LICENSE": "📝 LİSANS",
        "INTELLIGENZA ARTIFICIALE": "🧠 YAPAY ZEKA",
        
        "ERR_CLOSE_TABLE": "🚫 Masaya yaklaşın!",
        "ERR_ALREADY_ORDER": "❌ Zaten bir sipariş var!",
        "ERR_SINK_FULL": "🚨 Eviye dolu! Bulaşıkları yıka!",
        "ERR_CLOSE_COUNTER": "🚫 Tezgaha yaklaşın!",
        "ERR_NO_FOOD_SERVED": "❌ Bu yemeği servis etmiyoruz!",
        "ERR_TRAY_FULL": "❌ Tepsi dolu!",
        "ERR_NO_READY_FOOD": "📦 Hazır yemek yok!",
        "ERR_CLOSE_SINK": "🚫 Eviyeye yaklaşın!",
        "TRAY_FULL": "Tepsi dolu!",
        "SINK_FULL": "Eviye dolu!",
        "NO_FOOD_READY": "Hazır yemek yok",
        "COUNTER_OCCUPIED": "İstasyon dolu!",
        "MOVE_CLOSER_WASD": "WASD ile yaklaşın!",
        "MOVE_CLOSER_ARROWS": "Ok tuşlarıyla yaklaşın!",
        
        "MSG_ORDER_TAKEN": "📝 Sipariş Alındı!",
        "MSG_ORDER_REC": "📝 Sipariş alındı!",
        "MSG_SERVED": "🍽️ Servis Edildi!",
        "MSG_TABLE_CLEARED": "🧹 Masa Temizlendi!",
        "MSG_TABLE_FREE": "🪑 Masa boş",
        "FOOD_READY": "hazır!",
        "FOOD_TAKEN": "alındı!",
        "TRICK_CLICKS": "🔑 Hile:",
        "CLICKS_LEFT": "tık...",
        "WASHING": "🧼 Yıkanıyor...",
        "WASH_CLEAN": "✨ Bulaşıklar temiz!",
        "WASH_NONE": "🧼 Bulaşık yok",
        "LEAVING_ANGRY": "😡 Ayrılıyor!",
        "TABLE_SHORT": "Masa",
        "PLATE_DEPOSITED": "🧹 Tabak bırakıldı!",
        "DAY_STARTED": "🎉 {level}. GÜN BAŞLADI!",
        "TABLE_OCCUPIED": "Masa dolu",
        "ORDER_TAKEN": "Sipariş alındı!",
        "WASHING_PLATE": "🧹 Tabak bırakıldı!",
        
        "TUTORIAL_TITLE": "🎯 EĞİTİM - GÜN 0",
        "TUTORIAL_STEP_1": "👋 Hoş geldin, Garson!\nHareket etmek için WASD kullan.\nSipariş almak için müşterinin masasına git.",
        "TUTORIAL_STEP_2": "📝 Harika! Siparişi aldın.\nŞimdi mutfaktaki tezgaha git\nve siparişi Şefe ver.",
        "TUTORIAL_STEP_3": "👨‍🍳 Şef pişirdi!\nYemeği almak için tezgaha dön\nve müşteriye servis yap.",
        "TUTORIAL_STEP_4": "🍽️ Müşteri servis edildi!\nŞimdi kirli tabağı al\nve eviyeye götür.",
        "TUTORIAL_STEP_5": "🧼 Aferin!\nEviyeye tıklayarak bulaşıkları yıka.\nEğitim bitti!",
        "TUTORIAL_STEP_6": "🎉 Eğitim tamamlandı!\n3 canla 1. Gün başlıyor.",
        "TUTORIAL_TABLE": "🪑 Müşteri Masası",
        "TUTORIAL_COUNTER": "🧑‍🍳 Mutfak Tezgahı",
        "TUTORIAL_SINK": "🚿 Eviye",
        "TUTORIAL_MSG": "📖 Talimatları takip et",
        "TUTORIAL_WAIT": "⏳ Şefin pişirmesini bekle...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Eğitim oklarını takip et!",
        
        "AI_CHAT_TITLE": "💬 {name} ile Sohbet",
        "AI_CHAT_GREETING": "Merhaba! Nasıl yardımcı olabilirim?",
        "AI_CHAT_CLOSE": "Sohbeti kapat",
        "AI_CHAT_SEND": "Gönder",
        "AI_CHAT_PLACEHOLDER": "Bir mesaj yaz...",
        "AI_CHAT_LOADING": "🤔 Düşünüyorum...",
        "AI_CHAT_ERROR": "⚠️ Hata: daha sonra tekrar dene",
        "AI_CHAT_FALLBACK": "📝 Çevrimdışı moddayım!",
        
        "RADIO_TITLE": "📻 Radyo",
        "RADIO_PLAY": "▶ Oynat",
        "RADIO_STOP": "⏹ Durdur",
        "RADIO_NEXT": "⏭ Sonraki",
        "RADIO_ON": "📻 Radyo Açık",
        "RADIO_OFF": "📻 Radyo Kapalı",
        "RADIO_STATION_1": "🎵 Şarkı 1",
        "RADIO_STATION_2": "🎵 Şarkı 2",
        "RADIO_STATION_3": "🎵 Şarkı 3",
        
        "PHONE_RINGING": "📞 Telefon çalıyor!",
        "PHONE_ANSWER": "📞 Cevapla?",
        "PHONE_CALL": "📞 Görüşmede...",
        "PHONE_MESSAGE": "📱 Yeni mesaj!",
        "PHONE_DELIVERY": "📦 3 müşteri sonra özel teslimat!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Patates Kızartması",
        "FOOD_PANINO": "🍔 Hamburger",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Kaponata",
        "FOOD_CAFFE": "☕ Kahve",
        "FOOD_COLA": "🥤 Kola",
        "FOOD_ACQUA": "💧 Su",
        "FOOD_BIRRA": "🍺 Bira",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Kinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "ru": {
        "GIOCA": "▶ ИГРАТЬ",
        "IMPOSTAZIONI": "⚙ НАСТРОЙКИ",
        "CREDITI": "ℹ АВТОРЫ",
        "TORNA": "↩ В МЕНЮ",
        "VAI A CASA": "🏠 ДОМОЙ",
        "GIORNO": "⭐ День",
        "INCASSO": "💰 Выручка:",
        "SERVITI": "👥 Обслужено:",
        "VASSOIO": "📋 Поднос:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 РАКОВИНА",
        "PRONTO": "Готово! 👨‍🍳",
        "OCCUPATO": "Занято!",
        "LOADING": "Загрузка...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "СИМУЛЯТОР ОФИЦИАНТКИ И ДОМАШНЕЙ ЖИЗНИ",
        "NOTEPAD_TITLE": "📝 ЗАКАЗ",
        "NOTEPAD_EMPTY": "Блокнот пуст",
        "NOTEPAD_READY": "Готов к заказам",
        "NOTEPAD_TABLE": "Стол:",
        "DAY_COMPLETE": "⭐ ДЕНЬ ЗАВЕРШЕН! ⭐",
        "DAY_FAILED": "💀 ДЕНЬ ПРОВАЛЕН 💀",
        "DAY_FAILED_DESC": "Вы потеряли все жизни из-за злых клиентов!",
        "SAVINGS_LEFT": "💰 Остаток накоплений:",
        "DAYS_WORKED": "📅 Отработано дней:",
        "FURNITURE_BOUGHT": "🛋️ Куплено мебели:",
        "AUDIO_SETTINGS": "🔊 Звук игры",
        "ACTIVE": "ВКЛ",
        "DISABLED": "ВЫКЛ",
        "DIFFICULTY_LEVEL": "📊 Сложность",
        "EASY": "ЛЕГКО",
        "NORMAL": "НОРМАЛЬНО",
        "HARD": "СЛОЖНО",
        "CONTROL_SYSTEM": "🎮 Управление",
        "KEYBOARD": "КЛАВИАТУРА:",
        "LANGUAGE_SELECT": "🌐 Язык / Language",
        "CREDITS_TITLE": "ℹ РАЗРАБОТЧИКИ",
        "CREDITS_IDEATION": "🎮 ИДЕЯ И КОД",
        "CREDITS_SUPPORT": "🏠 ПРИ ПОДДЕРЖКЕ",
        "CREDITS_GRAPHICS": "🎨 ГРАФИКА И АНИМАЦИЯ",
        "CREDITS_TECH": "🛠️ ТЕХНОЛОГИИ",
        "CREDITS_LICENSE": "📝 ЛИЦЕНЗИЯ",
        "INTELLIGENZA ARTIFICIALE": "🧠 ИСКУССТВЕННЫЙ ИНТЕЛЛЕКТ",
        
        "ERR_CLOSE_TABLE": "🚫 Подойдите к столу!",
        "ERR_ALREADY_ORDER": "❌ У вас уже есть заказ!",
        "ERR_SINK_FULL": "🚨 Раковина полна! Помойте посуду!",
        "ERR_CLOSE_COUNTER": "🚫 Подойдите к стойке!",
        "ERR_NO_FOOD_SERVED": "❌ Мы это не подаем!",
        "ERR_TRAY_FULL": "❌ Поднос полон!",
        "ERR_NO_READY_FOOD": "📦 Нет готовой еды!",
        "ERR_CLOSE_SINK": "🚫 Подойдите к раковине!",
        "TRAY_FULL": "Поднос полон!",
        "SINK_FULL": "Раковина полна!",
        "NO_FOOD_READY": "Нет готовой еды",
        "COUNTER_OCCUPIED": "Занято!",
        "MOVE_CLOSER_WASD": "Подойдите с WASD!",
        "MOVE_CLOSER_ARROWS": "Подойдите со Стрелками!",
        
        "MSG_ORDER_TAKEN": "📝 Заказ записан!",
        "MSG_ORDER_REC": "📝 Заказ принят!",
        "MSG_SERVED": "🍽️ Подано!",
        "MSG_TABLE_CLEARED": "🧹 Стол убран!",
        "MSG_TABLE_FREE": "🪑 Стол свободен",
        "FOOD_READY": "готово!",
        "FOOD_TAKEN": "забрано!",
        "TRICK_CLICKS": "🔑 Трюк:",
        "CLICKS_LEFT": "кликов...",
        "WASHING": "🧼 Моем...",
        "WASH_CLEAN": "✨ Посуда чистая!",
        "WASH_NONE": "🧼 Нет посуды",
        "LEAVING_ANGRY": "😡 Уходит!",
        "TABLE_SHORT": "Стол",
        "PLATE_DEPOSITED": "🧹 Тарелка сдана!",
        "DAY_STARTED": "🎉 ДЕНЬ {level} НАЧАЛСЯ!",
        "TABLE_OCCUPIED": "Стол занят",
        "ORDER_TAKEN": "Заказ принят!",
        "WASHING_PLATE": "🧹 Тарелка сдана!",
        
        "TUTORIAL_TITLE": "🎯 ОБУЧЕНИЕ - ДЕНЬ 0",
        "TUTORIAL_STEP_1": "👋 Добро пожаловать, Официантка!\nИспользуй WASD для движения.\nПодойди к столу клиента, чтобы принять заказ.",
        "TUTORIAL_STEP_2": "📝 Отлично! Ты приняла заказ.\nТеперь иди к стойке на кухне,\nчтобы передать его Шеф-повару.",
        "TUTORIAL_STEP_3": "👨‍🍳 Шеф-повар приготовил!\nВернись к стойке, чтобы забрать еду\nи подать ее клиенту.",
        "TUTORIAL_STEP_4": "🍽️ Клиент обслужен!\nТеперь возьми грязную тарелку\nи отнеси ее к раковине.",
        "TUTORIAL_STEP_5": "🧼 Молодец!\nПомой тарелки, нажав на раковину.\nОбучение закончено!",
        "TUTORIAL_STEP_6": "🎉 Обучение пройдено!\nНачинай День 1 с 3 жизнями.",
        "TUTORIAL_TABLE": "🪑 Стол Клиента",
        "TUTORIAL_COUNTER": "🧑‍🍳 Кухонная Стойка",
        "TUTORIAL_SINK": "🚿 Раковина",
        "TUTORIAL_MSG": "📖 Следуй инструкциям",
        "TUTORIAL_WAIT": "⏳ Подожди, пока Шеф-повар готовит...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Следуй стрелкам обучения!",
        
        "AI_CHAT_TITLE": "💬 Чат с {name}",
        "AI_CHAT_GREETING": "Здравствуйте! Чем могу помочь?",
        "AI_CHAT_CLOSE": "Закрыть чат",
        "AI_CHAT_SEND": "Отправить",
        "AI_CHAT_PLACEHOLDER": "Напишите сообщение...",
        "AI_CHAT_LOADING": "🤔 Думаю...",
        "AI_CHAT_ERROR": "⚠️ Ошибка: попробуйте позже",
        "AI_CHAT_FALLBACK": "📝 Я в режиме офлайн!",
        
        "RADIO_TITLE": "📻 Радио",
        "RADIO_PLAY": "▶ Воспроизвести",
        "RADIO_STOP": "⏹ Остановить",
        "RADIO_NEXT": "⏭ Следующий",
        "RADIO_ON": "📻 Радио Включено",
        "RADIO_OFF": "📻 Радио Выключено",
        "RADIO_STATION_1": "🎵 Песня 1",
        "RADIO_STATION_2": "🎵 Песня 2",
        "RADIO_STATION_3": "🎵 Песня 3",
        
        "PHONE_RINGING": "📞 Телефон звонит!",
        "PHONE_ANSWER": "📞 Ответить?",
        "PHONE_CALL": "📞 В разговоре...",
        "PHONE_MESSAGE": "📱 Новое сообщение!",
        "PHONE_DELIVERY": "📦 Спецдоставка через 3 клиентов!",
        
        "FOOD_PIZZA": "🍕 Пицца",
        "FOOD_PATATINE": "🍟 Картошка фри",
        "FOOD_PANINO": "🍔 Бургер",
        "FOOD_RISOTTO": "🍚 Ризотто",
        "FOOD_CAPONATA": "🍆 Капоната",
        "FOOD_CAFFE": "☕ Кофе",
        "FOOD_COLA": "🥤 Кола",
        "FOOD_ACQUA": "💧 Вода",
        "FOOD_BIRRA": "🍺 Пиво",
        "FOOD_ARANCINA": "🧆 Аранчина",
        "FOOD_CASSATA": "🍰 Кассата",
        "FOOD_CHINOTTO": "🥤 Кинотто",
        "FOOD_CANNOLO": "🥐 Канноло",
        "FOOD_GINSENG": "☕ Женьшень"
    },
    "ja": {
        "GIOCA": "▶ プレイ",
        "IMPOSTAZIONI": "⚙ 設定",
        "CREDITI": "ℹ クレジット",
        "TORNA": "↩ メニューへ戻る",
        "VAI A CASA": "🏠 帰宅する",
        "GIORNO": "⭐ 日目",
        "INCASSO": "💰 売上:",
        "SERVITI": "👥 接客数:",
        "VASSOIO": "📋 トレイ:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 シンク",
        "PRONTO": "完成！ 👨‍🍳",
        "OCCUPATO": "使用中！",
        "LOADING": "読み込み中...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "ウェイトレス＆ライフシミュレーター",
        "NOTEPAD_TITLE": "📝 注文メモ",
        "NOTEPAD_EMPTY": "メモは空です",
        "NOTEPAD_READY": "注文準備完了",
        "NOTEPAD_TABLE": "テーブル:",
        "DAY_COMPLETE": "⭐ 1日クリア！ ⭐",
        "DAY_FAILED": "💀 営業失敗 💀",
        "DAY_FAILED_DESC": "怒ったお客様のせいでライフが無くなりました！",
        "SAVINGS_LEFT": "💰 貯金残高:",
        "DAYS_WORKED": "📅 労働日数:",
        "FURNITURE_BOUGHT": "🛋️ 購入した家具:",
        "AUDIO_SETTINGS": "🔊 ゲーム音量",
        "ACTIVE": "有効",
        "DISABLED": "無効",
        "DIFFICULTY_LEVEL": "📊 難易度",
        "EASY": "かんたん",
        "NORMAL": "ふつう",
        "HARD": "むずかしい",
        "CONTROL_SYSTEM": "🎮 操作方法",
        "KEYBOARD": "キーボード:",
        "LANGUAGE_SELECT": "🌐 言語 / Language",
        "CREDITS_TITLE": "ℹ 開発クレジット",
        "CREDITS_IDEATION": "🎮 企画・開発",
        "CREDITS_SUPPORT": "🏠 協力",
        "CREDITS_GRAPHICS": "🎨 グラフィック・アニメ",
        "CREDITS_TECH": "🛠️ 使用技術",
        "CREDITS_LICENSE": "📝 ライセンス",
        "INTELLIGENZA ARTIFICIALE": "🧠 人工知能",
        
        "ERR_CLOSE_TABLE": "🚫 テーブルに近づいてください！",
        "ERR_ALREADY_ORDER": "❌ 既に注文を受けています！",
        "ERR_SINK_FULL": "🚨 シンクがいっぱいです！皿を洗ってください！",
        "ERR_CLOSE_COUNTER": "🚫 カウンターに近づいてください！",
        "ERR_NO_FOOD_SERVED": "❌ その料理は提供していません！",
        "ERR_TRAY_FULL": "❌ トレイがいっぱいです！",
        "ERR_NO_READY_FOOD": "📦 出来上がり料理がありません！",
        "ERR_CLOSE_SINK": "🚫 シンクに近づいてください！",
        "TRAY_FULL": "トレイがいっぱいです！",
        "SINK_FULL": "シンクがいっぱいです！",
        "NO_FOOD_READY": "出来上がり料理がありません",
        "COUNTER_OCCUPIED": "使用中！",
        "MOVE_CLOSER_WASD": "WASDで近づいてください！",
        "MOVE_CLOSER_ARROWS": "矢印キーで近づいてください！",
        
        "MSG_ORDER_TAKEN": "📝 注文を受けました！",
        "MSG_ORDER_REC": "📝 注文完了！",
        "MSG_SERVED": "🍽️ 配膳完了！",
        "MSG_TABLE_CLEARED": "🧹 片付け完了！",
        "MSG_TABLE_FREE": "🪑 空席",
        "FOOD_READY": "完成！",
        "FOOD_TAKEN": "受け取り！",
        "TRICK_CLICKS": "🔑 裏技:",
        "CLICKS_LEFT": "クリック...",
        "WASHING": "🧼 洗浄中...",
        "WASH_CLEAN": "✨ ピカピカ！",
        "WASH_NONE": "🧼 皿がありません",
        "LEAVING_ANGRY": "😡 帰ってしまった！",
        "TABLE_SHORT": "卓",
        "PLATE_DEPOSITED": "🧹 皿を置きました！",
        "DAY_STARTED": "🎉 {level}日目が始まりました！",
        "TABLE_OCCUPIED": "使用中",
        "ORDER_TAKEN": "注文を受けました！",
        "WASHING_PLATE": "🧹 皿を置きました！",
        
        "TUTORIAL_TITLE": "🎯 チュートリアル - 0日目",
        "TUTORIAL_STEP_1": "👋 ようこそ、ウェイトレスさん！\nWASDで移動します。\nお客様のテーブルに行って注文を聞いてください。",
        "TUTORIAL_STEP_2": "📝 注文を聞きましたね！\nキッチンのカウンターに行って\nシェフに注文を渡してください。",
        "TUTORIAL_STEP_3": "👨‍🍳 シェフが調理しました！\nカウンターに戻って料理を受け取り\nお客様に提供してください。",
        "TUTORIAL_STEP_4": "🍽️ お客様に提供しました！\n今度は汚れた皿を取って\nシンクに持って行ってください。",
        "TUTORIAL_STEP_5": "🧼 よくできました！\nシンクをクリックして皿を洗ってください。\nチュートリアルは終了です！",
        "TUTORIAL_STEP_6": "🎉 チュートリアル完了！\n3つのライフで1日目を始めましょう。",
        "TUTORIAL_TABLE": "🪑 お客様のテーブル",
        "TUTORIAL_COUNTER": "🧑‍🍳 キッチンカウンター",
        "TUTORIAL_SINK": "🚿 シンク",
        "TUTORIAL_MSG": "📖 指示に従ってください",
        "TUTORIAL_WAIT": "⏳ シェフが調理するのを待って...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ チュートリアルの矢印に従ってください！",
        
        "AI_CHAT_TITLE": "💬 {name}とのチャット",
        "AI_CHAT_GREETING": "こんにちは！どのようにお手伝いしましょうか？",
        "AI_CHAT_CLOSE": "チャットを閉じる",
        "AI_CHAT_SEND": "送信",
        "AI_CHAT_PLACEHOLDER": "メッセージを入力...",
        "AI_CHAT_LOADING": "🤔 考え中...",
        "AI_CHAT_ERROR": "⚠️ エラー：後でもう一度お試しください",
        "AI_CHAT_FALLBACK": "📝 オフラインモードです！",
        
        "RADIO_TITLE": "📻 ラジオ",
        "RADIO_PLAY": "▶ 再生",
        "RADIO_STOP": "⏹ 停止",
        "RADIO_NEXT": "⏭ 次へ",
        "RADIO_ON": "📻 ラジオオン",
        "RADIO_OFF": "📻 ラジオオフ",
        "RADIO_STATION_1": "🎵 曲1",
        "RADIO_STATION_2": "🎵 曲2",
        "RADIO_STATION_3": "🎵 曲3",
        
        "PHONE_RINGING": "📞 電話が鳴っています！",
        "PHONE_ANSWER": "📞 出ますか？",
        "PHONE_CALL": "📞 通話中...",
        "PHONE_MESSAGE": "📱 新しいメッセージ！",
        "PHONE_DELIVERY": "📦 あと3人のお客様で特別配達！",
        
        "FOOD_PIZZA": "🍕 ピザ",
        "FOOD_PATATINE": "🍟 フライドポテト",
        "FOOD_PANINO": "🍔 ハンバーガー",
        "FOOD_RISOTTO": "🍚 リゾット",
        "FOOD_CAPONATA": "🍆 カポナータ",
        "FOOD_CAFFE": "☕ コーヒー",
        "FOOD_COLA": "🥤 コーラ",
        "FOOD_ACQUA": "💧 水",
        "FOOD_BIRRA": "🍺 ビール",
        "FOOD_ARANCINA": "🧆 アランチーニ",
        "FOOD_CASSATA": "🍰 カッサータ",
        "FOOD_CHINOTTO": "🥤 キノット",
        "FOOD_CANNOLO": "🥐 カンノーロ",
        "FOOD_GINSENG": "☕ ギンセン"
    },
    "pl": {
        "GIOCA": "▶ GRAJ",
        "IMPOSTAZIONI": "⚙ USTAWIENIA",
        "CREDITI": "ℹ TWÓRCY",
        "TORNA": "↩ POWRÓT DO MENU",
        "VAI A CASA": "🏠 IDŹ DO DOMU",
        "GIORNO": "⭐ Dzień",
        "INCASSO": "💰 Zarobek:",
        "SERVITI": "👥 Obsłużeni:",
        "VASSOIO": "📋 Taca:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 ZLEW",
        "PRONTO": "Gotowe! 👨‍🍳",
        "OCCUPATO": "Stowisko zajęte!",
        "LOADING": "Ładowanie...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SYMULATOR KELNERKI I ŻYCIA W DOMU",
        "NOTEPAD_TITLE": "📝 ZAMÓWIENIE",
        "NOTEPAD_EMPTY": "Notatnik Pusty",
        "NOTEPAD_READY": "Gotowy na zamówienia",
        "NOTEPAD_TABLE": "Stolik:",
        "DAY_COMPLETE": "⭐ DZIEŃ ZAKOŃCZONY! ⭐",
        "DAY_FAILED": "💀 DZIEŃ NIEUDANY 💀",
        "DAY_FAILED_DESC": "Straciłeś wszystkie życia przez złość klientów!",
        "SAVINGS_LEFT": "💰 Pozostałe oszczędności:",
        "DAYS_WORKED": "📅 Przepracowane dni:",
        "FURNITURE_BOUGHT": "🛋️ Kupione meble:",
        "AUDIO_SETTINGS": "🔊 Dźwięk w grze",
        "ACTIVE": "WŁĄCZONE",
        "DISABLED": "WYŁĄCZONE",
        "DIFFICULTY_LEVEL": "📊 Poziom Trudności",
        "EASY": "ŁATWY",
        "NORMAL": "NORMALNY",
        "HARD": "TRUDNY",
        "CONTROL_SYSTEM": "🎮 Sterowanie",
        "KEYBOARD": "KLAWIATURA:",
        "LANGUAGE_SELECT": "🌐 Język / Language",
        "CREDITS_TITLE": "ℹ AUTORZY",
        "CREDITS_IDEATION": "🎮 POMYSŁ I KOD",
        "CREDITS_SUPPORT": "🏠 WSPARCIE",
        "CREDITS_GRAPHICS": "🎨 GRAFIKA I ANIMACJE",
        "CREDITS_TECH": "🛠️ TECHNOLOGIE",
        "CREDITS_LICENSE": "📝 LICENCJA",
        "INTELLIGENZA ARTIFICIALE": "🧠 SZTUCZNA INTELIGENCJA",
        
        "ERR_CLOSE_TABLE": "🚫 Podejdź do stolika!",
        "ERR_ALREADY_ORDER": "❌ Masz już zamówienie!",
        "ERR_SINK_FULL": "🚨 Zlew przepełniony! Umyj naczynia!",
        "ERR_CLOSE_COUNTER": "🚫 Podejdź do lady!",
        "ERR_NO_FOOD_SERVED": "❌ Nie serwujemy tego!",
        "ERR_TRAY_FULL": "❌ Taca pełna!",
        "ERR_NO_READY_FOOD": "📦 Brak gotowych dań!",
        "ERR_CLOSE_SINK": "🚫 Podejdź do zlewu!",
        "TRAY_FULL": "Taca pełna!",
        "SINK_FULL": "Zlew pełny!",
        "NO_FOOD_READY": "Brak gotowego jedzenia",
        "COUNTER_OCCUPIED": "Stanowisko zajęte!",
        "MOVE_CLOSER_WASD": "Podejdź z WASD!",
        "MOVE_CLOSER_ARROWS": "Podejdź ze Strzałkami!",
        
        "MSG_ORDER_TAKEN": "📝 Zamówienie Przyjęte!",
        "MSG_ORDER_REC": "📝 Zrealizowano zamówienie!",
        "MSG_SERVED": "🍽️ Podano!",
        "MSG_TABLE_CLEARED": "🧹 Stolik Posprzątany!",
        "MSG_TABLE_FREE": "🪑 Stolik wolny",
        "FOOD_READY": "gotowe!",
        "FOOD_TAKEN": "pobrane!",
        "TRICK_CLICKS": "🔑 Kod:",
        "CLICKS_LEFT": "kliknięć...",
        "WASHING": "🧼 Mycie...",
        "WASH_CLEAN": "✨ Czyste naczynia!",
        "WASH_NONE": "🧼 Brak naczyń",
        "LEAVING_ANGRY": "😡 Wychodzi!",
        "TABLE_SHORT": "Stół",
        "PLATE_DEPOSITED": "🧹 Talerz odłożony!",
        "DAY_STARTED": "🎉 ROZPOCZĘTO DZIEŃ {level}!",
        "TABLE_OCCUPIED": "Stolik zajęty",
        "ORDER_TAKEN": "Zamówienie przyjęte!",
        "WASHING_PLATE": "🧹 Talerz odłożony!",
        
        "TUTORIAL_TITLE": "🎯 TUTORIAL - DZIEŃ 0",
        "TUTORIAL_STEP_1": "👋 Witaj, Kelnerko!\nUżyj WASD aby się poruszać.\nIdź do stolika klienta, aby przyjąć zamówienie.",
        "TUTORIAL_STEP_2": "📝 Świetnie! Przyjęłaś zamówienie.\nTeraz idź do lady w kuchni,\naby przekazać je Szefowi.",
        "TUTORIAL_STEP_3": "👨‍🍳 Szef ugotował!\nWróć do lady, aby odebrać jedzenie\ni podać je klientowi.",
        "TUTORIAL_STEP_4": "🍽️ Klient obsłużony!\nTeraz weź brudny talerz\ni zanieś go do zlewu.",
        "TUTORIAL_STEP_5": "🧼 Dobra robota!\nUmyj naczynia klikając na zlew.\nTutorial zakończony!",
        "TUTORIAL_STEP_6": "🎉 Tutorial ukończony!\nRozpocznij Dzień 1 z 3 życiami.",
        "TUTORIAL_TABLE": "🪑 Stolik Klienta",
        "TUTORIAL_COUNTER": "🧑‍🍳 Lada Kuchenna",
        "TUTORIAL_SINK": "🚿 Zlew",
        "TUTORIAL_MSG": "📖 Postępuj zgodnie z instrukcjami",
        "TUTORIAL_WAIT": "⏳ Poczekaj, aż Szef ugotuje...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Postępuj zgodnie ze strzałkami tutoriala!",
        
        "AI_CHAT_TITLE": "💬 Czat z {name}",
        "AI_CHAT_GREETING": "Cześć! Jak mogę pomóc?",
        "AI_CHAT_CLOSE": "Zamknij czat",
        "AI_CHAT_SEND": "Wyślij",
        "AI_CHAT_PLACEHOLDER": "Napisz wiadomość...",
        "AI_CHAT_LOADING": "🤔 Myślę...",
        "AI_CHAT_ERROR": "⚠️ Błąd: spróbuj ponownie później",
        "AI_CHAT_FALLBACK": "📝 Jestem w trybie offline!",
        
        "RADIO_TITLE": "📻 Radio",
        "RADIO_PLAY": "▶ Odtwarzaj",
        "RADIO_STOP": "⏹ Zatrzymaj",
        "RADIO_NEXT": "⏭ Następny",
        "RADIO_ON": "📻 Radio Włączone",
        "RADIO_OFF": "📻 Radio Wyłączone",
        "RADIO_STATION_1": "🎵 Piosenka 1",
        "RADIO_STATION_2": "🎵 Piosenka 2",
        "RADIO_STATION_3": "🎵 Piosenka 3",
        
        "PHONE_RINGING": "📞 Telefon dzwoni!",
        "PHONE_ANSWER": "📞 Odebrać?",
        "PHONE_CALL": "📞 W rozmowie...",
        "PHONE_MESSAGE": "📱 Nowa wiadomość!",
        "PHONE_DELIVERY": "📦 Specjalna dostawa za 3 klientów!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Frytki",
        "FOOD_PANINO": "🍔 Burger",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Kaponata",
        "FOOD_CAFFE": "☕ Kawa",
        "FOOD_COLA": "🥤 Cola",
        "FOOD_ACQUA": "💧 Woda",
        "FOOD_BIRRA": "🍺 Piwo",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "hu": {
        "GIOCA": "▶ JÁTÉK",
        "IMPOSTAZIONI": "⚙ BEÁLLÍTÁSOK",
        "CREDITI": "ℹ ALKOTÓK",
        "TORNA": "↩ VISSZA A MENÜBE",
        "VAI A CASA": "🏠 HAZAMENETEL",
        "GIORNO": "⭐ Nap",
        "INCASSO": "💰 Bevétel:",
        "SERVITI": "👥 Kiszolgálva:",
        "VASSOIO": "📋 Tálca:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 MOSOGATÓ",
        "PRONTO": "Kész! 👨‍🍳",
        "OCCUPATO": "Foglalt hely!",
        "LOADING": "Betöltés...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "PINCÉRNŐ ÉS OTTHONI ÉLET SZIMULÁTOR",
        "NOTEPAD_TITLE": "📝 RENDELÉS",
        "NOTEPAD_EMPTY": "Üres jegyzetfüzet",
        "NOTEPAD_READY": "Készen áll a rendelésre",
        "NOTEPAD_TABLE": "Asztal:",
        "DAY_COMPLETE": "⭐ NAP TELJESÍTVE! ⭐",
        "DAY_FAILED": "💀 NAP SIKERTELEN 💀",
        "DAY_FAILED_DESC": "Minden életet elveszítettél a mérges vendégek miatt!",
        "SAVINGS_LEFT": "💰 Megmaradt megtakarítás:",
        "DAYS_WORKED": "📅 Ledolgozott napok:",
        "FURNITURE_BOUGHT": "🛋️ Vásárolt bútorok:",
        "AUDIO_SETTINGS": "🔊 Játék hangja",
        "ACTIVE": "BEKAPCSOLVA",
        "DISABLED": "KIKAPCSOLVA",
        "DIFFICULTY_LEVEL": "📊 Nehézség",
        "EASY": "KÖNNYŰ",
        "NORMAL": "NORMÁL",
        "HARD": "NEHÉZ",
        "CONTROL_SYSTEM": "🎮 Irányítás",
        "KEYBOARD": "BILLENTYŰZET:",
        "LANGUAGE_SELECT": "🌐 Nyelv / Language",
        "CREDITS_TITLE": "ℹ ALKOTÓK",
        "CREDITS_IDEATION": "🎮 ÖTLET ÉS KÓD",
        "CREDITS_SUPPORT": "🏠 TÁMOGATÓK",
        "CREDITS_GRAPHICS": "🎨 GRAFIKA ÉS ANIMÁCIÓ",
        "CREDITS_TECH": "🛠️ TECHNOLÓGIÁK",
        "CREDITS_LICENSE": "📝 LICENC",
        "INTELLIGENZA ARTIFICIALE": "🧠 MESTERSÉGES INTELLIGENCIA",
        
        "ERR_CLOSE_TABLE": "🚫 Menj közelebb az asztalhoz!",
        "ERR_ALREADY_ORDER": "❌ Már van egy rendelésed!",
        "ERR_SINK_FULL": "🚨 Tele a mosogató! Mosogass el!",
        "ERR_CLOSE_COUNTER": "🚫 Menj közelebb a pulthoz!",
        "ERR_NO_FOOD_SERVED": "❌ Ezt nem szolgáljuk fel!",
        "ERR_TRAY_FULL": "❌ Tele a tálca!",
        "ERR_NO_READY_FOOD": "📦 Nincs kész étel!",
        "ERR_CLOSE_SINK": "🚫 Menj közelebb a mosogatóhoz!",
        "TRAY_FULL": "Tálca tele!",
        "SINK_FULL": "Mosogató tele!",
        "NO_FOOD_READY": "Nincs kész étel",
        "COUNTER_OCCUPIED": "Foglalt hely!",
        "MOVE_CLOSER_WASD": "Közelíts WASD-val!",
        "MOVE_CLOSER_ARROWS": "Közelíts a Nyilakkal!",
        
        "MSG_ORDER_TAKEN": "📝 Rendelés felvéve!",
        "MSG_ORDER_REC": "📝 Rendelés megérkezett!",
        "MSG_SERVED": "🍽️ Felszolgálva!",
        "MSG_TABLE_CLEARED": "🧹 Asztal letakarítva!",
        "MSG_TABLE_FREE": "🪑 Szabad asztal",
        "FOOD_READY": "kész!",
        "FOOD_TAKEN": "elvégre!",
        "TRICK_CLICKS": "🔑 Csalás:",
        "CLICKS_LEFT": "Kattintás...",
        "WASHING": "🧼 Mosogatás...",
        "WASH_CLEAN": "✨ Tiszta edények!",
        "WASH_NONE": "🧼 Nincs edény",
        "LEAVING_ANGRY": "😡 Elmegy!",
        "TABLE_SHORT": "Aszt.",
        "PLATE_DEPOSITED": "🧹 Tányér lerakva!",
        "DAY_STARTED": "🎉 {level}. NAP ELKEZDŐDÖTT!",
        "TABLE_OCCUPIED": "Asztal foglalt",
        "ORDER_TAKEN": "Rendelés felvéve!",
        "WASHING_PLATE": "🧹 Tányér lerakva!",
        
        "TUTORIAL_TITLE": "🎯 OKTATÓ - 0. NAP",
        "TUTORIAL_STEP_1": "👋 Üdvözöllek, Pincérnő!\nA WASD használatával mozoghatsz.\nMenj a vendég asztalához, hogy felvegye a rendelést.",
        "TUTORIAL_STEP_2": "📝 Remek! Felvetted a rendelést.\nMost menj a konyhai pultboz,\nhogy átadd a Szakácsnak.",
        "TUTORIAL_STEP_3": "👨‍🍳 A Szakács megfőzte!\nMenj vissza a pultboz, hogy elvedd az ételt\nés tálald a vendégnek.",
        "TUTORIAL_STEP_4": "🍽️ Vendég kiszolgálva!\nMost vedd el a koszos tányért\nés vidd a mosogatóhoz.",
        "TUTORIAL_STEP_5": "🧼 Szép munka!\nMosogass el a mosogatóra kattintva.\nAz oktató véget ért!",
        "TUTORIAL_STEP_6": "🎉 Oktató befejezve!\nKezdd el az 1. napot 3 élettel.",
        "TUTORIAL_TABLE": "🪑 Vendég Asztal",
        "TUTORIAL_COUNTER": "🧑‍🍳 Konyhai Pult",
        "TUTORIAL_SINK": "🚿 Mosogató",
        "TUTORIAL_MSG": "📖 Kövesd az utasításokat",
        "TUTORIAL_WAIT": "⏳ Várd meg, míg a Szakács főz...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Kövesd az oktató nyilait!",
        
        "AI_CHAT_TITLE": "💬 Csevegés {name}-vel",
        "AI_CHAT_GREETING": "Szia! Hogyan segíthetek?",
        "AI_CHAT_CLOSE": "Csevegés bezárása",
        "AI_CHAT_SEND": "Küldés",
        "AI_CHAT_PLACEHOLDER": "Írj egy üzenetet...",
        "AI_CHAT_LOADING": "🤔 Gondolkodom...",
        "AI_CHAT_ERROR": "⚠️ Hiba: próbáld újra később",
        "AI_CHAT_FALLBACK": "📝 Offline módban vagyok!",
        
        "RADIO_TITLE": "📻 Rádió",
        "RADIO_PLAY": "▶ Lejátszás",
        "RADIO_STOP": "⏹ Megállítás",
        "RADIO_NEXT": "⏭ Következő",
        "RADIO_ON": "📻 Rádió Be",
        "RADIO_OFF": "📻 Rádió Ki",
        "RADIO_STATION_1": "🎵 Dal 1",
        "RADIO_STATION_2": "🎵 Dal 2",
        "RADIO_STATION_3": "🎵 Dal 3",
        
        "PHONE_RINGING": "📞 Csörög a telefon!",
        "PHONE_ANSWER": "📞 Felveszed?",
        "PHONE_CALL": "📞 Hívásban...",
        "PHONE_MESSAGE": "📱 Új üzenet!",
        "PHONE_DELIVERY": "📦 Különleges szállítás 3 vendég múlva!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Hasábburgonya",
        "FOOD_PANINO": "🍔 Hamburger",
        "FOOD_RISOTTO": "🍚 Rizottó",
        "FOOD_CAPONATA": "🍆 Kaponáta",
        "FOOD_CAFFE": "☕ Kávé",
        "FOOD_COLA": "🥤 Kóla",
        "FOOD_ACQUA": "💧 Víz",
        "FOOD_BIRRA": "🍺 Sör",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "pt": {
        "GIOCA": "▶ JOGAR",
        "IMPOSTAZIONI": "⚙ CONFIGURAÇÕES",
        "CREDITI": "ℹ CRÉDITOS",
        "TORNA": "↩ VOLTAR AO MENU",
        "VAI A CASA": "🏠 IR PARA CASA",
        "GIORNO": "⭐ Dia",
        "INCASSO": "💰 Lucro:",
        "SERVITI": "👥 Atendidos:",
        "VASSOIO": "📋 Bandeja:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 PIA",
        "PRONTO": "Pronto! 👨‍🍳",
        "OCCUPATO": "Posto ocupado!",
        "LOADING": "Carregando...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULADOR DE GARÇONETE E VIDA EM CASA",
        "NOTEPAD_TITLE": "📝 PEDIDO",
        "NOTEPAD_EMPTY": "Bloco Vazio",
        "NOTEPAD_READY": "Pronto para pedidos",
        "NOTEPAD_TABLE": "Mesa:",
        "DAY_COMPLETE": "⭐ DIA CONCLUÍDO! ⭐",
        "DAY_FAILED": "💀 DIA FRACASSADO 💀",
        "DAY_FAILED_DESC": "Você perdeu todas as vidas devido a clientes zangados!",
        "SAVINGS_LEFT": "💰 Economias restantes:",
        "DAYS_WORKED": "📅 Dias trabalhados:",
        "FURNITURE_BOUGHT": "🛋️ Móveis comprados:",
        "AUDIO_SETTINGS": "🔊 Áudio do jogo",
        "ACTIVE": "ATIVADO",
        "DISABLED": "DESATIVADO",
        "DIFFICULTY_LEVEL": "📊 Dificuldade",
        "EASY": "FÁCIL",
        "NORMAL": "NORMAL",
        "HARD": "DIFÍCIL",
        "CONTROL_SYSTEM": "🎮 Controles",
        "KEYBOARD": "TECLADO:",
        "LANGUAGE_SELECT": "🌐 Idioma / Language",
        "CREDITS_TITLE": "ℹ CRÉDITOS",
        "CREDITS_IDEATION": "🎮 IDEIA E CÓDIGO ORIGINAL",
        "CREDITS_SUPPORT": "🏠 COM O APOIO DE",
        "CREDITS_GRAPHICS": "🎨 GRÁFICOS E ANIMAÇÕES",
        "CREDITS_TECH": "🛠️ TECNOLOGIAS INTEGRADAS",
        "CREDITS_LICENSE": "📝 LICENÇA",
        "INTELLIGENZA ARTIFICIALE": "🧠 INTELIGÊNCIA ARTIFICIAL",
        
        "ERR_CLOSE_TABLE": "🚫 Aproxime-se da mesa!",
        "ERR_ALREADY_ORDER": "❌ Você já tem um pedido!",
        "ERR_SINK_FULL": "🚨 Pia cheia! Lave a louça!",
        "ERR_CLOSE_COUNTER": "🚫 Aproxime-se do balcão!",
        "ERR_NO_FOOD_SERVED": "❌ Não servimos essa comida!",
        "ERR_TRAY_FULL": "❌ Bandeja cheia!",
        "ERR_NO_READY_FOOD": "📦 Nenhuma comida pronta!",
        "ERR_CLOSE_SINK": "🚫 Aproxime-se da pia!",
        "TRAY_FULL": "Bandeja cheia!",
        "SINK_FULL": "Pia cheia!",
        "NO_FOOD_READY": "Nenhuma comida pronta",
        "COUNTER_OCCUPIED": "Posto ocupado!",
        "MOVE_CLOSER_WASD": "Aproxime-se com WASD!",
        "MOVE_CLOSER_ARROWS": "Aproxime-se com as Setas!",
        
        "MSG_ORDER_TAKEN": "📝 Pedido Anotado!",
        "MSG_ORDER_REC": "📝 Pedido recebido!",
        "MSG_SERVED": "🍽️ Servido!",
        "MSG_TABLE_CLEARED": "🧹 Mesa Limpa!",
        "MSG_TABLE_FREE": "🪑 Mesa livre",
        "FOOD_READY": "pronto!",
        "FOOD_TAKEN": "retirado!",
        "TRICK_CLICKS": "🔑 Truque:",
        "CLICKS_LEFT": "cliques...",
        "WASHING": "🧼 Lavando...",
        "WASH_CLEAN": "✨ Louça limpa!",
        "WASH_NONE": "🧼 Sem louça",
        "LEAVING_ANGRY": "😡 Vai embora!",
        "TABLE_SHORT": "Mesa",
        "PLATE_DEPOSITED": "🧹 Prato depositado!",
        "DAY_STARTED": "🎉 DIA {level} INICIADO!",
        "TABLE_OCCUPIED": "Mesa ocupada",
        "ORDER_TAKEN": "Pedido anotado!",
        "WASHING_PLATE": "🧹 Prato depositado!",
        
        "TUTORIAL_TITLE": "🎯 TUTORIAL - DIA 0",
        "TUTORIAL_STEP_1": "👋 Bem-vinda, Garçonete!\nUse WASD para se mover.\nVá à mesa do cliente para anotar o pedido.",
        "TUTORIAL_STEP_2": "📝 Ótimo! Você anotou o pedido.\nAgora vá ao balcão da cozinha\npara entregar ao Chef.",
        "TUTORIAL_STEP_3": "👨‍🍳 O Chef cozinhou!\nVolte ao balcão para pegar a comida\ne servir ao cliente.",
        "TUTORIAL_STEP_4": "🍽️ Cliente servido!\nAgora pegue o prato sujo\ne leve à pia.",
        "TUTORIAL_STEP_5": "🧼 Bem feito!\nLave os pratos clicando na pia.\nO tutorial acabou!",
        "TUTORIAL_STEP_6": "🎉 Tutorial concluído!\nComece o Dia 1 com 3 vidas.",
        "TUTORIAL_TABLE": "🪑 Mesa do Cliente",
        "TUTORIAL_COUNTER": "🧑‍🍳 Balcão da Cozinha",
        "TUTORIAL_SINK": "🚿 Pia",
        "TUTORIAL_MSG": "📖 Siga as instruções",
        "TUTORIAL_WAIT": "⏳ Espere o Chef cozinhar...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Siga as setas do tutorial!",
        
        "AI_CHAT_TITLE": "💬 Chat com {name}",
        "AI_CHAT_GREETING": "Olá! Como posso ajudar?",
        "AI_CHAT_CLOSE": "Fechar chat",
        "AI_CHAT_SEND": "Enviar",
        "AI_CHAT_PLACEHOLDER": "Escreva uma mensagem...",
        "AI_CHAT_LOADING": "🤔 Pensando...",
        "AI_CHAT_ERROR": "⚠️ Erro: tente novamente mais tarde",
        "AI_CHAT_FALLBACK": "📝 Estou em modo offline!",
        
        "RADIO_TITLE": "📻 Rádio",
        "RADIO_PLAY": "▶ Tocar",
        "RADIO_STOP": "⏹ Parar",
        "RADIO_NEXT": "⏭ Próximo",
        "RADIO_ON": "📻 Rádio Ligado",
        "RADIO_OFF": "📻 Rádio Desligado",
        "RADIO_STATION_1": "🎵 Música 1",
        "RADIO_STATION_2": "🎵 Música 2",
        "RADIO_STATION_3": "🎵 Música 3",
        
        "PHONE_RINGING": "📞 O telefone está tocando!",
        "PHONE_ANSWER": "📞 Atender?",
        "PHONE_CALL": "📞 Em chamada...",
        "PHONE_MESSAGE": "📱 Nova mensagem!",
        "PHONE_DELIVERY": "📦 Entrega especial em 3 clientes!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Batatas Fritas",
        "FOOD_PANINO": "🍔 Hambúrguer",
        "FOOD_RISOTTO": "🍚 Risoto",
        "FOOD_CAPONATA": "🍆 Caponata",
        "FOOD_CAFFE": "☕ Café",
        "FOOD_COLA": "🥤 Cola",
        "FOOD_ACQUA": "💧 Água",
        "FOOD_BIRRA": "🍺 Cerveja",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "hi": {
        "GIOCA": "▶ खेलें",
        "IMPOSTAZIONI": "⚙ सेटिंग्स",
        "CREDITI": "ℹ क्रेडिट्स",
        "TORNA": "↩ मेनू पर वापस जाएँ",
        "VAI A CASA": "🏠 घर जाएँ",
        "GIORNO": "⭐ दिन",
        "INCASSO": "💰 कमाई:",
        "SERVITI": "👥 सेवा की:",
        "VASSOIO": "📋 ट्रे:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 सिंक",
        "PRONTO": "तैयार! 👨‍🍳",
        "OCCUPATO": "जगह व्यस्त है!",
        "LOADING": "लोड हो रहा है...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "वेट्रेस और गृहस्थ जीवन सिम्युलेटर",
        "NOTEPAD_TITLE": "📝 ऑर्डर",
        "NOTEPAD_EMPTY": "नोटपैड खाली है",
        "NOTEPAD_READY": "ऑर्डर के लिए तैयार",
        "NOTEPAD_TABLE": "टेबल:",
        "DAY_COMPLETE": "⭐ दिन पूरा हुआ! ⭐",
        "DAY_FAILED": "💀 दिन असफल 💀",
        "DAY_FAILED_DESC": "गुस्साए ग्राहकों के कारण आपने सभी जानें गंवा दीं!",
        "SAVINGS_LEFT": "💰 बची हुई बचत:",
        "DAYS_WORKED": "📅 काम किए गए दिन:",
        "FURNITURE_BOUGHT": "🛋️ खरीदे गए फर्नीचर:",
        "AUDIO_SETTINGS": "🔊 गेम ऑडियो",
        "ACTIVE": "सक्रिय",
        "DISABLED": "निष्क्रिय",
        "DIFFICULTY_LEVEL": "📊 कठिनाई का स्तर",
        "EASY": "आसान",
        "NORMAL": "सामान्य",
        "HARD": "कठिन",
        "CONTROL_SYSTEM": "🎮 नियंत्रण प्रणाली",
        "KEYBOARD": "कीबोर्ड:",
        "LANGUAGE_SELECT": "🌐 भाषा / Language",
        "CREDITS_TITLE": "ℹ विकास श्रेय",
        "CREDITS_IDEATION": "🎮 विचार और मूल कोड",
        "CREDITS_SUPPORT": "🏠 के सहयोग से",
        "CREDITS_GRAPHICS": "🎨 ग्राफिक्स और एनिमेशन",
        "CREDITS_TECH": "🛠️ एकीकृत प्रौद्योगिकियां",
        "CREDITS_LICENSE": "📝 लाइसेंस",
        "INTELLIGENZA ARTIFICIALE": "🧠 कृत्रिम बुद्धिमत्ता",
        
        "ERR_CLOSE_TABLE": "🚫 टेबल के पास जाएँ!",
        "ERR_ALREADY_ORDER": "❌ आपके पास पहले से एक ऑर्डर है!",
        "ERR_SINK_FULL": "🚨 सिंक भरा हुआ है! बर्तन धोएं!",
        "ERR_CLOSE_COUNTER": "🚫 काउंटर के पास जाएँ!",
        "ERR_NO_FOOD_SERVED": "❌ हम यह भोजन परोसते नहीं हैं!",
        "ERR_TRAY_FULL": "❌ ट्रे पूरी भरी है!",
        "ERR_NO_READY_FOOD": "📦 कोई भोजन तैयार नहीं है!",
        "ERR_CLOSE_SINK": "🚫 सिंक के पास जाएँ!",
        "TRAY_FULL": "ट्रे पूरी भरी है!",
        "SINK_FULL": "सिंक भरा हुआ है!",
        "NO_FOOD_READY": "कोई भोजन तैयार नहीं है",
        "COUNTER_OCCUPIED": "जगह व्यस्त है!",
        "MOVE_CLOSER_WASD": "WASD के साथ पास आएँ!",
        "MOVE_CLOSER_ARROWS": "तीर कुंजियों के साथ पास आएँ!",
        
        "MSG_ORDER_TAKEN": "📝 ऑर्डर लिया गया!",
        "MSG_ORDER_REC": "📝 ऑर्डर प्राप्त हुआ!",
        "MSG_SERVED": "🍽️ परोसा गया!",
        "MSG_TABLE_CLEARED": "🧹 टेबल साफ हो गई!",
        "MSG_TABLE_FREE": "🪑 टेबल खाली है",
        "FOOD_READY": "तैयार!",
        "FOOD_TAKEN": "ले लिया!",
        "TRICK_CLICKS": "🔑 ट्रिक:",
        "CLICKS_LEFT": "क्लिक...",
        "WASHING": "🧼 धुलाई जारी...",
        "WASH_CLEAN": "✨ बर्तन साफ!",
        "WASH_NONE": "🧼 कोई बर्तन नहीं",
        "LEAVING_ANGRY": "😡 जा रहा है!",
        "TABLE_SHORT": "टेबल",
        "PLATE_DEPOSITED": "🧹 प्लेट जमा की गई!",
        "DAY_STARTED": "🎉 दिन {level} शुरू हुआ!",
        "TABLE_OCCUPIED": "टेबल व्यस्त है",
        "ORDER_TAKEN": "ऑर्डर लिया गया!",
        "WASHING_PLATE": "🧹 प्लेट जमा की गई!",
        
        "TUTORIAL_TITLE": "🎯 ट्यूटोरियल - दिन 0",
        "TUTORIAL_STEP_1": "👋 स्वागत है, वेट्रेस!\nचलने के लिए WASD का उपयोग करें.\nऑर्डर लेने के लिए ग्राहक की टेबल पर जाएं।",
        "TUTORIAL_STEP_2": "📝 बहुत अच्छे! आपने ऑर्डर ले लिया।\nअब शेफ को ऑर्डर देने के लिए\nरसोई के काउंटर पर जाएं।",
        "TUTORIAL_STEP_3": "👨‍🍳 शेफ ने खाना बना दिया!\nखाना लेने के लिए काउंटर पर वापस जाएं\nऔर ग्राहक को परोसें।",
        "TUTORIAL_STEP_4": "🍽️ ग्राहक को परोस दिया!\nअब गंदी प्लेट लें\nऔर सिंक पर ले जाएं।",
        "TUTORIAL_STEP_5": "🧼 बहुत अच्छे!\nसिंक पर क्लिक करके बर्तन धोएं।\nट्यूटोरियल समाप्त!",
        "TUTORIAL_STEP_6": "🎉 ट्यूटोरियल पूरा हुआ!\n3 जीवन के साथ दिन 1 शुरू करें।",
        "TUTORIAL_TABLE": "🪑 ग्राहक की टेबल",
        "TUTORIAL_COUNTER": "🧑‍🍳 रसोई काउंटर",
        "TUTORIAL_SINK": "🚿 सिंक",
        "TUTORIAL_MSG": "📖 निर्देशों का पालन करें",
        "TUTORIAL_WAIT": "⏳ शेफ के पकाने की प्रतीक्षा करें...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ ट्यूटोरियल के तीरों का पालन करें!",
        
        "AI_CHAT_TITLE": "💬 {name} के साथ चैट",
        "AI_CHAT_GREETING": "नमस्ते! मैं कैसे मदद कर सकता हूँ?",
        "AI_CHAT_CLOSE": "चैट बंद करें",
        "AI_CHAT_SEND": "भेजें",
        "AI_CHAT_PLACEHOLDER": "एक संदेश लिखें...",
        "AI_CHAT_LOADING": "🤔 सोच रहा हूँ...",
        "AI_CHAT_ERROR": "⚠️ त्रुटि: बाद में पुनः प्रयास करें",
        "AI_CHAT_FALLBACK": "📝 मैं ऑफलाइन मोड में हूँ!",
        
        "RADIO_TITLE": "📻 रेडियो",
        "RADIO_PLAY": "▶ चलाएँ",
        "RADIO_STOP": "⏹ रोकें",
        "RADIO_NEXT": "⏭ अगला",
        "RADIO_ON": "📻 रेडियो चालू",
        "RADIO_OFF": "📻 रेडियो बंद",
        "RADIO_STATION_1": "🎵 गाना 1",
        "RADIO_STATION_2": "🎵 गाना 2",
        "RADIO_STATION_3": "🎵 गाना 3",
        
        "PHONE_RINGING": "📞 फोन बज रहा है!",
        "PHONE_ANSWER": "📞 उत्तर दें?",
        "PHONE_CALL": "📞 कॉल पर...",
        "PHONE_MESSAGE": "📱 नया संदेश!",
        "PHONE_DELIVERY": "📦 3 ग्राहकों में विशेष डिलीवरी!",
        
        "FOOD_PIZZA": "🍕 पिज़्ज़ा",
        "FOOD_PATATINE": "🍟 फ्रेंच फ्राइज़",
        "FOOD_PANINO": "🍔 बर्गर",
        "FOOD_RISOTTO": "🍚 रिसोट्टो",
        "FOOD_CAPONATA": "🍆 कैपोनाटा",
        "FOOD_CAFFE": "☕ कॉफ़ी",
        "FOOD_COLA": "🥤 कोला",
        "FOOD_ACQUA": "💧 पानी",
        "FOOD_BIRRA": "🍺 बियर",
        "FOOD_ARANCINA": "🧆 अरैंचिना",
        "FOOD_CASSATA": "🍰 कसाटा",
        "FOOD_CHINOTTO": "🥤 चिनोट्टो",
        "FOOD_CANNOLO": "🥐 कैनोलो",
        "FOOD_GINSENG": "☕ जिनसेंग"
    },
    "ko": {
        "GIOCA": "▶ 게임 시작",
        "IMPOSTAZIONI": "⚙ 설정",
        "CREDITI": "ℹ 크레딧",
        "TORNA": "↩ 메뉴로 돌아가기",
        "VAI A CASA": "🏠 집으로 가기",
        "GIORNO": "⭐ 일차",
        "INCASSO": "💰 수입:",
        "SERVITI": "👥 손님 수:",
        "VASSOIO": "📋 쟁반:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 싱크대",
        "PRONTO": "완성! 👨‍🍳",
        "OCCUPATO": "사용 중!",
        "LOADING": "로딩 중...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "웨이트리스 & 일상 시뮬레이터",
        "NOTEPAD_TITLE": "📝 주문서",
        "NOTEPAD_EMPTY": "메모장이 비어있음",
        "NOTEPAD_READY": "주문 받기 준비 완료",
        "NOTEPAD_TABLE": "테이블:",
        "DAY_COMPLETE": "⭐ 하루 완료! ⭐",
        "DAY_FAILED": "💀 영업 실패 💀",
        "DAY_FAILED_DESC": "화난 손님들 때문에 모든 생명을 잃었습니다!",
        "SAVINGS_LEFT": "💰 남은 저축액:",
        "DAYS_WORKED": "📅 일한 날짜:",
        "FURNITURE_BOUGHT": "🛋️ 구매한 가구:",
        "AUDIO_SETTINGS": "🔊 게임 사운드",
        "ACTIVE": "켜짐",
        "DISABLED": "꺼짐",
        "DIFFICULTY_LEVEL": "📊 난이도",
        "EASY": "쉬움",
        "NORMAL": "보통",
        "HARD": "어려움",
        "CONTROL_SYSTEM": "🎮 조작 방식",
        "KEYBOARD": "키보드:",
        "LANGUAGE_SELECT": "🌐 언어 / Language",
        "CREDITS_TITLE": "ℹ 개발진 크레딧",
        "CREDITS_IDEATION": "🎮 기획 & 개발",
        "CREDITS_SUPPORT": "🏠 지원",
        "CREDITS_GRAPHICS": "🎨 그래픽 & 애니메이션",
        "CREDITS_TECH": "🛠️ 사용 기술",
        "CREDITS_LICENSE": "📝 라이선스",
        "INTELLIGENZA ARTIFICIALE": "🧠 인공지능",
        
        "ERR_CLOSE_TABLE": "🚫 테이블에 더 가까이 가세요!",
        "ERR_ALREADY_ORDER": "❌ 이미 받아둔 주문이 있습니다!",
        "ERR_SINK_FULL": "🚨 싱크대가 가득 찼습니다! 설거지를 하세요!",
        "ERR_CLOSE_COUNTER": "🚫 카운터에 더 가까이 가세요!",
        "ERR_NO_FOOD_SERVED": "❌ 이 음식은 서빙할 수 없습니다!",
        "ERR_TRAY_FULL": "❌ 쟁반이 가득 찼습니다!",
        "ERR_NO_READY_FOOD": "📦 준비된 음식이 없습니다!",
        "ERR_CLOSE_SINK": "🚫 싱크대에 더 가까이 가세요!",
        "TRAY_FULL": "쟁반이 가득 찼습니다!",
        "SINK_FULL": "싱크대가 가득 찼습니다!",
        "NO_FOOD_READY": "준비된 음식이 없습니다",
        "COUNTER_OCCUPIED": "사용 중!",
        "MOVE_CLOSER_WASD": "WASD로 가까이 가세요!",
        "MOVE_CLOSER_ARROWS": "화살표 키로 가까이 가세요!",
        
        "MSG_ORDER_TAKEN": "📝 주문 접수!",
        "MSG_ORDER_REC": "📝 주문 완료!",
        "MSG_SERVED": "🍽️ 서빙 완료!",
        "MSG_TABLE_CLEARED": "🧹 테이블 정리 완료!",
        "MSG_TABLE_FREE": "🪑 빈 테이블",
        "FOOD_READY": "완성!",
        "FOOD_TAKEN": "픽업!",
        "TRICK_CLICKS": "🔑 치트:",
        "CLICKS_LEFT": "회 클릭...",
        "WASHING": "🧼 설거지 중...",
        "WASH_CLEAN": "✨ 접시가 깨끗해졌습니다!",
        "WASH_NONE": "🧼 설거지할 접시가 없습니다",
        "LEAVING_ANGRY": "😡 손님이 떠납니다!",
        "TABLE_SHORT": "테이블",
        "PLATE_DEPOSITED": "🧹 접시를 내려놓았습니다!",
        "DAY_STARTED": "🎉 {level}일차 시작!",
        "TABLE_OCCUPIED": "사용 중인 테이블",
        "ORDER_TAKEN": "주문 접수!",
        "WASHING_PLATE": "🧹 접시를 내려놓았습니다!",
        
        "TUTORIAL_TITLE": "🎯 튜토리얼 - 0일차",
        "TUTORIAL_STEP_1": "👋 웨이트리스님, 환영합니다!\n이동하려면 WASD를 사용하세요.\n주문을 받으려면 손님 테이블로 가세요.",
        "TUTORIAL_STEP_2": "📝 좋아요! 주문을 받았습니다.\n이제 주방 카운터로 가서\n셰프에게 주문을 전달하세요.",
        "TUTORIAL_STEP_3": "👨‍🍳 셰프가 요리했습니다!\n음식을 받으려면 카운터로 돌아가서\n손님에게 서빙하세요.",
        "TUTORIAL_STEP_4": "🍽️ 손님 서빙 완료!\n이제 더러운 접시를 가져다가\n싱크대에 가져다 놓으세요.",
        "TUTORIAL_STEP_5": "🧼 잘했어요!\n싱크대를 클릭하여 설거지를 하세요.\n튜토리얼이 끝났습니다!",
        "TUTORIAL_STEP_6": "🎉 튜토리얼 완료!\n3개의 생명으로 1일차를 시작하세요.",
        "TUTORIAL_TABLE": "🪑 손님 테이블",
        "TUTORIAL_COUNTER": "🧑‍🍳 주방 카운터",
        "TUTORIAL_SINK": "🚿 싱크대",
        "TUTORIAL_MSG": "📖 지침을 따르세요",
        "TUTORIAL_WAIT": "⏳ 셰프가 요리할 때까지 기다리세요...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ 튜토리얼 화살표를 따르세요!",
        
        "AI_CHAT_TITLE": "💬 {name}님과 채팅",
        "AI_CHAT_GREETING": "안녕하세요! 어떻게 도와드릴까요?",
        "AI_CHAT_CLOSE": "채팅 닫기",
        "AI_CHAT_SEND": "보내기",
        "AI_CHAT_PLACEHOLDER": "메시지를 입력하세요...",
        "AI_CHAT_LOADING": "🤔 생각 중...",
        "AI_CHAT_ERROR": "⚠️ 오류: 나중에 다시 시도하세요",
        "AI_CHAT_FALLBACK": "📝 오프라인 모드입니다!",
        
        "RADIO_TITLE": "📻 라디오",
        "RADIO_PLAY": "▶ 재생",
        "RADIO_STOP": "⏹ 정지",
        "RADIO_NEXT": "⏭ 다음",
        "RADIO_ON": "📻 라디오 켜짐",
        "RADIO_OFF": "📻 라디오 꺼짐",
        "RADIO_STATION_1": "🎵 노래 1",
        "RADIO_STATION_2": "🎵 노래 2",
        "RADIO_STATION_3": "🎵 노래 3",
        
        "PHONE_RINGING": "📞 전화가 울리고 있습니다!",
        "PHONE_ANSWER": "📞 받으시겠습니까?",
        "PHONE_CALL": "📞 통화 중...",
        "PHONE_MESSAGE": "📱 새 메시지!",
        "PHONE_DELIVERY": "📦 3명의 손님 후 특별 배송!",
        
        "FOOD_PIZZA": "🍕 피자",
        "FOOD_PATATINE": "🍟 감자튀김",
        "FOOD_PANINO": "🍔 버거",
        "FOOD_RISOTTO": "🍚 리조또",
        "FOOD_CAPONATA": "🍆 카포나타",
        "FOOD_CAFFE": "☕ 커피",
        "FOOD_COLA": "🥤 콜라",
        "FOOD_ACQUA": "💧 물",
        "FOOD_BIRRA": "🍺 맥주",
        "FOOD_ARANCINA": "🧆 아란치니",
        "FOOD_CASSATA": "🍰 카사타",
        "FOOD_CHINOTTO": "🥤 치노또",
        "FOOD_CANNOLO": "🥐 칸놀로",
        "FOOD_GINSENG": "☕ 인삼"
    },
    "zh": {
        "GIOCA": "▶ 开始游戏",
        "IMPOSTAZIONI": "⚙ 设置",
        "CREDITI": "ℹ 制作人员",
        "TORNA": "↩ 返回菜单",
        "VAI A CASA": "🏠 回家",
        "GIORNO": "⭐ 天",
        "INCASSO": "💰 收入:",
        "SERVITI": "👥 服务人数:",
        "VASSOIO": "📋 托盘:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 水槽",
        "PRONTO": "好了！ 👨‍🍳",
        "OCCUPATO": "位置已被占用！",
        "LOADING": "加载中...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "服务员与家庭生活模拟器",
        "NOTEPAD_TITLE": "📝 菜单",
        "NOTEPAD_EMPTY": "便签本为空",
        "NOTEPAD_READY": "准备点餐",
        "NOTEPAD_TABLE": "餐桌:",
        "DAY_COMPLETE": "⭐ 完成今日营业！ ⭐",
        "DAY_FAILED": "💀 营业失败 💀",
        "DAY_FAILED_DESC": "由于顾客生气，你失去了所有生命！",
        "SAVINGS_LEFT": "💰 剩余存款:",
        "DAYS_WORKED": "📅 工作天数:",
        "FURNITURE_BOUGHT": "🛋️ 已购家具:",
        "AUDIO_SETTINGS": "🔊 游戏音效",
        "ACTIVE": "开启",
        "DISABLED": "关闭",
        "DIFFICULTY_LEVEL": "📊 难度",
        "EASY": "简单",
        "NORMAL": "普通",
        "HARD": "困难",
        "CONTROL_SYSTEM": "🎮 控制方式",
        "KEYBOARD": "键盘:",
        "LANGUAGE_SELECT": "🌐 语言 / Language",
        "CREDITS_TITLE": "ℹ 开发者名单",
        "CREDITS_IDEATION": "🎮 策划与代码",
        "CREDITS_SUPPORT": "🏠 支持团队",
        "CREDITS_GRAPHICS": "🎨 美术与动画",
        "CREDITS_TECH": "🛠️ 技术支持",
        "CREDITS_LICENSE": "📝 许可证",
        "INTELLIGENZA ARTIFICIALE": "🧠 人工智能",
        
        "ERR_CLOSE_TABLE": "🚫 请靠近餐桌！",
        "ERR_ALREADY_ORDER": "❌ 你已经拿到了点菜单！",
        "ERR_SINK_FULL": "🚨 水槽满了！快去洗碗！",
        "ERR_CLOSE_COUNTER": "🚫 请靠近柜台！",
        "ERR_NO_FOOD_SERVED": "❌ 我们不上这道菜！",
        "ERR_TRAY_FULL": "❌ 托盘装满了！",
        "ERR_NO_READY_FOOD": "📦 没有准备好的食物！",
        "ERR_CLOSE_SINK": "🚫 请靠近水槽！",
        "TRAY_FULL": "托盘装满了！",
        "SINK_FULL": "水槽满了！",
        "NO_FOOD_READY": "没有准备好的食物",
        "COUNTER_OCCUPIED": "位置已被占用！",
        "MOVE_CLOSER_WASD": "请用WASD靠近！",
        "MOVE_CLOSER_ARROWS": "请用方向键靠近！",
        
        "MSG_ORDER_TAKEN": "📝 已记下点单！",
        "MSG_ORDER_REC": "📝 收到订单！",
        "MSG_SERVED": "🍽️ 上菜成功！",
        "MSG_TABLE_CLEARED": "🧹 餐桌已打扫！",
        "MSG_TABLE_FREE": "🪑 空桌",
        "FOOD_READY": "好了！",
        "FOOD_TAKEN": "已取走！",
        "TRICK_CLICKS": "🔑 秘籍:",
        "CLICKS_LEFT": "次点击...",
        "WASHING": "🧼 洗碗中...",
        "WASH_CLEAN": "✨ 碗碟已洗净！",
        "WASH_NONE": "🧼 没有脏碗",
        "LEAVING_ANGRY": "😡 顾客生性离开了！",
        "TABLE_SHORT": "桌",
        "PLATE_DEPOSITED": "🧹 盘子已放下！",
        "DAY_STARTED": "🎉 第{level}天开始！",
        "TABLE_OCCUPIED": "餐桌已占用",
        "ORDER_TAKEN": "已记下点单！",
        "WASHING_PLATE": "🧹 盘子已放下！",
        
        "TUTORIAL_TITLE": "🎯 教程 - 第0天",
        "TUTORIAL_STEP_1": "👋 欢迎，服务员！\n使用WASD移动。\n去顾客的餐桌接订单。",
        "TUTORIAL_STEP_2": "📝 很好！你接到了订单。\n现在去厨房柜台\n把订单交给厨师。",
        "TUTORIAL_STEP_3": "👨‍🍳 厨师做好了！\n回到柜台取食物\n并端给顾客。",
        "TUTORIAL_STEP_4": "🍽️ 顾客已服务！\n现在拿脏盘子\n并带到水槽。",
        "TUTORIAL_STEP_5": "🧼 做得好！\n点击水槽洗碗。\n教程结束了！",
        "TUTORIAL_STEP_6": "🎉 教程完成！\n用3条命开始第1天。",
        "TUTORIAL_TABLE": "🪑 顾客餐桌",
        "TUTORIAL_COUNTER": "🧑‍🍳 厨房柜台",
        "TUTORIAL_SINK": "🚿 水槽",
        "TUTORIAL_MSG": "📖 按照指示操作",
        "TUTORIAL_WAIT": "⏳ 等待厨师烹饪...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ 跟随教程箭头！",
        
        "AI_CHAT_TITLE": "💬 与{name}聊天",
        "AI_CHAT_GREETING": "你好！我能帮你什么吗？",
        "AI_CHAT_CLOSE": "关闭聊天",
        "AI_CHAT_SEND": "发送",
        "AI_CHAT_PLACEHOLDER": "输入消息...",
        "AI_CHAT_LOADING": "🤔 思考中...",
        "AI_CHAT_ERROR": "⚠️ 错误：请稍后重试",
        "AI_CHAT_FALLBACK": "📝 我处于离线模式！",
        
        "RADIO_TITLE": "📻 电台",
        "RADIO_PLAY": "▶ 播放",
        "RADIO_STOP": "⏹ 停止",
        "RADIO_NEXT": "⏭ 下一首",
        "RADIO_ON": "📻 电台已开",
        "RADIO_OFF": "📻 电台已关",
        "RADIO_STATION_1": "🎵 歌曲1",
        "RADIO_STATION_2": "🎵 歌曲2",
        "RADIO_STATION_3": "🎵 歌曲3",
        
        "PHONE_RINGING": "📞 电话响了！",
        "PHONE_ANSWER": "📞 接听？",
        "PHONE_CALL": "📞 通话中...",
        "PHONE_MESSAGE": "📱 新消息！",
        "PHONE_DELIVERY": "📦 3位顾客后有特别配送！",
        
        "FOOD_PIZZA": "🍕 披萨",
        "FOOD_PATATINE": "🍟 薯条",
        "FOOD_PANINO": "🍔 汉堡",
        "FOOD_RISOTTO": "🍚 炖饭",
        "FOOD_CAPONATA": "🍆 卡波纳塔",
        "FOOD_CAFFE": "☕ 咖啡",
        "FOOD_COLA": "🥤 可乐",
        "FOOD_ACQUA": "💧 水",
        "FOOD_BIRRA": "🍺 啤酒",
        "FOOD_ARANCINA": "🧆 阿兰奇尼",
        "FOOD_CASSATA": "🍰 卡萨塔",
        "FOOD_CHINOTTO": "🥤 奇诺托",
        "FOOD_CANNOLO": "🥐 卡诺里",
        "FOOD_GINSENG": "☕ 人参茶"
    },
    "ar": {
        "GIOCA": "▶ ابدأ اللعب",
        "IMPOSTAZIONI": "⚙ الإعدادات",
        "CREDITI": "ℹ فريق التطوير",
        "TORNA": "↩ العودة إلى القائمة",
        "VAI A CASA": "🏠 اذهب إلى المنزل",
        "GIORNO": "⭐ اليوم",
        "INCASSO": "💰 الأرباح:",
        "SERVITI": "👥 عدد الزبائن:",
        "VASSOIO": "📋 الصينية:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 المغسلة",
        "PRONTO": "جاهز! 👨‍🍳",
        "OCCUPATO": "المكان مشغول!",
        "LOADING": "جارٍ التحميل...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "محاكاة النادلة والحياة المنزلية",
        "NOTEPAD_TITLE": "📝 الطلبات",
        "NOTEPAD_EMPTY": "المفكرة فارغة",
        "NOTEPAD_READY": "جاهز لتسجيل الطلب",
        "NOTEPAD_TABLE": "الطاولة:",
        "DAY_COMPLETE": "⭐ تم إنهاء اليوم! ⭐",
        "DAY_FAILED": "💀 فشل اليوم 💀",
        "DAY_FAILED_DESC": "لقد خسرت كل الأرواح بسبب غضب الزبائن!",
        "SAVINGS_LEFT": "💰 المدخرات المتبقية:",
        "DAYS_WORKED": "📅 أيام العمل:",
        "FURNITURE_BOUGHT": "🛋️ الأثاث المُشترى:",
        "AUDIO_SETTINGS": "🔊 صوت اللعبة",
        "ACTIVE": "مفعل",
        "DISABLED": "معطل",
        "DIFFICULTY_LEVEL": "📊 مستوى الصعوبة",
        "EASY": "سهل",
        "NORMAL": "عادي",
        "HARD": "صعب",
        "CONTROL_SYSTEM": "🎮 نظام التحكم",
        "KEYBOARD": "لوحة المفاتيح:",
        "LANGUAGE_SELECT": "🌐 اللغة / Language",
        "CREDITS_TITLE": "ℹ فريق التطوير",
        "CREDITS_IDEATION": "🎮 الفكرة والبرمجة الأصلية",
        "CREDITS_SUPPORT": "🏠 بدعم من",
        "CREDITS_GRAPHICS": "🎨 الرسوميات والأنيميشن",
        "CREDITS_TECH": "🛠️ التقنيات المستخدمة",
        "CREDITS_LICENSE": "📝 الترخيص",
        "INTELLIGENZA ARTIFICIALE": "🧠 الذكاء الاصطناعي",
        
        "ERR_CLOSE_TABLE": "🚫 اقترب من الطاولة!",
        "ERR_ALREADY_ORDER": "❌ لديك طلب مسجل بالفعل!",
        "ERR_SINK_FULL": "🚨 المغسلة ممتلئة! اغسل الأطباق!",
        "ERR_CLOSE_COUNTER": "🚫 اقترب من الطاولة!",
        "ERR_NO_FOOD_SERVED": "❌ لا نقدّم هذا الطبق!",
        "ERR_TRAY_FULL": "❌ الصينية ممتلئة!",
        "ERR_NO_READY_FOOD": "📦 لا يوجد طعام جاهز!",
        "ERR_CLOSE_SINK": "🚫 اقترب من المغسلة!",
        "TRAY_FULL": "الصينية ممتلئة!",
        "SINK_FULL": "المغسلة ممتلئة!",
        "NO_FOOD_READY": "لا يوجد طعام جاهز",
        "COUNTER_OCCUPIED": "المكان مشغول!",
        "MOVE_CLOSER_WASD": "اقترب باستخدام WASD!",
        "MOVE_CLOSER_ARROWS": "اقترب باستخدام الأسهم!",
        
        "MSG_ORDER_TAKEN": "📝 تم تسجيل الطلب!",
        "MSG_ORDER_REC": "📝 تم استلام الطلب!",
        "MSG_SERVED": "🍽️ تم التقديم!",
        "MSG_TABLE_CLEARED": "🧹 تم تنظيف الطاولة!",
        "MSG_TABLE_FREE": "🪑 الطاولة فارغة",
        "FOOD_READY": "جاهز!",
        "FOOD_TAKEN": "تم أخذه!",
        "TRICK_CLICKS": "🔑 الخدعة:",
        "CLICKS_LEFT": "نقرات...",
        "WASHING": "🧼 جارٍ الغسل...",
        "WASH_CLEAN": "✨ الأطباق نظيفة!",
        "WASH_NONE": "🧼 لا توجد أطباق",
        "LEAVING_ANGRY": "😡 يغادر غاضبًا!",
        "TABLE_SHORT": "طاولة",
        "PLATE_DEPOSITED": "🧹 تم وضع الطبق!",
        "DAY_STARTED": "🎉 بدأ اليوم {level}!",
        "TABLE_OCCUPIED": "الطاولة مشغولة",
        "ORDER_TAKEN": "تم تسجيل الطلب!",
        "WASHING_PLATE": "🧹 تم وضع الطبق!",
        
        "TUTORIAL_TITLE": "🎯 البرنامج التعليمي - اليوم 0",
        "TUTORIAL_STEP_1": "👋 مرحباً، نادلة!\nاستخدم WASD للتحرك.\nاذهب إلى طاولة الزبون لتسجيل الطلب.",
        "TUTORIAL_STEP_2": "📝 ممتاز! لقد سجلت الطلب.\nالآن اذهب إلى منضدة المطبخ\nلتسليم الطلب إلى الشيف.",
        "TUTORIAL_STEP_3": "👨‍🍳 لقد طهى الشيف!\nعد إلى المنضدة لأخذ الطعام\nوتقديمه للزبون.",
        "TUTORIAL_STEP_4": "🍽️ تم تقديم الطعام للزبون!\nالآن خذ الطبق المتسخ\nواذهب به إلى المغسلة.",
        "TUTORIAL_STEP_5": "🧼 أحسنت!\nاغسل الأطباق بالضغط على المغسلة.\nانتهى البرنامج التعليمي!",
        "TUTORIAL_STEP_6": "🎉 اكتمل البرنامج التعليمي!\nابدأ اليوم الأول بـ 3 أرواح.",
        "TUTORIAL_TABLE": "🪑 طاولة الزبون",
        "TUTORIAL_COUNTER": "🧑‍🍳 منضدة المطبخ",
        "TUTORIAL_SINK": "🚿 المغسلة",
        "TUTORIAL_MSG": "📖 اتبع التعليمات",
        "TUTORIAL_WAIT": "⏳ انتظر حتى يطهو الشيف...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ اتبع أسهم البرنامج التعليمي!",
        
        "AI_CHAT_TITLE": "💬 محادثة مع {name}",
        "AI_CHAT_GREETING": "مرحباً! كيف يمكنني مساعدتك؟",
        "AI_CHAT_CLOSE": "إغلاق المحادثة",
        "AI_CHAT_SEND": "إرسال",
        "AI_CHAT_PLACEHOLDER": "اكتب رسالة...",
        "AI_CHAT_LOADING": "🤔 جاري التفكير...",
        "AI_CHAT_ERROR": "⚠️ خطأ: حاول مرة أخرى لاحقاً",
        "AI_CHAT_FALLBACK": "📝 أنا في وضع عدم الاتصال!",
        
        "RADIO_TITLE": "📻 الراديو",
        "RADIO_PLAY": "▶ تشغيل",
        "RADIO_STOP": "⏹ إيقاف",
        "RADIO_NEXT": "⏭ التالي",
        "RADIO_ON": "📻 الراديو قيد التشغيل",
        "RADIO_OFF": "📻 الراديو متوقف",
        "RADIO_STATION_1": "🎵 أغنية 1",
        "RADIO_STATION_2": "🎵 أغنية 2",
        "RADIO_STATION_3": "🎵 أغنية 3",
        
        "PHONE_RINGING": "📞 الهاتف يرن!",
        "PHONE_ANSWER": "📞 تردين؟",
        "PHONE_CALL": "📞 في مكالمة...",
        "PHONE_MESSAGE": "📱 رسالة جديدة!",
        "PHONE_DELIVERY": "📦 توصيل خاص بعد 3 زبائن!",
        
        "FOOD_PIZZA": "🍕 بيتزا",
        "FOOD_PATATINE": "🍟 بطاطس مقلية",
        "FOOD_PANINO": "🍔 برجر",
        "FOOD_RISOTTO": "🍚 ريزوتو",
        "FOOD_CAPONATA": "🍆 كابوناتا",
        "FOOD_CAFFE": "☕ قهوة",
        "FOOD_COLA": "🥤 كولا",
        "FOOD_ACQUA": "💧 ماء",
        "FOOD_BIRRA": "🍺 بيرة",
        "FOOD_ARANCINA": "🧆 أرانشيني",
        "FOOD_CASSATA": "🍰 كاساتا",
        "FOOD_CHINOTTO": "🥤 شينوتو",
        "FOOD_CANNOLO": "🥐 كانولو",
        "FOOD_GINSENG": "☕ جينسنغ"
    },
    "haw": {
        "GIOCA": "▶ PĀʻANI",
        "IMPOSTAZIONI": "⚙ HŌʻIKE",
        "CREDITI": "ℹ GOʻI",
        "TORNA": "↩ HOʻOPIʻI I KA PAPA KOE",
        "VAI A CASA": "🏠 HOʻI I KA HALE",
        "GIORNO": "⭐ Lā",
        "INCASSO": "💰 Kālā:",
        "SERVITI": "👥 Mākaukau:",
        "VASSOIO": "📋 Pā pālahalaha:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 KINI",
        "PRONTO": "Mākaukau! 👨‍🍳",
        "OCCUPATO": "Ua paʻa ka wahi!",
        "LOADING": "Hoʻouka nei...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATOR O KA WAHINE HĀNAI ME KA HALE",
        "NOTEPAD_TITLE": "📝 PALAPALA KAUOHA",
        "NOTEPAD_EMPTY": "Puke hāmama",
        "NOTEPAD_READY": "Mākaukau no nā kauoha",
        "NOTEPAD_TABLE": "Pākaukau:",
        "DAY_COMPLETE": "⭐ LĀ UA PAʻA! ⭐",
        "DAY_FAILED": "💀 HOʻOPAI LĀ 💀",
        "DAY_FAILED_DESC": "Ua pau nā ola i nā keiki huhū!",
        "SAVINGS_LEFT": "💰 Kālā i toe:",
        "DAYS_WORKED": "📅 Nā lā hana:",
        "FURNITURE_BOUGHT": "🛋️ Nā pūnana hou:",
        "AUDIO_SETTINGS": "🔊 Leo pāʻani",
        "ACTIVE": "HANA",
        "DISABLED": "AʻOLE HANA",
        "DIFFICULTY_LEVEL": "📊 Pae Hiki",
        "EASY": "WALE",
        "NORMAL": "MAʻAMAU",
        "HARD": "NUI",
        "CONTROL_SYSTEM": "🎮 Nā Mana",
        "KEYBOARD": "PĀPAʻI PĀKAUKAU:",
        "LANGUAGE_SELECT": "🌐 ʻŌlelo / Language",
        "CREDITS_TITLE": "ℹ NĀ KANAKA HAKU",
        "CREDITS_IDEATION": "🎮 MANAʻO A ME KA HAKU",
        "CREDITS_SUPPORT": "🏠 KŌKUA",
        "CREDITS_GRAPHICS": "🎨 KII A ME ANIMA",
        "CREDITS_TECH": "🛠️ ʻENEKINI",
        "CREDITS_LICENSE": "📝 PALAAPALA",
        "INTELLIGENZA ARTIFICIALE": "🧠 NAʻAUAO HANA",
        
        "ERR_CLOSE_TABLE": "🚫 E hoʻokokoke i ka pākaukau!",
        "ERR_ALREADY_ORDER": "❌ He kauoha kāu!",
        "ERR_SINK_FULL": "🚨 Ua piha ka kini! Umi i nā pā!",
        "ERR_CLOSE_COUNTER": "🚫 E hoʻokokoke i ka papa!",
        "ERR_NO_FOOD_SERVED": "❌ ʻAʻole mākou e hāʻawi i kēia!",
        "ERR_TRAY_FULL": "❌ Ua piha ka pā!",
        "ERR_NO_READY_FOOD": "📦 ʻAʻole meʻai mākaukau!",
        "ERR_CLOSE_SINK": "🚫 E hoʻokokoke i ka kini!",
        "TRAY_FULL": "Ua piha ka pā!",
        "SINK_FULL": "Ua piha ka kini!",
        "NO_FOOD_READY": "ʻAʻole meʻai mākaukau",
        "COUNTER_OCCUPIED": "Ua paʻa ka wahi!",
        "MOVE_CLOSER_WASD": "E hoʻokokoke me WASD!",
        "MOVE_CLOSER_ARROWS": "E hoʻokokoke me nā ʻōpala!",
        
        "MSG_ORDER_TAKEN": "📝 Ua skū i ka kauoha!",
        "MSG_ORDER_REC": "📝 Ua loaʻa ka kauoha!",
        "MSG_SERVED": "🍽️ Ua hāʻawi ʻia!",
        "MSG_TABLE_CLEARED": "🧹 Ua hāʻalele i ka pākaukau!",
        "MSG_TABLE_FREE": "🪑 Pākaukau hāmama",
        "FOOD_READY": "mākaukau!",
        "FOOD_TAKEN": "ua lawe ʻia!",
        "TRICK_CLICKS": "🔑 Kī secret:",
        "CLICKS_LEFT": "kaomi...",
        "WASHING": "🧼 Umi nei...",
        "WASH_CLEAN": "✨ Maʻemaʻe nā pā!",
        "WASH_NONE": "🧼 ʻAʻole pā",
        "LEAVING_ANGRY": "😡 Ua hele huhū!",
        "TABLE_SHORT": "Pā.",
        "PLATE_DEPOSITED": "🧹 Ua waiho ʻia ka pā!",
        "DAY_STARTED": "🎉 Ua hoʻomaka ka Lā {level}!",
        "TABLE_OCCUPIED": "Pākaukau paʻa",
        "ORDER_TAKEN": "Ua skū ka kauoha!",
        "WASHING_PLATE": "🧹 Ua waiho ʻia ka pā!",
        
        "TUTORIAL_TITLE": "🎯 AʻO - LĀ 0",
        "TUTORIAL_STEP_1": "👋 Welina mai, Wahine Hānai!\nE hoʻohana i WASD no ka neʻe ʻana.\nE hele i ka pākaukau o ka mea kūʻai e kiʻi i ke kauoha.",
        "TUTORIAL_STEP_2": "📝 Maikaʻi! Ua kiʻi ʻoe i ke kauoha.\nI kēia manawa, e hele i ka pā kuke\ne hāʻawi i ka Chef.",
        "TUTORIAL_STEP_3": "👨‍🍳 Ua kuke ka Chef!\nE hoʻi i ka pā e lawe i ka meʻai\na e hāʻawi i ka mea kūʻai.",
        "TUTORIAL_STEP_4": "🍽️ Ua hāʻawi ʻia i ka mea kūʻai!\nI kēia manawa, e lawe i ka pā lepo\na e lawe i ka kini.",
        "TUTORIAL_STEP_5": "🧼 Hana maikaʻi!\nE umi i nā pā ma ke kaomi ʻana i ka kini.\nUa pau ke aʻo!",
        "TUTORIAL_STEP_6": "🎉 Ua pau ke aʻo!\nE hoʻomaka i ka Lā 1 me 3 ola.",
        "TUTORIAL_TABLE": "🪑 Pākaukau o ka Mea Kūʻai",
        "TUTORIAL_COUNTER": "🧑‍🍳 Pā Kuke",
        "TUTORIAL_SINK": "🚿 Kini",
        "TUTORIAL_MSG": "📖 E hahai i nā ʻōlelo kuhikuhi",
        "TUTORIAL_WAIT": "⏳ E kali i ka Chef e kuke...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ E hahai i nā ʻōpala o ke aʻo!",
        
        "AI_CHAT_TITLE": "💬 Kūkākūkā me {name}",
        "AI_CHAT_GREETING": "Aloha! Pehea wau e kōkua ai?",
        "AI_CHAT_CLOSE": "Pani i ke kūkākūkā",
        "AI_CHAT_SEND": "Hoʻouna",
        "AI_CHAT_PLACEHOLDER": "E kākau i kahi leka...",
        "AI_CHAT_LOADING": "🤔 Ke noʻonoʻo nei...",
        "AI_CHAT_ERROR": "⚠️ Hapa: e hoʻāʻo hou ma hope",
        "AI_CHAT_FALLBACK": "📝 Aia wau ma ke ʻano pili ʻole!",
        
        "RADIO_TITLE": "📻 Lekiō",
        "RADIO_PLAY": "▶ Hoʻokani",
        "RADIO_STOP": "⏹ Hoʻōki",
        "RADIO_NEXT": "⏭ Aʻe",
        "RADIO_ON": "📻 Lekiō Paʻa",
        "RADIO_OFF": "📻 Lekiō Pau",
        "RADIO_STATION_1": "🎵 Mele 1",
        "RADIO_STATION_2": "🎵 Mele 2",
        "RADIO_STATION_3": "🎵 Mele 3",
        
        "PHONE_RINGING": "📞 Ke kani nei ke kelepona!",
        "PHONE_ANSWER": "📞 E pane?",
        "PHONE_CALL": "📞 Ke kamaʻilio nei...",
        "PHONE_MESSAGE": "📱 He leka hou!",
        "PHONE_DELIVERY": "📦 Hoʻouna kūikawā ma hope o 3 mau mea kūʻai!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Palai",
        "FOOD_PANINO": "🍔 Burger",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Caponata",
        "FOOD_CAFFE": "☕ Kope",
        "FOOD_COLA": "🥤 Kola",
        "FOOD_ACQUA": "💧 Wai",
        "FOOD_BIRRA": "🍺 Pia",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "me": {
        "GIOCA": "▶ IGRAJ",
        "IMPOSTAZIONI": "⚙ PODEŠAVANJA",
        "CREDITI": "ℹ KREDITI",
        "TORNA": "↩ NAZAD U MENI",
        "VAI A CASA": "🏠 IDI KUĆI",
        "GIORNO": "⭐ Dan",
        "INCASSO": "💰 Zarada:",
        "SERVITI": "👥 Posluženi:",
        "VASSOIO": "📋 Poslužavnik:",
        "PIATTI": "🍽️",
        "LAVELLO": "🚿 SUDOPER",
        "PRONTO": "Spremno! 👨‍🍳",
        "OCCUPATO": "Stanica zauzeta!",
        "LOADING": "Učitavanje...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATOR KONOBARICE & KUĆNOG ŽIVOTA",
        "NOTEPAD_TITLE": "📝 PORUDŽBINA",
        "NOTEPAD_EMPTY": "Prazna sveska",
        "NOTEPAD_READY": "Spremno za porudžbine",
        "NOTEPAD_TABLE": "Sto:",
        "DAY_COMPLETE": "⭐ DAN ZAVRŠEN! ⭐",
        "DAY_FAILED": "💀 DAN NEUSPJEŠAN 💀",
        "DAY_FAILED_DESC": "Izgubio si sve živote zbog ljutih gostiju!",
        "SAVINGS_LEFT": "💰 Preostala ušteđevina:",
        "DAYS_WORKED": "📅 Radnih dana:",
        "FURNITURE_BOUGHT": "🛋️ Kupljeni namještaj:",
        "AUDIO_SETTINGS": "🔊 Zvuk igre",
        "ACTIVE": "AKTIVNO",
        "DISABLED": "ISKLJUČENO",
        "DIFFICULTY_LEVEL": "📊 Nivo težine",
        "EASY": "LAKO",
        "NORMAL": "NORMALNO",
        "HARD": "TEŠKO",
        "CONTROL_SYSTEM": "🎮 Sistem kontrola",
        "KEYBOARD": "TASTATURA:",
        "LANGUAGE_SELECT": "🌐 Jezik / Language",
        "CREDITS_TITLE": "ℹ KREDITI RAZVOJA",
        "CREDITS_IDEATION": "🎮 IDEJA & ORIGINALNI KOD",
        "CREDITS_SUPPORT": "🏠 UZ PODRŠKU",
        "CREDITS_GRAPHICS": "🎨 GRAFIKA & ANIMACIJE",
        "CREDITS_TECH": "🛠️ INTEGRISANE TEHNOLOGIJE",
        "CREDITS_LICENSE": "📝 LICENCA",
        "INTELLIGENZA ARTIFICIALE": "🧠 VJEŠTAČKA INTELIGENCIJA",
        
        "ERR_CLOSE_TABLE": "🚫 Priđi stolu!",
        "ERR_ALREADY_ORDER": "❌ Već imaš porudžbinu!",
        "ERR_SINK_FULL": "🚨 Sudoper pun! Operi posuđe!",
        "ERR_CLOSE_COUNTER": "🚫 Priđi pultu!",
        "ERR_NO_FOOD_SERVED": "❌ Ne služimo ovo jelo!",
        "ERR_TRAY_FULL": "❌ Poslužavnik pun!",
        "ERR_NO_READY_FOOD": "📦 Nema spremnog jela!",
        "ERR_CLOSE_SINK": "🚫 Priđi sudoperu!",
        "TRAY_FULL": "Poslužavnik pun!",
        "SINK_FULL": "Sudoper pun!",
        "NO_FOOD_READY": "Nema spremnog jela",
        "COUNTER_OCCUPIED": "Stanica zauzeta!",
        "MOVE_CLOSER_WASD": "Priđi sa WASD!",
        "MOVE_CLOSER_ARROWS": "Priđi sa Strelicama!",
        
        "MSG_ORDER_TAKEN": "📝 Porudžbina zapisana!",
        "MSG_ORDER_REC": "📝 Porudžbina primljena!",
        "MSG_SERVED": "🍽️ Posluženo!",
        "MSG_TABLE_CLEARED": "🧹 Sto očišćen!",
        "MSG_TABLE_FREE": "🪑 Sto slobodan",
        "FOOD_READY": "spremno!",
        "FOOD_TAKEN": "uzeto!",
        "TRICK_CLICKS": "🔑 Trik:",
        "CLICKS_LEFT": "klikova...",
        "WASHING": "🧼 Pranje...",
        "WASH_CLEAN": "✨ Posuđe čisto!",
        "WASH_NONE": "🧼 Nema posuđa",
        "LEAVING_ANGRY": "😡 Odlazi!",
        "TABLE_SHORT": "Sto.",
        "PLATE_DEPOSITED": "🧹 Tanjir odložen!",
        "DAY_STARTED": "🎉 DAN {level} ZAPOČEO!",
        "TABLE_OCCUPIED": "Sto zauzet",
        "ORDER_TAKEN": "Porudžbina primljena!",
        "WASHING_PLATE": "🧹 Tanjir odložen!",
        
        "TUTORIAL_TITLE": "🎯 TUTORIJAL - DAN 0",
        "TUTORIAL_STEP_1": "👋 Dobrodošla, Konobarice!\nKoristi WASD za kretanje.\nIdi do stola gosta da preuzmeš porudžbinu.",
        "TUTORIAL_STEP_2": "📝 Odlično! Preuzela si porudžbinu.\nSada idi do pulta u kuhinji\nda je predaš Chef-u.",
        "TUTORIAL_STEP_3": "👨‍🍳 Chef je skuvao!\nVrati se do pulta da preuzmeš hranu\ni posluži gosta.",
        "TUTORIAL_STEP_4": "🍽️ Gost poslužen!\nSada uzmi prljavi tanjir\ni odnesi ga do sudopera.",
        "TUTORIAL_STEP_5": "🧼 Odlično!\nOperi posuđe klikom na sudoper.\nTutorijal je završen!",
        "TUTORIAL_STEP_6": "🎉 Tutorijal završen!\nZapočni Dan 1 sa 3 života.",
        "TUTORIAL_TABLE": "🪑 Sto Gosta",
        "TUTORIAL_COUNTER": "🧑‍🍳 Kuhinjski Pult",
        "TUTORIAL_SINK": "🚿 Sudoper",
        "TUTORIAL_MSG": "📖 Prati uputstva",
        "TUTORIAL_WAIT": "⏳ Sačekaj da Chef skuva...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Prati strelice tutorijala!",
        
        "AI_CHAT_TITLE": "💬 Chat sa {name}",
        "AI_CHAT_GREETING": "Zdravo! Kako mogu pomoći?",
        "AI_CHAT_CLOSE": "Zatvori chat",
        "AI_CHAT_SEND": "Pošalji",
        "AI_CHAT_PLACEHOLDER": "Napiši poruku...",
        "AI_CHAT_LOADING": "🤔 Razmišljam...",
        "AI_CHAT_ERROR": "⚠️ Greška: pokušaj ponovo kasnije",
        "AI_CHAT_FALLBACK": "📝 U offline modu sam!",
        
        "RADIO_TITLE": "📻 Radio",
        "RADIO_PLAY": "▶ Pusti",
        "RADIO_STOP": "⏹ Zaustavi",
        "RADIO_NEXT": "⏭ Sljedeća",
        "RADIO_ON": "📻 Radio Uključen",
        "RADIO_OFF": "📻 Radio Isključen",
        "RADIO_STATION_1": "🎵 Pjesma 1",
        "RADIO_STATION_2": "🎵 Pjesma 2",
        "RADIO_STATION_3": "🎵 Pjesma 3",
        
        "PHONE_RINGING": "📞 Telefon zvoni!",
        "PHONE_ANSWER": "📞 Odgovori?",
        "PHONE_CALL": "📞 U razgovoru...",
        "PHONE_MESSAGE": "📱 Nova poruka!",
        "PHONE_DELIVERY": "📦 Specijalna dostava za 3 gosta!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Pomfrit",
        "FOOD_PANINO": "🍔 Burger",
        "FOOD_RISOTTO": "🍚 Rizoto",
        "FOOD_CAPONATA": "🍆 Kaponata",
        "FOOD_CAFFE": "☕ Kafa",
        "FOOD_COLA": "🥤 Kola",
        "FOOD_ACQUA": "💧 Voda",
        "FOOD_BIRRA": "🍺 Pivo",
        "FOOD_ARANCINA": "🧆 Arančina",
        "FOOD_CASSATA": "🍰 Kasata",
        "FOOD_CHINOTTO": "🥤 Kinoto",
        "FOOD_CANNOLO": "🥐 Kanolo",
        "FOOD_GINSENG": "☕ Ginseng"
    },
    "ku": {
        "GIOCA": "▶ LÎSTIN",
        "IMPOSTAZIONI": "⚙ MÎHENG",
        "CREDITI": "ℹ KREDÎT",
        "TORNA": "↩ VEGERE MENU",
        "VAI A CASA": "🏠 HER MALÊ",
        "GIORNO": "⭐ Roj",
        "INCASSO": "💰 Hatin:",
        "SERVITI": "👥 Xizmetkirî:",
        "VASSOIO": "📋 Sînî:",
        "PIATTI": "🍽️ Qedeh",
        "LAVELLO": "🚿 LAVABO",
        "PRONTO": "Amade! 👨‍🍳",
        "OCCUPATO": "Cih tije ye!",
        "LOADING": "Tê barkirin...",
        "MENU_TITLE": "🍽️ WAITRESS SIMULATOR",
        "MENU_SUBTITLE": "SIMULATORA XIZMETKARÊ & JIYANA MALÊ",
        "NOTEPAD_TITLE": "📝 FERMAN",
        "NOTEPAD_EMPTY": "Defter vala ye",
        "NOTEPAD_READY": "Amade ji bo fermanan",
        "NOTEPAD_TABLE": "Masê:",
        "DAY_COMPLETE": "⭐ ROJ QEDÎ HAT! ⭐",
        "DAY_FAILED": "💀 ROJ TÊK ÇÛ 💀",
        "DAY_FAILED_DESC": "Hemû jiyan ji ber mêşterên birîndar wenda kirî!",
        "SAVINGS_LEFT": "💰 Perê mayî:",
        "DAYS_WORKED": "📅 Rojên kar kirî:",
        "FURNITURE_BOUGHT": "🛋️ Amûrên kirî:",
        "AUDIO_SETTINGS": "🔊 Dengê lîstikê",
        "ACTIVE": "ÇALAK",
        "DISABLED": "NEÇALAK",
        "DIFFICULTY_LEVEL": "📊 Asta Sûrî",
        "EASY": "HESAN",
        "NORMAL": "NORMAL",
        "HARD": "ZEHÊ",
        "CONTROL_SYSTEM": "🎮 Pergala kontrolê",
        "KEYBOARD": "KLAVYE:",
        "LANGUAGE_SELECT": "🌐 Ziman / Language",
        "CREDITS_TITLE": "ℹ KREDÎTÊ PÊŞDEÇÛNÊ",
        "CREDITS_IDEATION": "🎮 RAGIHANDIN & KODA ORJÎNAL",
        "CREDITS_SUPPORT": "🏠 BI PIŞTGIRIYA",
        "CREDITS_GRAPHICS": "🎨 GRAFÎK & ANÎMASYON",
        "CREDITS_TECH": "🛠️ TEKNOLOJÎYÊ TÊKILDAR",
        "CREDITS_LICENSE": "📝 LÎSANS",
        "INTELLIGENZA ARTIFICIALE": "🧠 HÎŞÊ ÇÊKIRÎ",
        
        "ERR_CLOSE_TABLE": "🚫 Nêzîkî masê bibe!",
        "ERR_ALREADY_ORDER": "❌ Tu jixwe fermanek heye!",
        "ERR_SINK_FULL": "🚨 Lavabo tije ye! Qedehê paqij bike!",
        "ERR_CLOSE_COUNTER": "🚫 Nêzîkî kontwarê bibe!",
        "ERR_NO_FOOD_SERVED": "❌ Em vê xwarinê naxizmin!",
        "ERR_TRAY_FULL": "❌ Sînî tije ye!",
        "ERR_NO_READY_FOOD": "📦 Xwarinê amade tune!",
        "ERR_CLOSE_SINK": "🚫 Nêzîkî lavabo bibe!",
        "TRAY_FULL": "Sînî tije ye!",
        "SINK_FULL": "Lavabo tije ye!",
        "NO_FOOD_READY": "Xwarinê amade tune",
        "COUNTER_OCCUPIED": "Cih tije ye!",
        "MOVE_CLOSER_WASD": "Bi WASD nêzîk bibe!",
        "MOVE_CLOSER_ARROWS": "Bi Tîran nêzîk bibe!",
        
        "MSG_ORDER_TAKEN": "📝 Ferman hat nivîsîn!",
        "MSG_ORDER_REC": "📝 Ferman hat stendin!",
        "MSG_SERVED": "🍽️ Xizmet kirî!",
        "MSG_TABLE_CLEARED": "🧹 Masê paqij kirî!",
        "MSG_TABLE_FREE": "🪑 Masê vala ye",
        "FOOD_READY": "amade!",
        "FOOD_TAKEN": "hate stendin!",
        "TRICK_CLICKS": "🔑 Hîle:",
        "CLICKS_LEFT": "klik...",
        "WASHING": "🧼 Tê paqijkirin...",
        "WASH_CLEAN": "✨ Qedeh paqij!",
        "WASH_NONE": "🧼 Qedeh tune",
        "LEAVING_ANGRY": "😡 Dikeve derve!",
        "TABLE_SHORT": "Mas.",
        "PLATE_DEPOSITED": "🧹 Qedeh hat danîn!",
        "DAY_STARTED": "🎉 ROJA {level} DESTPÊ KIR!",
        "TABLE_OCCUPIED": "Masê tije ye",
        "ORDER_TAKEN": "Ferman hat stendin!",
        "WASHING_PLATE": "🧹 Qedeh hat danîn!",
        
        "TUTORIAL_TITLE": "🎯 TALÎMÎ - ROJA 0",
        "TUTORIAL_STEP_1": "👋 Bi xêr hatî, Xizmetkar!\nWASD bikar bîne ji bo tevgerê.\nJi bo fermanê here masê mêşterê.",
        "TUTORIAL_STEP_2": "📝 Baş e! Te ferman stend.\nNiha here kontwarê mitbexê\nda fermanê bide Şef.",
        "TUTORIAL_STEP_3": "👨‍🍳 Şef çêkir!\nVegere kontwarê ji bo xwarinê bistînî\nû bide mêşter.",
        "TUTORIAL_STEP_4": "🍽️ Mêşter hate xizmetkirin!\nNiha qedeha pîs bigire\nû bibe lavabo.",
        "TUTORIAL_STEP_5": "🧼 Baş e!\nBi tikandina li ser lavabo qedehan paqij bike.\nTalîmî qediya!",
        "TUTORIAL_STEP_6": "🎉 Talîmî qediya!\nRoja 1 bi 3 jiyan destpê bike.",
        "TUTORIAL_TABLE": "🪑 Maseya Mêşter",
        "TUTORIAL_COUNTER": "🧑‍🍳 Kontwarê Mitbexê",
        "TUTORIAL_SINK": "🚿 Lavabo",
        "TUTORIAL_MSG": "📖 Li rêberiyê bike",
        "TUTORIAL_WAIT": "⏳ Bisekine heta Şef çêdike...",
        "TUTORIAL_FOLLOW_ARROWS": "⚠️ Li tîrên talîmî bike!",
        
        "AI_CHAT_TITLE": "💬 Axaftin bi {name} re",
        "AI_CHAT_GREETING": "Silav! Ez çawa dikarim alîkarî bikim?",
        "AI_CHAT_CLOSE": "Axaftinê bigire",
        "AI_CHAT_SEND": "Bişîne",
        "AI_CHAT_PLACEHOLDER": "Peyamek binivîse...",
        "AI_CHAT_LOADING": "🤔 Difikirim...",
        "AI_CHAT_ERROR": "⚠️ Çewtî: paşê dîsa biceribîne",
        "AI_CHAT_FALLBACK": "📝 Ez di moda offline de me!",
        
        "RADIO_TITLE": "📻 Radyo",
        "RADIO_PLAY": "▶ Lîstin",
        "RADIO_STOP": "⏹ Rawestan",
        "RADIO_NEXT": "⏭ Pêşve",
        "RADIO_ON": "📻 Radyo Vekirî",
        "RADIO_OFF": "📻 Radyo Girtî",
        "RADIO_STATION_1": "🎵 Stran 1",
        "RADIO_STATION_2": "🎵 Stran 2",
        "RADIO_STATION_3": "🎵 Stran 3",
        
        "PHONE_RINGING": "📞 Telefon diziqîne!",
        "PHONE_ANSWER": "📞 Bersiv bide?",
        "PHONE_CALL": "📞 Di axaftinê de...",
        "PHONE_MESSAGE": "📱 Peyama nû!",
        "PHONE_DELIVERY": "📦 Radestîna taybetî piştî 3 mêşteran!",
        
        "FOOD_PIZZA": "🍕 Pizza",
        "FOOD_PATATINE": "🍟 Patatên sorkirî",
        "FOOD_PANINO": "🍔 Burger",
        "FOOD_RISOTTO": "🍚 Risotto",
        "FOOD_CAPONATA": "🍆 Caponata",
        "FOOD_CAFFE": "☕ Qehwe",
        "FOOD_COLA": "🥤 Cola",
        "FOOD_ACQUA": "💧 Av",
        "FOOD_BIRRA": "🍺 Bîre",
        "FOOD_ARANCINA": "🧆 Arancina",
        "FOOD_CASSATA": "🍰 Cassata",
        "FOOD_CHINOTTO": "🥤 Chinotto",
        "FOOD_CANNOLO": "🥐 Cannolo",
        "FOOD_GINSENG": "☕ Ginseng"
    }
};

// Funzioni di utilità
function getLanguages() {
    return LOCAL_LANGUAGES;
}

function getCurrentLang() {
    return window.CURRENT_LANG || localStorage.getItem('waitress_game_lang') || 'it';
}

function t(key) {
    // Se esiste una funzione window.t definita altrove, usala
    if (typeof window.t === 'function' && window.t !== t) {
        const res = window.t(key);
        if (res !== key) return res;
    }

    const lang = getCurrentLang();
    const dicts = LOCAL_AUTO_TRANSLATIONS;
    
    if (dicts && dicts[lang] && dicts[lang][key]) {
        return dicts[lang][key];
    }
    if (dicts && dicts['it'] && dicts['it'][key]) {
        return dicts['it'][key];
    }
    return key;
}

function switchLanguage(langCode) {
    if (typeof window.setLanguage === 'function') {
        window.setLanguage(langCode);
    } else {
        window.CURRENT_LANG = langCode;
        localStorage.setItem('waitress_game_lang', langCode);
        if (window.game && window.game.scene) {
            window.game.scene.getScenes(true).forEach(scene => {
                scene.scene.restart();
            });
        }
    }
}

function setLanguage(langCode) {
    if (!LOCAL_LANGUAGES[langCode]) return;
    window.CURRENT_LANG = langCode;
    localStorage.setItem('waitress_game_lang', langCode);
    
    if (window.game && window.game.scene) {
        window.game.scene.getScenes(true).forEach(scene => {
            if (scene && scene.scene) {
                scene.scene.restart();
            }
        });
    }
}

// Imposta la lingua corrente all'avvio
window.CURRENT_LANG = localStorage.getItem('waitress_game_lang') || 'it';

// Esponi tutto al window object
window.LANGUAGES = LOCAL_LANGUAGES;
window.AUTO_TRANSLATIONS = LOCAL_AUTO_TRANSLATIONS;
window.t = t;
window.setLanguage = setLanguage;
window.switchLanguage = switchLanguage;
window.getLanguages = getLanguages;
window.getCurrentLang = getCurrentLang;